### ISSUE TITLE
Deploy Identities 

### ISSUE THREAD

**Issue by nhrones** [denoland/deploy_feedback#100]
Is there any way to get an isolates identity in a running app instance?

I can currently see: 
 DEPLOYMENT_ID from deno.env
 [europe-west1] in the deploy-logs (can I get this in the instance?)

Can multiple running instances of an app be started from more than one isolate in the same region?
In other words, will all running instances in the same region be running from the same isolate?

**Comment by lucacasonato** [comment]
No, multiple isolates could be running in the same region. You could assign an ID to each isolate yourself at startup though. Just do `const INSTANCE_ID = crypto.randomUUID();` in global scope.

**Comment by nhrones** [comment]
@lucacasonato Thanks for the quick reply.  Think I'll use first WebSocket client ID ('sec-websocket-key') as the INSTANCE_ID.
I'm developing a robust multiplayer peer-to-peer state-syncing strategy based on WS + BroadcastChannel.
