### ISSUE TITLE
Removal of default `deno.dev` domain

### ISSUE THREAD

**Issue by ryanccn** [denoland/deploy_feedback#102]
Hello,

I was wondering if it was possible to remove the default `deno.dev` domain associated with the project (i.e. `${PROJECT}.deno.dev`).

It would be best if there are still immutable URLs and the custom domain, but not the original `deno.dev` one.

Could you maybe treat `${PROJECT}.deno.dev` as a domain just like any other? This allows users to delete them if they want to.

Kind of like how the Vercel project domains work.

**Comment by ryanccn** [comment]
Because, well, it would be weird if you had a link shortener of your own branding `a.ryanccn.dev` but had to have something like `ryanccn-redirects.deno.dev` also attached.

When you only need one copy of the production deploy but you've got two.

**Comment by bnoordhuis** [comment]
Maybe I misunderstand your point but it doesn't strike me as particularly harmful, just a little superfluous or inelegant.

I don't mind bringing it up internally but I need to understand the impact on your project a bit better.

**Comment by ryanccn** [comment]
It's a bit... weird... if you have something running on another domain while you have your own domain.

**Comment by mathiasrw** [comment]
Not sure how many are using Deno to manage content heavy websites, but it can harm your SEO ranking drastically if google finds identical content on a seperate domains.

**Comment by lilnasy** [comment]
Cloudflare recently addressed the same issue on their pages platform with [custom headers](https://blog.cloudflare.com/custom-headers-for-pages/#what-can-you-set-with-custom-headers). It's worth checking if `X-Robots-Tag: noindex` can be set conditionally from within the code. If it works well, it could be made automatic for when you set a custom domain.

**Comment by ryanccn** [comment]
@bnoordhuis any updates?

**Comment by bnoordhuis** [comment]
It needs some changes to our data model but it's coming in the not too distant future. Think weeks, not months.

**Comment by ryanccn** [comment]
OK, thanks for the update!

**Comment by ryanccn** [comment]
It's been 2 months 😶‍🌫️

**Comment by ryanccn** [comment]
Thanks! Good to now 😄
