### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by ewiggin** [denoland/deploy_feedback#103]
I'm using handlebars template engine on my project. When I run deployctl in local it's works fine, but when I push the code and deploy on deno.com the application crash and throw this error.

```typescript
private engine: Handlebars = new Handlebars({
    baseDir: `${Deno.cwd()}/views`,
});
```

![image](https://user-images.githubusercontent.com/657517/135709523-0cc1cf96-fb9c-4483-9ce2-3232b5137daf.png)

**Comment by bnoordhuis** [comment]
Not enough of Deno's file system APIs have been implemented to support std/fs/walk yet but that is coming in the near future.

In the mean time, if you restrict yourself to `Deno.readFile()` and `Deno.readTextFile()`, you should be able to make it work but you'll probably have to fork and patch handlebars for that.

**Comment by ewiggin** [comment]
Thanks for the response!

I think sync cloud deploy limitations with local deployctl client can avoid push erroneous/unsupported code.
