### ISSUE TITLE
Allow `fetch` to use `URL` as input

### ISSUE THREAD

**Issue by eliassjogreen** [denoland/deploy_feedback#11]
Currently trying to use a `URL` object as the first parameter to a `fetch` call throws the following type error:

```
error: TS2345 [ERROR]: Argument of type 'URL' is not assignable to parameter of type 'RequestInfo'.
  Type 'URL' is not assignable to type 'string'.
```

**Comment by bnoordhuis** [comment]
Thanks for the report. Does your code look something like this?
```js
let url = new URL("...");
let req = new Request(url);
let res = await fetch(req);
```
The `Request` constructor takes either a string or another `Request` object but not an `URL` object: https://developer.mozilla.org/en-US/docs/Web/API/Request/Request

If that's not applicable, can you post example code?

**Comment by eliassjogreen** [comment]
Nevermind, it was because I was running it without the `window` lib to avoid type errors it did not work... Sorry!
