### ISSUE TITLE
Incorrect or incomplete module import in example docs

### ISSUE THREAD

**Issue by cknight** [denoland/deploy_feedback#115]
The Fresh example on https://deno.com/deploy/docs/resources-frameworks/ has the following import:

```
import { h, IS_BROWSER, useState } from "../deps.ts";
```

It is unclear to a new user how to import these dependencies or where they come from.  A better example would be to list them explicitly here without reference to `../deps.ts`.

**Comment by lucacasonato** [comment]
Fresh does not run as a single file. It is an entire framework that requires more than one file, and a specific file/folder structure. See https://github.com/lucacasonato/fresh.
