### ISSUE TITLE
Support for Deno.stat

### ISSUE THREAD

**Issue by jupegarnica** [denoland/deploy_feedback#117]
If there any plan to support Deno.stat and Deno.stat and  Deno.statSync?
It would be very nice to serve static files from deno deploy

**Comment by satyarohith** [comment]
We now support [Deno.stat](https://doc.deno.land/deno/stable/~/Deno.stat) on Deploy. We will also add `Deno.lstat` in a few days. Thanks for opening the issue.

**Comment by jupegarnica** [comment]
Nice :)
