### ISSUE TITLE
Missing Deno.readTextFileSync

### ISSUE THREAD

**Issue by pedropaulosuzuki** [denoland/deploy_feedback#118]
Hey! How's everyone going? I hope everyone's doing well.

I tried using Deno.readTextFileSync and I realized it is still unsuported. Of couse one can make it work by replacing it with this:
```ts
const file = Deno.readTextFileSync('./path').trim(); // Best method
const file_2 = ( await Deno.readTextFile('./path') ).trim(); // A way around it
```
It works, but can become a bit messy. Are there any plans to implement this and other missing Deno APIs? These can get a bit messy if we need to perform them under "non async" functions. Thanks!!

**Comment by lucacasonato** [comment]
`Deno.readTextFileSync` is now supported on Deno Deploy.
