### ISSUE TITLE
How to specify deno config

### ISSUE THREAD

**Issue by DanielRamosAcosta** [denoland/deploy_feedback#119]
I'm using custom compiler settings, this is my `deno.json` file:

```
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  }
}
```

But deno deploy does not seem to be grabbing this file, how can we specify the `--config` option?

**Comment by tlgimenes** [comment]
I'm having the same issue here

**Comment by lucab** [comment]
Thanks for the report! Deno Deploy should now be able to auto-discover `deno.json` and `deno.jsonc` files in a project, see https://deno.com/deploy/changelog#auto-discover-denojsonc-from-deployctl-deployments.
If something is still not working, feel free to open a new ticket.
