### ISSUE TITLE
Unable to use make a db connection in deno deploy

### ISSUE THREAD

**Issue by dangdennis** [denoland/deploy_feedback#128]
Env: Deno Playground

According to https://deno.com/blog/deploy-beta3/, I can create TLS connections now. I attempted to connect to my postgres-compatible cockroach db [with deno-postgres](https://deno-postgres.com/#/?id=prepared-statement). However, I  receive this error. How do I try `--unstable`?

```
TLS connection failed with message: You need to execute Deno with the `--unstable` argument in order to stablish a TLS connection
Defaulting to non-encrypted connection
```

```
const client = new Client({
  user: "xxxx",
  database: "xxxx",
  hostname: "xxxx",
  port: xxxxx,
  password: "xxxx"
});
await client.connect();
```

P.S. typo in the error message `stablish`

**Comment by lucacasonato** [comment]
Deno Deploy does not have support for the `Deno.startTls` API yet (only `Deno.connectTls`). Postgres requires the use of the `Deno.startTls`  for TLS connections though. We are stabilizing `Deno.startTls` in Deno 1.16 which will be released on November 9th. `Deno.startTls` will be available in Deno Deploy later next week.

**Comment by dangdennis** [comment]
@lucacasonato thanks for clearing it up.

**Comment by dangdennis** [comment]
Sharing an example here in case someone really wants to try it locally https://github.com/dangdennis/deno-deploy-cockroachdb-example
