### ISSUE TITLE
Logs page takes very long to load and often fails

### ISSUE THREAD

**Issue by roseMix** [denoland/deploy_feedback#129]
The logs page at `https://dash.deno.com/projects/<my-project-name>/logs` takes extremely long to load, often fails, and sometime just says: `No logs - visit <my-project-name>.deno.dev to generate logs` , even when there should be logs:

Directly browsing the actual logs path at `https://dash.deno.com/api/projects/<UUID>/deployments/latest/logs` returns:
```
{
  "code": "notAcceptable",
  "message": "The target resource does not have a representation that the user-agent would accept. Resource only available with content type 'application/json'."
}
```
PS: I'm browsing behind a proxy (but any other routes within Deno deploy - and other websites - work perfectly)

**Comment by lucacasonato** [comment]
@roseMix Does your proxy do TLS termination / HTTP proxying? That endpoint streams newline delimited JSON messages. The endpoint might not work if your proxy does not support streaming HTTP.

The "notAcceptable" code is because your browser does not send `application/json`. Does it work if you curl the endpoint?
```
curl -N https://dash.deno.com/api/projects/<UUID>/deployments/latest/logs -H "Authorization: Bearer <your-deploy-token>"
```

You can get an API token on your Deno Deploy accounts page.

**Comment by roseMix** [comment]
Thanks @lucacasonato. I edited the browser request through MS Edge dev tool to contain the auth header (and a header to to accept application/json) and I get a 200 but logs don't show with different error in the console:
 ```
net::ERR_INCOMPLETE_CHUNKED_ENCODING 200 (OK)
```

(For now I can't actually curl on this machine (because of a cert issue with the proxy), I can only do it in the browser. )

**Comment by lucacasonato** [comment]
Could you email me at deploy@deno.com with the project name where it is failing? I can dig into this then.

**Comment by lucacasonato** [comment]
Also, you can probably circumvent the auth error in curl by specifying the `-K` flag.

**Comment by magurotuna** [comment]
I'm going to close this issue as being kind of stale. Please feel free to reopen and ask if it's still happening.
