### ISSUE TITLE
Hello World types

### ISSUE THREAD

**Issue by croaky** [denoland/deploy_feedback#13]
Copying https://deno.com/deploy/docs/hello-world into my text editor:

```ts
addEventListener("fetch", (event) => {
  const response = new Response("Hello World!", {
    headers: { "content-type": "text/plain" },
  });
  event.respondWith(response);
});
```

I see the following error on `event.respondWith`:

```
[deno-ts 2339] [E] Property 'respondWith' does not exist on type 'Event'.
```

Is `event` a [`FetchEvent`](https://deno.com/deploy/docs/runtime-fetchevent)? When I add a type for the function argument:

```ts
addEventListener("fetch", (event: FetchEvent) => {
  const response = new Response("Hello World!", {
    headers: { "content-type": "text/plain" },
  });
  event.respondWith(response);
});
```

I get the following error:

```
[deno-ts 2304] [E] Cannot find name 'FetchEvent'.
```

Is there a way to pull in the types for a Deno Deploy program
to enable to jump to definitions, autocomplete, etc.?

It looks like maybe `FetchEvent` is available at [cli/dts/lib.webworker.d.ts](https://github.com/denoland/deno/blob/d6d5ced1ab90404d25a87a242ee5b03ca655abe5/cli/dts/lib.webworker.d.ts)?
But that is not exposed to my editor. I've tried in Vim and VS Code.

```
% deno --version
deno 1.8.3 (release, aarch64-apple-darwin)
v8 9.0.257.3
typescript 4.2.2
```

My apologies if this is an editor config question not specific to Deno Deploy.
I noticed @haydos585 had the same issue at 18:30 of this video:
https://youtu.be/W3vIJoVx5VM?t=1110

Thanks!

**Comment by wperron** [comment]
HI! :wave: yes, the `event` is a `FetchEvent`. It is a bit annoying at the moment I'll agree, there is an issue on the https://github.com/denoland/deployctl issue to improve the docs on how to calm the linter in vscode --> https://github.com/denoland/deployctl/issues/24

For the runtime error, make sure to use `deployctl run` instead of `deno run` and you won't have any issues at runtime.

**Comment by izznatsir** [comment]
Workaround:
In your project directory, first create `types` folder:
```bash
mkdir types
```
Then, generate the type definition to that folder:
```bash
deployctl types > types/deploy.d.ts
```
Then, create a `tsconfig.json` that has `typeRoots` configured:
```json
{
  "compilerOptions": {
    "typeRoots": ["types"]
  }
}
```
Feel free to add other configurations to the file.
Then, configure your `Deno VSCode` extension to read `tsconfig.json` you created. You can create `.vscode/settings.json`:
```json
{
  "deno.config": "tsconfig.json"
}
```
Or, configure the extension in VS Code UI.

**Comment by ChristianSiegert** [comment]
@croaky Check out https://github.com/denoland/deployctl/issues/24#issuecomment-819272065

**Comment by croaky** [comment]
@ChristianSiegert Your solution worked great, thank you!

**Comment by lucab** [comment]
Types have been reworked/unified across Deploy and standalone Deno, so this shouldn't be a problem anymore. Closing.
