### ISSUE TITLE
Environment variables issues

### ISSUE THREAD

**Issue by roseMix** [denoland/deploy_feedback#130]
I currently deployed something with multiple environment variables and found the flow very clunky. Here are some suggestions:

- It would be very useful to have a manual redeploy button for a Github-connected deployment, for instance when changing environment variables I always had to commit (or reconnect) to trigger a redeploy

- Having to manually enter each env var is tiresome - especially given that you cant view or edit any env var right after adding it - an option to upload a .env or yaml (or just a textbox to bulk paste) and it should get added would be great.

- It's quite frustrating that you can't edit or view any env var right after you save it, especially if you have multiple which you are copy/pasting and want to make sure at the end that you entered correctly. I understand the security concerns for restricting viewing/editing later on, so I would suggest adding a save button to the env page (for all env vars at once, not for each separately) and only once that is pressed there can be no further editing/viewing

**Comment by lucacasonato** [comment]
These issues have been mostly addressed. Thanks for the report!
