### ISSUE TITLE
Supports `fetch` for files in github repository with `file://` protocol

### ISSUE THREAD

**Issue by ayame113** [denoland/deploy_feedback#133]
It would be nice to be able to fetch github repositories using the `file://` protocol, like deno 1.16.
Currently "PermissionDenied: Read access not allowed" error occurs. The code I tried is [here](https://github.com/ayame113/deno-deploy-test/blob/9cbd769e534b7e1cd01b5b948504c94d116305ca/local_fetch.ts).

According to the [issue comments](https://github.com/denoland/deno/issues/2150#issuecomment-830664588), fetching local files seems to have worked in the past. Was this intentionally removed? Or is my code wrong?

**Comment by lucacasonato** [comment]
It is supported in Deno 1.16, it just has not been shipped to Deno Deploy yet. We will be addressing this is in the next few days.

**Comment by ayame113** [comment]
I got it. thank you!

**Comment by satyarohith** [comment]
@ayame113, `fetch()` now supports `file://` URLs in deploy. With a project linked to GitHub, the following source in `main.ts` should work:
```ts
import { serve } from "https://deno.land/std@0.114.0/http/server.ts";

function handler(req: Request): Promise<Response> {
  // Note: import.meta.url is a file:// URL.
  return fetch(new URL("./main.ts", import.meta.url));
}

console.log("Listening on http://localhost:8000");
await serve(handler);

```
