### ISSUE TITLE
deno oak app.fetchEventHandler() not Work

### ISSUE THREAD

**Issue by bobwatcherx** [denoland/deploy_feedback#135]
import { Application } from "https://deno.land/x/oak/mod.ts";

const app = new Application();

app.use((ctx) => {
  ctx.response= {data:"success login"}
});

addEventListener("fetch",app.fetchEventHandler());

**==> deployctl run file.ts  not work** 

**TS2339 [ERROR]: Property 'fetchEventHandler' does not exist on type 'Application<Record<string, any>>'.
addEventListener("fetch",app.fetchEventHandler());**

**Comment by lucacasonato** [comment]
Try this:

```js
import { Application, Router } from "https://deno.land/x/oak/mod.ts";

const router = new Router();
router.get("/", (ctx) => {
  ctx.response.body = "Hello world!";
});

const app = new Application();
app.use(router.routes());
app.use(router.allowedMethods());

app.addEventListener(
  "listen",
  (e) => console.log("Listening on http://localhost:8080"),
);
await app.listen({ port: 8080 });
```
