### ISSUE TITLE
Stop deploy-bot comments on commits & option to turn off preview deployments [in a branch]

### ISSUE THREAD

**Issue by amithm7** [denoland/deploy_feedback#137]
Since, deno deploy doesn't support import maps currently, I was bundling the code with gh-actions and pushing to another build branch. 

Preview deployment of other branches are meaningless. The deno deploy bot produces a comment when the same bundle file isn't found in the main branch, which is very annoying.

~A workaround is to name the file same, this prevents 404 comment, but then it seems like a check is failing.~ deploy-bot is spams regardless.

**Comment by amithm7** [comment]
I'm even getting notified of bot comments on my commit when it is in a **fork** repository.

**Comment by piscisaureus** [comment]
The bot got replaced by a proper Github app ages ago.
