### ISSUE TITLE
New repo isn't listed Git options

### ISSUE THREAD

**Issue by aslilac** [denoland/deploy_feedback#138]
I created the repo right after connecting Github to Deno Deploy, it's been about 24 hours and the repo still doesn't show up in the dropdown list

**Comment by lucacasonato** [comment]
How is the Deno Deploy GitHub application set up? Did you "Install GitHub App" on the repo you want to link?

**Comment by aslilac** [comment]
<img width="501" alt="Screen Shot 2021-11-29 at 9 05 07 PM" src="https://user-images.githubusercontent.com/418348/143983899-e09ca106-7f0d-4950-b0c3-e676331b5144.png">
 Yup, it's installed on my personal account with access to all repos. I even tried uninstalling and reinstalling the app, but it still doesn't show up.

**Comment by lucacasonato** [comment]
Oh, I think you may have run into a bug in the Deno Deploy system. Currently only the first 30 repositories in your account are shown. This should be fixed later today.

As a workaround for now, you can set the GitHub App to "Only select repositories" and select the specific repositories you want to use with Deno Deploy. As long as that list is less than 30 items long, you should be able to link just fine.

Sorry for this inconvenience - I'll ping this issue again when the bug has been fixed :-)

**Comment by aslilac** [comment]
Ahh, yup! That worked!
