### ISSUE TITLE
Want Performance API

### ISSUE THREAD

**Issue by syumai** [denoland/deploy_feedback#14]
i've created an app for Deno Deploy which uses Go WebAssembly (tinygo).
https://github.com/syumai/deno-deploy-scale-image

This app runs locally on deployctl, but fails on Deno Deploy because it doesn't support Performance API.
https://deno.com/deploy/docs/runtime-api

Want Performance API to run Go WebAssembly.

### Run locally on deployctl

```
git clone https://github.com/syumai/deno-deploy-scale-image
cd deno-deploy-scale-image
make run
# app runs on 0.0.0.0:8080
# visit this URL in browser: http://0.0.0.0:8080/image?path=landscape.jpg&width=200
```

### Run on Deno Deploy

deploy `syumai/deno-deploy-scale-image/mod.js` or visit: https://scale-image-d58e0765.deno.dev/image?path=landscape.jpg&width=200

This produces this error

```json
{"error":"process.hrtime is not a function or its return value is not iterable"}
```

This error was caused by the code below (global.performance is missing)

https://github.com/tinygo-org/tinygo/blob/master/targets/wasm_exec.js#L112

**Comment by syumai** [comment]
As a workaround, this polyfill worked.

https://gist.github.com/paulirish/5438650

**Comment by bnoordhuis** [comment]
I'll look into enabling the `Performance` API but, as expectation management, we can't enable high-resolution timers on Deno Deploy because of SPECTRE.

(We have detection and mitigation measures in place but we're not taking chances.)

**Comment by satyarohith** [comment]
We introduced Performance API several months ago: https://deno.com/deploy/docs/runtime-api. Sorry we didn't update the issue.

**Comment by syumai** [comment]
@satyarohith Thank you for mentioning about this. I'll try this feature!
