### ISSUE TITLE
Variables becoming undefined when recieving POST request

### ISSUE THREAD

**Issue by Libertas007** [denoland/deploy_feedback#142]
I was testing Deno Deploy functionality and I was making simple server using sift. Everything worked fine but when I added `version` variable, problems started to appear. When I sent GET request to `/`, `version` was as expected `"0.0.1"`. But when I sent
POST request, `version` was `undefined`.
Do you knwo what's wrong with it?
Here's my code:
```ts
import {
  json,
  serve,
} from "https://deno.land/x/sift@0.4.0/mod.ts";

serve({
  "/": home,
});

const version = "0.0.1"

function home(request: Request) {
  // Some logic...
  return json({version, data: {}})
}
```

I also tried to use `http` library, but results were the same...

**Comment by kt3k** [comment]
The code doesn't look having any issue. How do you make a POST request?

**Comment by satyarohith** [comment]
@Libertas007, the code is working as expected. Playground: https://dash.deno.com/playground/dead-hedgehog-16 

```sh
➜  ~ curl -X GET https://dead-hedgehog-16.deno.dev
{"version":"0.0.1","data":{}}
➜  ~ curl -X POST https://dead-hedgehog-16.deno.dev
{"version":"0.0.1","data":{}}
```

**Comment by satyarohith** [comment]
Closing as the code is working as expected. Please open a new issue if you still encounter problems.
