### ISSUE TITLE
No logs visible after visiting the application

### ISSUE THREAD

**Issue by ricklamers** [denoland/deploy_feedback#15]
Not sure if time delayed, but after visiting the deployed app (https://free-pigeon-11.deno.dev/) I saw no logs in 

dash.deno.com/projects/[uuid]/deployments/[id]/logs?back_to=project

**Comment by ricklamers** [comment]
Some positive feedback: love the simplicity of it all :)

**Comment by satyarohith** [comment]
Hi, @ricklamers. :)

The [json/html](https://github.com/denoland/deploy_examples/tree/main/json_html) example doesn't log anything to the console. Add `console.log`'s to the code to see some logs or deploy [this small example](https://git.io/JOUTL) which logs the requests.

Note: you need to keep the logs page of the deployment open when requests are made as logs are directly streamed to the page and not persisted. This should improve in the future.

**Comment by ricklamers** [comment]
Ah, I expected a request log or something like that. Thank you for clearing that up
