### ISSUE TITLE
Unable to clone repo

### ISSUE THREAD

**Issue by jpaquim** [denoland/deploy_feedback#151]
Trying to link [this repo and branch](https://github.com/pluvial/pluvial.xyz/tree/deno) into a new project, and I'm stuck at this step:

<img width="715" alt="Screenshot 2022-01-14 at 14 58 55" src="https://user-images.githubusercontent.com/1531031/149536794-803297a7-2f4a-4dcd-bc7f-b5aae6cabad0.png">

There seems to be something successfully registered though, as some Deno-related checks have been triggered in the PR https://github.com/pluvial/pluvial.xyz/pull/1

Any ideas for what may be causing the issue?

**Comment by lucacasonato** [comment]
Thank you for reporting this. I'll get back to you once we have figured out what is going on.

**Comment by lucacasonato** [comment]
Could you try to link the repository again? This issue should now be resolved.

**Comment by jpaquim** [comment]
I just tested again, it seems to be working well! Thank you 🚀
