### ISSUE TITLE
Stuck On 0%

### ISSUE THREAD

**Issue by MJGaming1532** [denoland/deploy_feedback#152]
![image](https://user-images.githubusercontent.com/73678945/149618784-6c03969c-75eb-4114-b9da-6750307c3a17.png)
![image](https://user-images.githubusercontent.com/73678945/149618799-05b4f40c-072d-44d2-86ba-b13338c68efd.png)

HELP ME PLS, ITS STUCKING FOR A LONG

**Comment by lucacasonato** [comment]
The issue is now resolved.
