### ISSUE TITLE
Cannot read properties of undefined (reading 'rid')

### ISSUE THREAD

**Issue by vorticalbox** [denoland/deploy_feedback#155]
I am trying to deploy a pet project I have of a simple message board but when ever my app starts I get this error 

```
TypeError: Cannot read properties of undefined (reading 'rid')     at createWritableStdioStream (https://deno.land/std@0.121.0/node/internal/streams/readable.js:1413:22)     at https://deno.land/std@0.121.0/node/internal/streams/readable.js:1451:23
--
```

repo: https://github.com/vorticalbox/dragonfly

**Comment by lucacasonato** [comment]
See https://github.com/denoland/deno_std/issues/1825

**Comment by vorticalbox** [comment]
does anyone know when this will be released to deno.dev?

**Comment by vorticalbox** [comment]
> @vorticalbox update to latest `deno_std` and the problem should go away.

I'm not using it directly so I assume a dependency is. thanks for the info
