### ISSUE TITLE
Sync username with Github after changing it

### ISSUE THREAD

**Issue by kecrily** [denoland/deploy_feedback#156]
I changed my username on GitHub, and I still have my old username on Deno Deploy.

Currently the username seems to be used when inviting members to join the organization, and having the Deno Deploy username be the same as GitHub when GitHub is the only login will give people a better idea of who they are actually inviting. 

So can I keep them consistent by allowing people to change their own usernames?

It's not very important, just a small detail

**Comment by anotherishi** [comment]
I also suffer from the same problem...
Please allow to change the username manually or automatically update with the GitHub username.

**Comment by katsuki-yuri** [comment]
Still waiting for this one to happen

**Comment by ry** [comment]
Attempt 1 https://github.com/denoland/deploy/pull/5008

**Comment by orzklv** [comment]
Can I test it or it's not available publicly?

**Comment by magurotuna** [comment]
@katsuki-yuri Not yet, but we're actively working on it. Stay tuned :)

**Comment by magurotuna** [comment]
The fix for this issue is now available. It includes sync'ing both username and fullname.

**Comment by orzklv** [comment]
Thank you very much!
