### ISSUE TITLE
Static files / CDN?

### ISSUE THREAD

**Issue by justinmchase** [denoland/deploy_feedback#157]
This is pretty cool, I'm still trying to wrap my brain around it... but typically I'd want some kind of a static file serve with CDN for web content.

I suppose I could just do the compilation, equivalent to `ng build` or whatever I wanted at startup? And then just run a static file serve over the results but... how about a CDN? It would be cool if there was just a CDN checkbox on the app which would look for a header to control caching, and would invalidate on redeploy automatically?

**Comment by vwkd** [comment]
Caching is on the roadmap, see #74.

**Comment by ry** [comment]
We haven't yet announced our static file support, but the feature is already working and available to all users. 

I'll leave it to the interested to experiment but try this https://github.com/denoland/deployctl

```
# mkdir /tmp/mypage
# cd /tmp/mypage
# echo "<h1>hello world</h1>" > hello.html
# deployctl deploy --project=deep-cow-21 https://deno.land/std/http/file_server.ts
✔ Project: deep-cow-21
✔ Found 1 asset.
✔ Uploaded 1 new asset.
✔ Deployment complete.

View at:
 - https://deep-cow-21-dhnntt577hmg.deno.dev
```

https://deep-cow-21-dhnntt577hmg.deno.dev


Or just stay tuned for the blog post.

**Comment by justinmchase** [comment]
@ry So we're saying a super simple static file server, which ends up on multiple instances around the world plus a cache layer (which is coming) and boom you effectively have a CDN?

**Comment by ry** [comment]
@justinmchase There is indeed some caching that we will add improve the example above, but I think it already qualifies as a CDN. You should be get sub-100ms latencies worldwide to https://deep-cow-21-dhnntt577hmg.deno.dev/hello.html

**Comment by justinmchase** [comment]
I see sounds good.

With this `deployctl` approach, will I be able to send args to `file_server.ts` also? Such as:

```sh
deployctl deploy --project=deep-cow-21 https://deno.land/std/http/file_server.ts -- --no-dir-listing
```

I see its already doing fallback handling for `index.html` also, very nice thanks!

**Comment by ry** [comment]
@justinmchase no you can't send args, but you can import `file_server.ts` in your own code and customize it as much as you want: https://doc.deno.land/https://deno.land/std@0.122.0/http/file_server.ts/~/serveFile

**Comment by AaronO** [comment]
@justinmchase It's important to note that `file_server.ts` isn't "special" with the new static file support you can `fetch(...)` assets or read them via `Deno.readFile(...)`/`Deno.readTextFile(...)` (or use `serveFile(...)` from std that @ry recommended)
