### ISSUE TITLE
Change production branch.

### ISSUE THREAD

**Issue by ihack2712** [denoland/deploy_feedback#16]
It would be very useful to be able to change the deploy production branch on the git integration.

**Comment by satyarohith** [comment]
Hi, @ihack2712.

The default branch of your repository on GitHub is considered as the production branch on Deploy. [Changing the default branch](https://docs.github.com/en/github/administering-a-repository/changing-the-default-branch#changing-the-default-branch) on GitHub will change the production branch on Deploy.

**Comment by ihack2712** [comment]
I know, maybe I should've been more clear.

I run two deploy projects, targetting the same repository, however, I want one of the deploy projects to target a different branch for the deploy production environment. The reason for this is because services like [Discord](https://discord.com) requires a domain for discord interactions.

So I have two different applications (on discord), one for testing and one for production. The production application points to `project1.deno.dev` whilst the testing application points to `project2.deno.dev`. Now the goal I want to achieve is that `project2.deno.dev` can use the same repository as `project1` but target a different branch for the `project2.deno.dev` subdomain.

Another possibility to avoid having multiple projects would allow projects to have multiple (static) domains targetted to different branches.

My current solution is to have two repositories, one development repository and one production repository. Bot of which is actually the same repository, but `repository2:master` is `repository1:dev`. Having that is a huge mess to manage, and not only is it messy, it also adds one unecessary repository to my profile.

I hope that clarified my problem and what I want to achieve.

**Comment by mathiasrw** [comment]
We really need to be able to set what branch triggers a push to production. Most of our repos has the develop branch as main - so that the team dont f*** up - and only a few people can push to the master branch. 

Please please please make it possible to select what branch is being pushed to production.

**Comment by lucacasonato** [comment]
This feature is now available. When linking a GitHub repo you now have to option to choose a branch other than the repository default branch for the production branch. Documentation for this feature will be available in the next couple of days.
