### ISSUE TITLE
Only a fixed number of branches are listed

### ISSUE THREAD

**Issue by roj1512** [denoland/deploy_feedback#174]
When I try to deploy an app from a repository with too many branches, only a fixed number of branches are listed in this select. Please fix it ASAP. 

![](https://cdn.discordapp.com/attachments/826085979344470037/943476714456113194/IMG_6057.png)

**Comment by satyarohith** [comment]
@roj1512, the issue is now fixed. Thanks!

**Comment by roj1512** [comment]
Super awesome!
