### ISSUE TITLE
`Deno.permissions` seems to be unavailable in Deno Deploy

### ISSUE THREAD

**Issue by justinmchase** [denoland/deploy_feedback#177]
A library I am using is calling `Deno.permissions.query` before reading environment variables. But this is crashing with an error saying `Deno.permissions` is `undefined`. What is the right way to handle this scenario?

Is there a list of API differences between deno latest, and deno deploy?

Related to https://github.com/laughedelic/github_app_auth/issues/6

**Comment by AaronO** [comment]
@justinmchase Thanks for reporting this, we'll make these APIs available in Deploy later this week

**Comment by justinmchase** [comment]
My workaround was to just patch the Deno object:

```ts
if (!Deno.permissions) {
  // todo: remove this hack once one of the following issue is resolved
  // https://github.com/laughedelic/github_app_auth/issues/6
  // https://github.com/denoland/deploy_feedback/issues/177
  (Deno as unknown as Record<string, unknown>)["permissions"] = {
    query: async () => await true,
  };
}
```

**Comment by AaronO** [comment]
@justinmchase This is now live in prod, see https://dash.deno.com/playground/kind-hare-29

Note that `Deno.permissions.revoke()` will throw, `.query()` returns "granted" for env/net/read, everything else is "denied".
`.request()` is a no-op and returns the same value as `.query()` (you can't currently change the permissions of the running isolate)

**Comment by justinmchase** [comment]
Perfect thanks!
