### ISSUE TITLE
Oak is having strange `UnexpectedEof` errors after being idle for 15s

### ISSUE THREAD

**Issue by justinmchase** [denoland/deploy_feedback#179]
I'm using Oak for a server and after a while the pod starts emitting these errors:

>     [uncaught application error]: UnexpectedEof - early eof
> 
>         at async Listener.accept (deno:ext/net/01_net.js:207:19)
>         at async accept (https://deno.land/x/oak@v10.2.0/http_server_native.ts:166:38)

![Screen Shot 2022-03-07 at 6 55 22 AM](https://user-images.githubusercontent.com/10974/157038597-700b8b86-df58-4f14-9984-b0454844d580.png)

I am wondering if after some idle time, is Deno Deploy being actively shutdown? Is there a signal being sent I should be handling to gracefully shutdown the server? These errors always seem to come at the end of the logs.

**Comment by lucacasonato** [comment]
This may well be a bug in Oak. We'll investigate. Thanks for reporting!

**Comment by scott-ling** [comment]
I just ran locally for 10hrs plus do not get the error, did the  same on a hosted VM, and also as a container, again do not see error.

I only see that error when running on Deno Deploy, in its logs... 

It is most curious...  even running with listener on all evt.. I cant replicate locally at all.  (yeah I ran test in background as I did other work..)

**Comment by mikehall314** [comment]
I am seeing the same thing running Oak 10.2 on Deploy.

**Comment by justinmchase** [comment]
When deno deploy goes idle and it shuts down the server, is it sending a kill signal to the deno process?

**Comment by ionutrogojan** [comment]
Any updates on this? I just deployed my first project and I don't know where to go from here. I have the same error logging.

**Comment by scott-ling** [comment]
nothing yet, but does not seem to be destructive I left a server running for past couple weeks or so no issues, it does seem once in a while (maybe when resources are refreshed due to inactivity on the deno side of things.)

I have not been able to find issue on the Oak side of things.

**Comment by digitaldesigndj** [comment]
<img width="1069" alt="Screen Shot 2022-06-28 at 11 20 44 AM" src="https://user-images.githubusercontent.com/539320/176254890-40c5441d-c40d-4928-9408-fcd0956574e4.png">
Same error here. does not seem to affect the site. It only happens to me in production on deno.dev. Locally I can't reproduce so I am at a loss.

**Comment by scott-ling** [comment]
yup, same here -> hoping its just a sigint issue. -> but has not caused me lost data or other issues yet

**Comment by justinmchase** [comment]
Is Oak producing background threads? I suspect the listening socket is being hard closed, probably before the server is shutdown, maybe the problem is that a sigint _isn't_ being sent before the process exits?

**Comment by kidonng** [comment]
This seems to have been answered in https://github.com/oakserver/oak/issues/483#issuecomment-1060109388.

**Comment by justinmchase** [comment]
Ok, I forgot about that. So we're saying you can add a `app.addEventListener("error", handler)` and then possibly filter out these errors?

**Comment by satyarohith** [comment]
We made a change on Dec 7 2022 that should prevent these logs. Apologies for not updating the issue.

If you're still facing seeing these logs, please re-open or create s new issue.

Thanks for your feedback.
