### ISSUE TITLE
Allow deployment without public repo

### ISSUE THREAD

**Issue by ChristianSiegert** [denoland/deploy_feedback#18]
I’d like to deploy Deno Deploy projects without making the repos public. Ideally, code could be pushed to Deno Deploy to create a deployment instead of having Deno Deploy pull code from the repo. This would allow private repos that are not even reachable from the Internet, and the use of CI/CD to create deployments when certain conditions are met. Deployments could be created via a new command like `deployctl deploy`.

**Comment by bnoordhuis** [comment]
Thanks for the feedback. Private repo support is definitely coming. Push support makes sense too.

No definite ETA yet but probably sometime in the next month or two. I'll update the issue when it goes live.

**Comment by lucacasonato** [comment]
Private repo support has landed. They can be linked in exactly the same way as public repos.
