### ISSUE TITLE
Determine whether the app is running locally or on Deno Deploy.

### ISSUE THREAD

**Issue by thomas3577** [denoland/deploy_feedback#183]
Is there a better way to determine if the application is running locally or on deno deploy?

```ts
import { Application } from './deps/oak.ts';

const app = new Application();

const local = !Deno.env.get('DENO_REGION');

const denoDeployConfig = {
  port: 8000
};

const localConfig = {
  port: 8443,
  secure: true,
  certFile: 'localhost.crt',
  keyFile: 'localhost.key',
};

await app.listen(local ? localConfig : denoDeployConfig);
```

Maybe with an environment variable named "DENO_DEPLOY".

**Comment by sylc** [comment]
one option is `DENO_DEPLOYMENT_ID` see https://deno.com/deploy/docs/projects#preset-variables

**Comment by thomas3577** [comment]
Okay, it probably doesn't make much difference if I use DENO_REGION or DENO_DEPLOYMENT_ID for this.

I also don't currently have a meaningful use case where I need to distinguish between localhost or deno deploy. Unless someone wants to use localhost with SSL for fun (like me) :).

Thanks
