### ISSUE TITLE
Suggestion: Example with mongodb to save data

### ISSUE THREAD

**Issue by Milo123459** [denoland/deploy_feedback#19]
An example of using mongodb in some way would be great, like a tutorial.

**Comment by guilt** [comment]
> It's not supported at the moment, unless there's some mongodb-as-a-service that lets you access it over HTTP (but in that case it'd be more a howto on how to talk to a web service.)

Well, there is https://www.mongodb.com/cloud/atlas 

Yeah, definitely looking forward to this example.
