### ISSUE TITLE
Consider adding support for structuredClone API

### ISSUE THREAD

**Issue by sylc** [denoland/deploy_feedback#192]
`structuredClone` is supported by deno, since v1.14, but not by deno deploy, which unfortunately I discovered to late today.

It is a convenient API to deep clone objects. Could it be considered to be added to deno deploy?

thanks

**Comment by lucacasonato** [comment]
Coming very soon!

**Comment by AaronO** [comment]
@sylc This was fixed ~9h ago

**Comment by sylc** [comment]
Thanks for the quick fix!
