### ISSUE TITLE
Random errors accessing to a site hosted on deno deploy

### ISSUE THREAD

**Issue by oscarotero** [denoland/deploy_feedback#193]
Hi. The site https://lume.land is a pure static site hosted in deno deploy.
Occasionally, the first time to access it takes like 10 seconds or so and return a SSL error. Then I reload the page and everything works fine.

The last time, after reloading the page I got the following error:
![imaxe](https://user-images.githubusercontent.com/377873/164974057-947f3d33-8079-48cd-8a9e-ee49005aed99.png)

After reload again, everything works fine. The code repository of the site is https://github.com/lumeland/lume.land

I cannot provide more info for now. The next time I get a new SSL I'll try to collect more data.
I hope it helps. Thanks!

**Comment by lucacasonato** [comment]
@oscarotero We rolled out a fix yesterday that may have resolved this issue. Can you still reproduce?

**Comment by oscarotero** [comment]
@lucacasonato Nice, thanks!
At the moment it works fine (even it seems faster!). I'll let you know if it happens again.

**Comment by oscarotero** [comment]
@lucacasonato Hi. It seems like this error appeared again. I'm getting this error once in a while since a time ago (it's in galician language but basically is a SSL error): 
<img width="1248" alt="imaxe" src="https://user-images.githubusercontent.com/377873/168595776-28ab5ab6-5ce3-451c-a3d0-599a760a2f72.png">

After reloading the page, it works fine.

**Comment by lucacasonato** [comment]
Can you click the "more info" button or the "non secure" button in the URL bar when you encounter this next time, and paste the certificate details / exact error code?

**Comment by oscarotero** [comment]
ok.

**Comment by oscarotero** [comment]
Ok, it happened again. Some screenshots:

<img width="1292" alt="image" src="https://user-images.githubusercontent.com/377873/169091371-53e7509e-f3d3-4f3c-bb33-a5e5c2987237.png">

The "Learn more" link goes to https://support.mozilla.org/en-US/kb/secure-connection-failed-firefox-did-not-connect?as=u&utm_source=inproduct



<img width="694" alt="image" src="https://user-images.githubusercontent.com/377873/169091517-12957260-e721-42df-9a93-4045cd0aec49.png">

<img width="632" alt="image" src="https://user-images.githubusercontent.com/377873/169092132-2f41526a-84b7-49f3-b0ae-03e50566e32b.png">

<img width="965" alt="image" src="https://user-images.githubusercontent.com/377873/169092757-4d49c5f5-178c-4103-a6c5-ce2ac66aebd3.png">

**Comment by oscarotero** [comment]
I'm getting this random errors in deno.com website:
<img width="1138" alt="imaxe" src="https://user-images.githubusercontent.com/377873/169647233-3044d0ec-9c7e-4f4a-8806-e8f38ab5488c.png">

**Comment by jrson83** [comment]
I also confirm, since about a week, the page runs really bad. It sometimes does not respond at all, or throws a 500 error.

**Comment by lucab** [comment]
I'm closing this issue as it got stale.
If anybody encounters TLS errors, please open a dedicated ticket.
