### ISSUE TITLE
frontend: logging objects doesn't work properly

### ISSUE THREAD

**Issue by satyarohith** [denoland/deploy_feedback#197]
![image](https://user-images.githubusercontent.com/29819102/166472038-0d58957e-b52c-4b3d-8416-9ca8c7da0fd5.png)
![image](https://user-images.githubusercontent.com/29819102/166472070-7b91beb0-27ad-4ad8-9aaa-e44ed225885b.png)

From https://discord.com/channels/684898665143206084/826085979344470037/971053921575522305

**Comment by ihack2712** [comment]
Maybe consider using xterm.js to render this properly?

**Comment by lucacasonato** [comment]
@ihack2712 We already have rendering for ANSI colors in the regular logs page, it just wasn't applied to the new playground view yet.

**Comment by magurotuna** [comment]
Coloring works like this in the playground
![image](https://user-images.githubusercontent.com/23649474/232759265-625db98d-8c14-4b83-96cd-79d2df87a0ce.png)
