### ISSUE TITLE
GitHub Actions 'on: schedule' support

### ISSUE THREAD

**Issue by croaky** [denoland/deploy_feedback#202]
I set up my static site to build with GitHub Actions and then deploy to Deno Deploy.

The workflow file is here:

https://github.com/croaky/blog/blob/main/.github/workflows/deno.yml

This is working great! The site is live at:

https://dancroak.com/

However, each article has a date. I'd like GitHub Action to publish nightly all articles with todays date >= article date.

So, I have a copy of the workflow file that runs using GitHub Actions' `schedule` / `cron` interface:

* https://github.com/croaky/blog/blob/main/.github/workflows/daily.yml
* https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

The GitHub Action did run, but it looks like Deno Deploy raised an error:

```
Error: APIError: GitHub event 'schedule' is not supported.
```

https://github.com/croaky/blog/runs/6282315380?check_suite_focus=true

Based on Discord conversation, it sounds like Deno Deploy will need to add knowledge of the GitHub event `schedule`.

**Comment by satyarohith** [comment]
Hi @croaky. We landed the feature. It should be live in a couple of hours.

**Comment by croaky** [comment]
Thanks!
