### ISSUE TITLE
Not bad

### ISSUE THREAD

**Issue by naliferov** [denoland/deploy_feedback#203]
Is code of deploy platform is open source?

**Comment by lucacasonato** [comment]
Hey @naliferov. The Deno Deploy platform itself is not open source. It is built around our open source Deno CLI: https://github.com/denoland/deno.

**Comment by naliferov** [comment]
> Hey @naliferov. The Deno Deploy platform itself is not open source. It is built around our open source Deno CLI: https://github.com/denoland/deno.

It would be good to have some api for live development to deploy some code without push to github.
