### ISSUE TITLE
Shared playground is crashing

### ISSUE THREAD

**Issue by sylc** [denoland/deploy_feedback#206]
I have created a new playground and made it public.
The shared link is crashing. ( i tried chrome, firefox and edge.)

https://dash.deno.com/playground/safe-snail-21

error:
<img width="505" alt="image" src="https://user-images.githubusercontent.com/10268458/168088967-f95d51fd-9cc1-474c-a4a2-4a2dad909bb8.png">

**Comment by ije** [comment]
@sylc  thanks for reporting, this has been fixed in https://dash-7t8b1a3sg2g0.deno.dev/playground/safe-snail-21, we will push it to production very soon.
