### ISSUE TITLE
Documentation: Typo on the Discord Slash Command page

### ISSUE THREAD

**Issue by drhayes** [denoland/deploy_feedback#21]
On this page: https://deno.com/deploy/docs/tutorial-discord-slash

A comment in a code block on that page says this:

```javascript
// Sift is a small routing library that abstracts the details like registering
// a fetch event listener and provides a simple function (serve) that has an
// API to invoke a funciton for a specific path.
```

It should say "function" instead of "funciton".

**Comment by wperron** [comment]
Fixed, thanks for letting us know!

**Comment by drhayes** [comment]
I AM NOW A CORE CONTRIBUTOR.

I mean... you're welcome. ( =
