### ISSUE TITLE
Playground media type dropdown behavior is confusing

### ISSUE THREAD

**Issue by sylc** [denoland/deploy_feedback#210]
Hi,

I got a bit confused with the behavior of the media type dropdown in the playground because it tries to deploy as soon as you change the selection. 
However the code provided to the deployment is not the current code in the playground editor, but the saved one.  

- If the code deployed is correct for the new media type, the deployment succeed but the editor is reset to the deployed code, erasing any unsaved code, which is a surprise. 
- If the code deployed is not correct for the new media type, the deployment fail. At that point the code display in the editor is still the dirty one, but the `Save & deploy` is not active. The code in the editor has to be made compatible with the old media type and the new media type, then saved and deployed, then the media type selection can be successfully changed and then code specific to that media type can be used.

In my use case, I started from a `TS` playground and then was trying to switch to `JSX`, while replacing all the code with with some valid jsx. 

Also at first it was not obvious to me that the `main.ts` was for changing the media type. It seems that it is to change the file, like if there was maybe few files accessible in the playground.

Maybe few suggestions:
- The media type dropdown should show the same as its selection option. e.g `TS` instead of `main.ts`
- Change the behavior of the dropdown to either
  - Do not automatically deploy on change and only highlight the `Save & deploy` (probably my choice)
  - Or automatically deployed but autosave at the same time the code in the playground editor
- Maybe also make the color of `Save & deploy` stand out a bit more when code is dirty by using a color different from black. 

thanks!

**Comment by ije** [comment]
great suggestion for me! i will improve this! thanks
