### ISSUE TITLE
--unstable on deno deploy

### ISSUE THREAD

**Issue by nezouse** [denoland/deploy_feedback#22]
Hi, is there a way to deploy with --unstable flag?

**Comment by satyarohith** [comment]
Hi @nezouse. 

If my understanding is correct, you're probably looking to use some unstable features of Deno on Deno Deploy. If that's true, it doesn't work as Deno Deploy is a different runtime from Deno. The APIs supported on Deno Deploy are documented here: https://deno.com/deploy/docs/runtime-api.
