### ISSUE TITLE
Getting 500 Internal Server Error when getting automatic certificates for custom domain

### ISSUE THREAD

**Issue by zainfathoni** [denoland/deploy_feedback#225]
I keep getting this error when setting up a custom domain for [my project](https://dash.deno.com/projects/waroengbumi/settings). Even after I deleted the configuration and restarted the process from the beginning, I still got the same error.

<img width="729" alt="Screenshot 2022-06-13 at 23 29 24" src="https://user-images.githubusercontent.com/6315466/173389782-a14fe9bf-58f5-4188-9b23-e8e47f4f0bce.png">

When I inspected the network calls, a `POST` call to `https://dash.deno.com/_api/projects/f72ddee2-95d6-4d58-9573-7e00ce9e2420/domains/waroengbumi.com/certificates` returns this error response:

```json
{
    "name": "ApiError",
    "status": 500,
    "code": "internalServerError",
    "traceId": "a2afc0738233a4e82521ea6c409f44ba",
    "message": "An internal server error occurred."
}
```

<img width="410" alt="Screenshot 2022-06-13 at 23 27 43" src="https://user-images.githubusercontent.com/6315466/173389793-05f360a8-7c8d-4455-8e31-7666b4fc881d.png">

**Comment by cjihrig** [comment]
@zainfathoni I took a look in our logs and the reported error is that the ACME challenge is not providing the correct value. I ran `dig` against your domain and noticed that neither the A nor the AAAA records match up with the values provided in the Deploy UI (the dialog you provided a screenshot for that includes the "Get automatic certificates" button). Can you configure those records and try again?

**Comment by zainfathoni** [comment]
I am using Cloudflare, and the Proxy status for those DNS records was `Proxied` instead of `DNS only`, hence the failure.
I have updated the Proxy status to `DNS only`, and the automatic SSL certificate creation is successful! 🎉

Thanks a lot for your help. 🙏

The `500 Internal Server Error` status misled me to think that something went wrong on the Deno Deploy side.
A different error message could have been more helpful for such issues in the future. 😁
