### ISSUE TITLE
Respond texts with `charset=utf-8` by default

### ISSUE THREAD

**Issue by kidonng** [denoland/deploy_feedback#227]
I just opened an issue regarding [`cdn.deno.land` not serving files with `charset=utf-8`](https://github.com/denoland/dotland/issues/2184), and realized this is also the case for Deno Deploy. But unlike `cdn.deno.land` which serves static files only, applications on Deno Deploy have full control over how content are served, so there are no one-size-fits-all solution.

However, leaving it completely to the users is fragile:

```sh-session
$ # This one is fine
$ curl -sI https://versailles.deno.dev/ | grep content-type
content-type: text/html; charset=utf-8

$ # But this one isn't
$ curl -sI https://morino.deno.dev/ | grep content-type
content-type: text/html
```

I suggest for common text content types `text/plain`, HTML (`text/html`), CSS (`text/css`), JSON (`application/json`), JS (`application/javascript`), Deno Deploy should serve a `content-type` HTTP header with `charset=utf-8`, unless `charset` is already specified. This reduces potential error and make Deno Deploy more developer-friendly.

**Comment by MiguelRipoll23** [comment]
Encountering this issue with Response.json, this shortcut that stringifies the response object and adds the application/json header without the encoding can be problematic.

**Comment by lucacasonato** [comment]
Deno Deploy serves the exact content type specified by the user. Our file server implementations (std/http's file server, and the fresh static file server) already serve files with `charset` parameter where applicable.

`new Response(str)` already creates a `text/plain; charset=utf-8` response. The `text/html` chatset is never automatically generated by the Deno runtime. It must always be explicitly provided by users. When it is generated by Deno related projects like fresh, they explicitly specify the `charset` parameter. The same applies to `text/css`. `application/javascript` is unconditionally consumed as UTF-8 by browsers - no `charset` needs to be specified. The charset type on `application/json` responses also does not affect browsers behaviour of JSON parsing. It is always interpreted as utf-8, unless manually handled as bytes in `fetch`, in which case the `content-type` header is not relevant at all. `application/json` also does not officially support the `charset` parameter: http://www.iana.org/assignments/media-types/application/json.

`Response.json` creates a UTF-8 encoded JSON response.

As such, we will not change the existing behavior here.

**Comment by MiguelRipoll23** [comment]
Thanks for the info, I found weird that Safari (iOS) doesn't show the emoji from my JSON response correctly and I thought the encoding from the headers response was the issue.

**Comment by kidonng** [comment]
Thanks for the clarification. I understand that browsers are smart enough to handle most cases, my original question was more oriented to scenarios outside of regular consuming, like what @MiguelRipoll23 have described (inspecting files/responses in the browser directly).
