### ISSUE TITLE
Request: retry button for transient deploy failures

### ISSUE THREAD

**Issue by forgo** [denoland/deploy_feedback#23]
I had a commit which failed and received this comment from the `deno-deploy` bot using GitHub integration:

```
failed to fetch 'https://cdn.esm.sh/v41/object-assign@4.1.1/es2015/object-assign.js': HTTP status client error (404 Not Found) for url (https://cdn.esm.sh/v41/object-assign@4.1.1/es2015/object-assign.js)
```

Hitting that same URL was not 404ing immediately after in my browser. I had a sneaking suspicion this was a transient issue. Sure enough, a dummy commit with a comment line was successful on the next push.

Unfortunately, I didn't see a clear way to retry or restart failed deploys from the [Deno Deploy Dashboard](https://dash.deno.com) or within GitHub itself to trigger again without resorting to a dummy commit.

It would be nice to have some sort of mechanism to do this, whether it's in the dashboard or via commenting to the GitHub bot.

**Comment by lucacasonato** [comment]
Closing in favor of #331
