### ISSUE TITLE
DNS: Set the appropriate record names

### ISSUE THREAD

**Issue by ngryman** [denoland/deploy_feedback#240]
Hi,

The current DNS configuration could be misleading for users.

If a user copy/paste the current configuration to their registrar, it won't work for the following reasons:
* `A` and `AAAA` records that point to the root domain need to be `@`, not the domain itself.
* `CNAME` records should not include the root domain.

Below is an example illustrating the current configuration for `example.com`:

![image](https://user-images.githubusercontent.com/892048/178479923-cc29afee-e05a-4acc-b8f2-6116a791fc40.png)

The correct version should be:

![image](https://user-images.githubusercontent.com/892048/178480035-d59f1811-e5d6-4dd0-8bd8-2fa369037afa.png)

**Comment by chezhe** [comment]
Agree. I am a frontend engineer, not familiar with DNS rule, I do as the provided records, validations failed.
BTW, thanks, bro.

**Comment by theogainey** [comment]
This would be a good change to see because I personally just had this issue and I was only able to fix it after finding this issue.

**Comment by alexbezhan** [comment]
I was struggling with domain validation for few hours. Then found this issue and it helped to fix. Thanks a lot. Must be the default instructions on the dashboard.

**Comment by satyarohith** [comment]
We've updated the instructions. They should be live in a few hours.
