### ISSUE TITLE
Getting HTTP 508 when trying to fetch from /api/hello

### ISSUE THREAD

**Issue by omar2205** [denoland/deploy_feedback#243]
Getting `HTTP 508` when fetching from `${u.origin}/api/hello`

I kept trying, and now I have a lot of deployments. #145 would help clean them.

I used a previous deployment URL, `https://other-deployment..deno.dev/api/hello`, and now it doesn't think there is a loop.

**Comment by lucacasonato** [comment]
Yes, you can not recursively fetch the current deployment. It is too easy to get into an infinite loop otherwise.

**Comment by omar2205** [comment]
But how could I fetch from my current API? Custom domain+use the deployment's URL?

**Comment by lucacasonato** [comment]
You can not fetch the current deployment from yourself. You shouldn't call your own API endpoint from the server. Instead call the function directly using a JS function call.

You can also not workaround the restriction by using a custom domain.

**Comment by omar2205** [comment]
Ok, thanks.
