### ISSUE TITLE
API to programmatically update env vars 

### ISSUE THREAD

**Issue by neves** [denoland/deploy_feedback#246]
This is necessary to sync env from services like doppler.com

**Comment by satyarohith** [comment]
Hi @neves

We are yet to stabilize and document the API. 

In the meantime, you can use the following endpoint:
```bash
curl -H 'Authorization: Bearer <auth_token>' -X PATCH -d '{"SECRET_NAME": "secret_value"}' https://dash.deno.com/api/projects/<project_name>/env
```

`<auth_token>` can be obtained from https://dash.deno.com/account#access-tokens

**Note**: A new deployment is created and promoted to production when you update the environment variables of a project.

**Comment by neves** [comment]
Thanks @satyarohith, it did work!
