### ISSUE TITLE
Projects stuck in Pending

### ISSUE THREAD

**Issue by sw-yx** [denoland/deploy_feedback#247]
while demoing, i created some projects and saw them get stuck in a Pending queue

![image](https://user-images.githubusercontent.com/6764957/180077821-f3ccdd93-6c24-481d-8058-edc5ae388061.png)

5 days on they are still there. something wrong?

**Comment by lucacasonato** [comment]
Pending means you have not yet deployed to it.

**Comment by piscisaureus** [comment]
@sw-yx your code is trying to import a non-existant module. `https://deno.land/x/htm@0.0.10/plugins.tsx` should be `https://deno.land/x/htm@0.0.10/plugins.ts`. If you fix that the project will deploy successfully.

![8F3151F8-A14A-408D-B761-141A2D9EE179](https://user-images.githubusercontent.com/218257/180131304-6bb23b1f-3dd4-4bf0-92ee-25c392de3665.jpeg)

**Comment by ije** [comment]
@sw-yx as @piscisaureus pointed, the "jsx" playground snippet was broken in latest update, we are fixing it! thanks

**Comment by sw-yx** [comment]
ah that was it. i didnt modify the sample code at all
