### ISSUE TITLE
TypeError: Deno.readFileSync is not a function

### ISSUE THREAD

**Issue by petephm** [denoland/deploy_feedback#249]
Getting this on deno deploy when using `configSync()` from the std lib dotenv:

<img width="973" alt="image" src="https://user-images.githubusercontent.com/7984905/180764645-0d1a32ba-9ee3-432b-9574-d3ca26c58397.png">

It's working locally so I'm not sure what the issue is?

**Comment by bartlomieju** [comment]
Deno Deploy doesn't support synchronous APIs (because they can block event loop), use `config` (the async version) instead.
