### ISSUE TITLE
Deploy to Deno button

### ISSUE THREAD

**Issue by tchief** [denoland/deploy_feedback#251]
Is there a button similar to [Deploy to Heroku](https://devcenter.heroku.com/articles/heroku-button) or [Deploy to Vercel](https://vercel.com/docs/deploy-button)?

Noticed in [docs](https://deno.com/deploy/docs/tutorial-discord-slash) example, which doesn't work:
```
https://dash.deno.com/new?url=https://deno.com/examples/hello_discord.ts&env=DISCORD_PUBLIC_KEY
``` 
And one more [here](https://github.com/denoland/deploy_examples/tree/ef0c3bf7eeb7f899dd6f492f57e349ef2aebbcce/telegram):
[![Deploy this example](https://deno.com/deno-deploy-button.svg)](https://dash.deno.com/new?url=https://raw.githubusercontent.com/denoland/deploy_examples/main/telegram/mod.ts&env=TOKEN,BOT_NAME)

Would be happy to contribute here, but can't find an appropriate repository (it seems to be private).

**Comment by tchief** [comment]
cc @satyarohith, as author/reviewer of that example

**Comment by dcdunkan** [comment]
@tchief It have been fixed.

**Comment by satyarohith** [comment]
Yes, we fixed the issue. Thanks!

**Comment by tchief** [comment]
Thanks! Was about to roll out simple service for this.

Is this correct, that
1. `url` is a required param, i.e. Dash do not try to resolve it from `referer`.
2. `url` could not point to a github repo, only file (`js`, `jsx`, `ts`, `tsx`).
3. `url` should point to a file, without relative file imports, like `import { handler } from "./utils.ts";`

Tried to test these, but seems these are not supported. Should I create 3 (or 1) separate issues for those you might plan to support?

**Comment by dcdunkan** [comment]
@tchief afaik,

2. `url` must point to a file with one of the supported file formats.
3. It can contain relative imports.
