### ISSUE TITLE
Fixed URL for latest preview

### ISSUE THREAD

**Issue by MiguelRipoll23** [denoland/deploy_feedback#253]
Hello!

When using Deno Deploy only as your API server, you need to build your front-end and deploy it again to be able to point it to the latest preview URL.

Right now we have a fixed URL that points to the latest production build, I suggest another fixed URL for the latest preview build as well.

Thank you, ❤️ Deno.

**Comment by ije** [comment]
like `$repo-$branch.deno.dev`?

**Comment by MiguelRipoll23** [comment]
Yup! That would work for me.

**Comment by lucacasonato** [comment]
We support `$project--$branch.deno.dev` URLs now.

**Comment by lucacasonato** [comment]
We support `$project--$branch.deno.dev` URLs now.

**Comment by MiguelRipoll23** [comment]
Thank you!
