### ISSUE TITLE
Strange behavior of setInterval

### ISSUE THREAD

**Issue by tagirov** [denoland/deploy_feedback#254]
setInterval(function() {
	console.log("run");
}, 1200000); // > 1200000

Sometimes it's works but in most cases doesn't (that is, if it doesn't work immediately after pushing the code - it doesn't work at all)

setInterval(function() {
	console.log("run");
}, 100000); // it works!

So it works for short periods of time, but not for long periods every time.

**Comment by bolchowka** [comment]
Isn't it because the instance is shut down after some inactivity time?

**Comment by tagirov** [comment]
> Isn't it because the instance is shut down after some inactivity time?

Yeah, I found it in the Heroku documentation. Never used cloud functions before.
So there is no way to implement this on a serverless platform?

**Comment by bolchowka** [comment]
https://stackoverflow.com/questions/51695859/is-it-ok-to-use-settimeout-in-cloud-functions
