### ISSUE TITLE
Add `error` and `unhandledrejection` events to runtime API

### ISSUE THREAD

**Issue by timfish** [denoland/deploy_feedback#258]
If this was supported this Sentry SDK would work
https://dash.deno.com/playground/slow-kingfisher-65

The above error doesn't currently even end up in crashes:
<img width="586" alt="image" src="https://user-images.githubusercontent.com/1150298/183057380-42f382c1-90e0-41ac-9ee7-e29234953234.png">

Serious production apps need to log and group/categorise errors. The built in logging/crashes feature is not sufficient to debug issues with large complex apps.

**Comment by bartlomieju** [comment]
Both of these events are already supported in Deploy. @lucacasonato is there any chance this change hasn't been rolled out fully?

**Comment by lucacasonato** [comment]
No, they are both rolled out and available.

**Comment by timfish** [comment]
In this case, why does `error` not get called or the error end up listed under crashes? Does it cat caught and logged to the console via `serve`?

```ts
import { serve } from "https://deno.land/std@0.145.0/http/server.ts";

addEventListener('error', (e) => console.log('oh dear', e));
addEventListener('unhandledrejection', (e) => console.log('oh dear', e));

serve((req: Request) => {
    throw new Error('Something happened');
});

```

**Comment by bartlomieju** [comment]
It gets caught internally, by our infrastructure. If you want to do some logging or network requests you should use `e.preventDefault()` to let event loop going.

**Comment by lucacasonato** [comment]
`serve` has an `onError` function argument in it's second parameter options bag, that by default catches the error and logs it using `console.errror`. You can provide your own `onError` handler if you want a different behavior (for example to `reportError` the error).

**Comment by timfish** [comment]
> you should use e.preventDefault() to let event loop going

This seems to work on Deno locally: 
https://github.com/timfish/sentry-deno/blob/8b568a3ba4814dfb041071a4abe7a93b38ccfc62/src/integrations/globalhandlers.ts#L108-L113

> that by default catches the error and logs it

Ah right, thanks, I wouldn't have expected that.

Is that desirable behaviour? Does that mean any error thrown in a handler will not end up listed in your crashes list?

**Comment by lucacasonato** [comment]
Correct. "Crashes" are for when there is an entirely uncaught exception, or you call `reportError` and do not `preventDefault` the `"error"` event.

**Comment by timfish** [comment]
In a web app, most of the code is going to be in or called by the handler, so this means that virtually no uncaught errors will result in an `error` event or end up listed in Crashes in the logs. From an error reporting perspective this is far from ideal!

**Comment by lucacasonato** [comment]
To defend the `onError` default: isolates can serve multiple requests at once. This means that if the isolate were to crash totally when a single request handler throws, all currently ongoing requests to that isolate would have to be aborted. If instead the error is just logged, then other requests can continue to work fine.

I agree that there are definitely improvements we need to make to observability inside of Deno Deploy, especially regarding historical logs. This is something we want to tackle soon, but I don't have a concrete ETA right now.

**Comment by timfish** [comment]
>  all currently ongoing requests to that isolate would have to be aborted

ah ok, understood!
