### ISSUE TITLE
Dashboard: Syntax errors with the scripts on the dashboard in Opera

### ISSUE THREAD

**Issue by code913** [denoland/deploy_feedback#26]
![Screenshot from 2021-04-28 19-18-10](https://user-images.githubusercontent.com/54856929/116415228-d9395880-a856-11eb-8963-6e4f36b87faa.png)

Any idea why?

**Comment by lucacasonato** [comment]
What Opera version are you on? Pleas update to at least Opera 67.

**Comment by code913** [comment]
Issue resolved I had outdated version of my browser
