### ISSUE TITLE
Having trouble connecting my domain

### ISSUE THREAD

**Issue by moonstripe** [denoland/deploy_feedback#266]
I've already connected one domain to a project on Deno Deploy, and I notice that the A and the AAAA records for this next project are the same as the prior one. The _acme.challenge is different, however. 

I updated the DNS records on my Cloudflare account, but when I click "Verify," I get an error message.

Are there conflicts with managing DNS from the same Cloudflare account?

**Comment by cjihrig** [comment]
> I've already connected one domain to a project on Deno Deploy, and I notice that the A and the AAAA records for this next project are the same as the prior one. The _acme.challenge is different, however.

That is expected.

Since you're using Cloudflare DNS, please ensure that the DNS records are set to DNS Only, and not Proxy mode.

**Comment by moonstripe** [comment]
@cjihrig Working now! Thank you. Note: my earlier domain is still working fine with Proxied A and AAAA records. Not too concerned, should I be?

**Comment by cjihrig** [comment]
If it is currently working, then you're probably fine. I'd personally turn off the proxy mode just to be safe.

I'll go ahead and close this out. Glad that things are working for you now.
