### ISSUE TITLE
Can't type spaces for environment variable inputs

### ISSUE THREAD

**Issue by ghost** [denoland/deploy_feedback#267]
It looks like there's no way to type spaces in the environment variables for a Deploy project. Trying to do so doesn't input a space character (nothing happens), perhaps because the input text is `.trim()`-ed on each input event. However, it is possible to *paste* text that contains a space. This applies to both the key input and the value input.

This seems like inconsistent behavior. Maybe a fix could be to trim the inputs only when the environment variables are saved?

**Comment by satyarohith** [comment]
We fixed the problem. Thanks for opening the issue!
