### ISSUE TITLE
unable to connect to isolate, terminated

### ISSUE THREAD

**Issue by Smilex11** [denoland/deploy_feedback#276]
unable to connect to isolate, terminated
code: DEPLOYMENT_FAILED

**Comment by satyarohith** [comment]
Hi, @Smilex11. Can you provide details about your project?

This is an issue we are seeing recently. The error message is cryptic and we will improve it.

**Comment by Smilex11** [comment]
This is the project address https://github.com/Smilex11/NetEaseCloudMusicLyric,
This project references cryptojs from npm, I think the main error comes from deno importing cryptojs

**Comment by Clownsw** [comment]
@satyarohith

**Comment by Smilex11** [comment]
I update my code, use unstable import npm package, But it still doesn't work @satyarohith

**Comment by Smilex11** [comment]
[](https://github.com/Smilex11/NetEaseCloudMusicLyric/blob/master/common.js#L5)

**Comment by cleverplatypus** [comment]
Having the same issue. No access to meaningful error log. 
Only showing
```
unable to connect to isolate, terminated
2022-09-05 08:34:50
```
And by the way, the Log UI generally only shows a truncated tail of the logs, often missing the part of the error with the useful info.

**Comment by cleverplatypus** [comment]
Gaaak! Found the culprit, unless it's a red herring.

There was a comma at the end of a deconstructed object in an import

Changed
```
import {
  AppConfigSchema,
  SponsorshipTypeSchema,
  AuthoredFragmentSchema,
  StallApplicationSchema,
  SponsorshipInfoRequestSchema,
  UserSchema, // <-------
} from '../schema.ts';
```
to
```
import {
  AppConfigSchema,
  SponsorshipTypeSchema,
  AuthoredFragmentSchema,
  StallApplicationSchema,
  SponsorshipInfoRequestSchema,
  UserSchema
} from '../schema.ts';
```
and the issue went away.

There must be a better way to spot these issues without resorting to lucky guesses and fumbling and sifting through commits.

I love Deno and Deno Deploy but this is one of the hurdles that can seriously affect early adoption.

Peace

**Comment by gvbl** [comment]
I'm seeing this after deploying the Fresh bootstrap project, no changes.  I did setup a custom domain.  Is it possible this gateway error occurs until DNS propagation?

**Comment by Industrial** [comment]
I'm also getting this issue. I deployed a Fresh app and it worked but as I made changes and deployed more complicated code then basic examples the deployment stopped working and I got this error message.

Would just printing out the error that happened expose too much information?

**Comment by Industrial** [comment]
I fixed my bug with this: https://github.com/denoland/fresh/issues/774#issuecomment-1249933168

**Comment by forgo** [comment]
I'm getting this exact same error when deploying the hello world example as `index.ts` as the only file in my GitHub linked repo (public). I tried unlinking and linking again, but got the same error. I'm not using any dependencies at all, so I'm not sure how the linked solution helps here.

The logs show the `console.log`s from the run script, so I'm not sure what's preventing the deploy itself from finishing.

<img width="962" alt="Screenshot 2022-09-17 at 8 49 27 PM" src="https://user-images.githubusercontent.com/5361286/190883432-2c49f955-8089-494b-9a0f-cc9d909ea4fd.png">

https://github.com/forgo/elliott.software/blob/main/index.ts


```
function capitalize(word: string): string {
  return word.charAt(0).toUpperCase() + word.slice(1);
}

function hello(name: string): string {
  return "Hello " + capitalize(name);
}

console.log(hello("john"));
console.log(hello("Sarah"));
console.log(hello("kai"));
```
