### ISSUE TITLE
TypeError: Headers are immutable. (doc invalid)

### ISSUE THREAD

**Issue by lowlighter** [denoland/deploy_feedback#28]
Example from the docs https://deno.com/deploy/docs/serve-static-assets probably doesn't work:
```ts
const response = await fetch(style);
// Set the appropriate content-type header value.
response.headers.set("content-type", "text/css; charset=utf-8");
// Return the response with modified content-type header.
return response;
```
I'm doing something similar ang get the following:
```
❗️ | TypeError: Headers are immutable.
    at Headers.set (deno:op_crates/fetch/20_headers.js:348:15) 
    at async respondWith (deno:js/10_sr.js:58:14)
```

Someone on the discord suggested me an answer, so the docs should be updated with this instead:
https://github.com/denoland/doc_website/commit/18bb0696be2734b6f951288b2b5996ef2ab9564f

**Comment by wperron** [comment]
Fix deployed.
