### ISSUE TITLE
[Documentation] "Example Outbound" is not found

### ISSUE THREAD

**Issue by dector** [denoland/deploy_feedback#281]
STR:
- Open https://deno.com/deploy/docs/runtime-fetch
- Scroll to the bottom
- Click on [Make an outbound request](https://deno.com/deploy/docs/example-outbound)

ER:
- Documentation page is opened

AR:
- HTTP 404

**Comment by lucab** [comment]
Thanks for the report! This has been fixed a few weeks ago together with other docs improvements.
