### ISSUE TITLE
Fix for the 404 page that is off-centered and overflowing the viewport on mobile

### ISSUE THREAD

**Issue by CetinSert** [denoland/deploy_feedback#282]
[**RTCode.io**](//rtcode.io) ([try](//rt.ht), [learn more](//efn.kr/b/sync)) – The next-gen, no-reload, real-time web playground with instant two-way input ⇄ output sync.

---

## Issue

1. visit https://404.deno.dev
2. notice it is off-centered!!!
    1. desktop: slight annoyance for the obsessive
    2. mobile: ⚠️ page does not fit into screen!

## Fix

1. remove `class` `p-4` from `body > div:first-child` on the `404` page

```diff
<body>
-  <div class="flex flex-col items-center justify-center w-full h-screen p-4 bg-repeat bg-center font-sans" ⋯
+  <div class="flex flex-col items-center justify-center w-full h-screen bg-repeat bg-center font-sans" ⋯
```

## Screenshots on mobile

| before | after |
| - | - |
| ![404 deno dev_(Samsung Galaxy S20 Ultra)](https://user-images.githubusercontent.com/27027/189045974-495c8fef-0943-44a2-98be-ea33f2d2e35f.png) | ![404 deno dev_(Samsung Galaxy S20 Ultra) (1)](https://user-images.githubusercontent.com/27027/189046002-851468ea-8b7c-4271-bcad-48fcb9d6f7ab.png) |

---

[**RTCode.io**](//rtcode.io) ([try](//rt.ht), [learn more](//efn.kr/b/sync)) – The next-gen, no-reload, real-time web playground with instant two-way input ⇄ output sync.

**Comment by lucab** [comment]
Thanks for the report! We kept the page padding, but adjusted the styling so that sizes are properly calculated. This should be fixed now.
