### ISSUE TITLE
error deploying project using supabase in npm

### ISSUE THREAD

**Issue by NuvensCorporation** [denoland/deploy_feedback#286]
Error The deployment failed: Module not found "npm:@supabase/supabase-js".

**Comment by NuvensCorporation** [comment]
tha same happnes if i use express:
import express from "npm:express";

**Comment by lucacasonato** [comment]
`npm:` specifiers are still unstable. Deno Deploy does not support any unstable Deno features, so you can not use `npm:` specifiers in Deno Deploy yet.
