### ISSUE TITLE
Getting `navigator.hardwareConcurrency` throws an error

### ISSUE THREAD

**Issue by gildas-lormeau** [denoland/deploy_feedback#287]
I was informed that zip.js (https://deno.land/x/zipjs/index.js) did not work on Deno deploy because getting `navigator.hardwareConcurrency` throws an error, see the issue here: https://github.com/gildas-lormeau/zip.js/issues/367. For the record, I circumvented this issue by catching the error when getting `navigator.hardwareConcurrency`.

**Comment by lucacasonato** [comment]
This is now fixed. Thanks for the report!

**Comment by gildas-lormeau** [comment]
Thank you also for the quick fix!
