### ISSUE TITLE
How does CPU time calculated in deno deploy?

### ISSUE THREAD

**Issue by vicary** [denoland/deploy_feedback#290]
I was redirected from https://github.com/denoland/deno/discussions/15988#discussioncomment-3731442. I am not sure how to phrase this as an issue, no immediate actionable items here, just a question.

Quoting the original question below.

> From the pricing page, CPU time is explicitly noted as "not wall clock time", but I have yet to find a documentation with such definition.
> 
> How does a it counts towards CPU time when, for example, SSR fetches a database?

**Comment by cjihrig** [comment]
Take a look at https://serverfault.com/questions/48455/what-are-the-differences-between-wall-clock-time-user-time-and-cpu-time. That thread breaks down the different types of time. SSR fetches to a database should count as I/O time and wall time, but not CPU time.

**Comment by vicary** [comment]
Thanks for the rely.

The linked answer surely clarifies many of my initial thoughs, it does opens up more precise questions at the same time.

Apologies for my lack of knowledge over these definitions:

1. Does the term "CPU time" includes both user time and system time?
2. For example if some SSR library invents a way to utlitize the workers API, does the CPU time counts (and accumulates) independently in all the treads involved?
3. When does CPU time starts counting? Does it includes the initialization phase where Deno loads up all the vendored imports before it can actually handle requests?

**Comment by cjihrig** [comment]
The CPU time should include all time that your code is running on the CPU (user or system time, across all threads). This includes time where the code is processing dependencies before requests can be handled.

**Comment by vicary** [comment]
The 10ms / 50ms timeout for deno deploy feels a bit restrictive, I may need some precise understandings on my own application to know how much I can work with. Is there a recommended way to do profiling when preparing our code for deno deploy?

Asking from another perspective, is there a general motivation behind the 10ms/50ms timeout? For example, 
1. Is there a designated usage model? For example: preact and lightweight data fetching only, nothing else, or
2. It's deno not ready for pro-rata billing from CloudFlare Worker Unbound just yet, but may open up more options in the future.

**Comment by shinebayar-g** [comment]
I agree. If Deno did give users a clear, straightforward examples of these limitations, users could be more aware of the situation instead of playing guessing games.
