### ISSUE TITLE
Deno Unsuportede protocol AMQP

### ISSUE THREAD

**Issue by NuvensCorporation** [denoland/deploy_feedback#297]
{"error":"Unsupported protocol"}
i get the above error when trying to use amqp protocol in deno with this library: 
https://deno.land/x/amqp@v0.17.0

**Comment by justinmchase** [comment]
What are you trying to connect to? What is that error emitting from? Very hard to tell what's going on without more info.

**Comment by NuvensCorporation** [comment]
i created a rabbitmq instance in RabbitMQ , i tried connect using deno, with tha package https://deno.land/x/amqp@v0.17.0,
when i make the connection to the server give this error.

**Comment by justinmchase** [comment]
What gives the error? Its thrown, or written to stdout, or stderr?  Whats the callstack, where is the rest of the information about the error? What is your connection configuration, what is your server configuration? Please provide more relevant information, what you're sharing here is not enough for anyone to help you.

Here are the docs on the limits of Deno Deploy:
https://deno.com/deploy/docs/runtime-sockets

AMQP is a TCP based protocol, here you can see the call to [`Deno.connect`](https://deno.land/x/amqp@v0.17.0/src/amqp_connect.ts?source#L26) in their code, so this library should be fine to use in deno deploy. 

It seems likely that you have an issue with that particular library or your server/client configuration. Maybe head over to this repo and fill out an issue and see if they can help identify the problem:
https://github.com/lenkan/deno-amqp/issues
