### ISSUE TITLE
Ability to delay deploy until other ci checks

### ISSUE THREAD

**Issue by lowlighter** [denoland/deploy_feedback#30]
Sometimes production branches have additional checks/build steps that are skipped on pull requests but may be required for deployment, so it would be nice if deno deploy is able to wait until these are performed.

In case of failures, I think the best would be to auto-cancel deployment so published version is guarenteed to be working

**Comment by satyarohith** [comment]
For automatic deployments, we promote a deployment to production after validating that it works. You can read more about it [here](https://deno.com/deploy/changelog#automatic-deployment-validation-on-deno-deploy).

If you need more control, you can use the [deployctl](https://github.com/denoland/deployctl) github action.

Thanks for opening the issue.
