### ISSUE TITLE
Redeploy same commit

### ISSUE THREAD

**Issue by vwkd** [denoland/deploy_feedback#300]
Sometimes it’s necessary to redeploy the same commit.

For example, when an unversioned dependency changes. This might be useful for rapid development where one controls both the dependency and the dependent.

Currently, one workaround is pushing an empty commit. But this is cumbersome, as it requires changes to the repository instead of just a button click in the Deno Deploy dashboard. Also, if keeping a clean history is desired, one needs to reset the empty commit and push again, which creates more friction by having to temporarily stash and unstash any changes that happened in the meantime.

This might be a more general solution to https://github.com/denoland/deploy_feedback/issues/23 too.

**Comment by lucacasonato** [comment]
Closing in favor of #331
