### ISSUE TITLE
Can not makig API call inside deno deploy that longs more than 60 seconds

### ISSUE THREAD

**Issue by NuvensCorporation** [denoland/deploy_feedback#304]
Hello, my project uses deno with OAK for API routes, and in this project I am using deno fetch API to make an API call that takes about 80 seconds to return the result, on my local machine it works normally, but only when I deploy in deno deploy the call forever at 60 seconds and it cannot complete the operation and gives this error in POSTMAN: Error: Failure when receiving data from the peer

**Comment by justinmchase** [comment]
So are you saying, you call your api, which then calls out to another api, and that 3rd party api can take 80s to respond? Where is the error surfaced, your postman client or in the backend api?

80 seconds is beyond most web api's threshold for acceptable response times, really more than just a second or two is not usually acceptable and most timeouts will be 30s or 40s and I do believe Deno Deploy will automatically load balance your incoming requests. So if your post man client is getting a timeout at 80s but your backend is not recieving an error then that is likely your answer. 

If the backend is getting an error calling the remote 3rd party api then its a bug in that api, nothing you can call across the web should take that long. Likely they should be doing an asynchronous operation with result, if it actually takes 80 seconds for some reason. Meaning the initial call should immediately return with a command id, then you call the server back with that id asking for the status until the operation is complete. You can improve that by using websockets but its the same pattern.

Don't count on 80s response times, don't accept any API which has longer than 3s response times on average.

```mermaid
sequenceDiagram
  participant A as Browser
  participant B as API
  participant C as 3rd Party

  A->>B: Sends command to initiate long running operation
  B->>A: Queues command, returns `{ commandId }`
  B->>C: Executes queue in background, calls 3rd Party API to do work
  A->>B: Calls GetCommand(commandId)
  B->>A: Responds immediately with `{ status: 'InProgress' }`
  C->>B: Long running call returns, command completes.
  A->>B: Calls GetCommand(commandId)
  B->>A: Responds immediately with `{ status: 'Complete', result: {...} }`
```

**Comment by NuvensCorporation** [comment]
let me explain again, I created an API with Deno using the Oak framework, right? so this API calls a 3rd party API to perform a certain processing, and this 3rd party API takes up to 2 minutes to respond because it needs user interaction, so it is necessary that my API in deno waits until the 3rd party API gives the answer.
This process is happening normally with my API in deno running locally, but when I upload the code in Deno Deploy, when making the call, deno Deploy cuts off as soon as it hits 60 seconds, exactly 60 seconds and not 61 or 62, which indicates that Deno deploy is interrupting the process when completing the exact 60 seconds.

**Comment by NuvensCorporation** [comment]
Hello, thanks for the feedback, the problem is in option A, Deno deploy is interrupting the connection with my postman as soon as it reaches 60s, the third-party API is not mine, we are just consuming it and it really takes up to 130s to finish processing, so Deno deploy should wait for this API to finish and then give me the return, which is not happening, because Deno deploy is ending before.

**Comment by justinmchase** [comment]
Ok, thanks. Yeah that is very common, I don't think its reasonable for Deno to allow you to have an http connection open for longer than 60s, you're going to need an alternate design.

See the command pattern and the diagram in the initial reply for example.
https://en.wikipedia.org/wiki/Command_pattern

You'll need a database and a queue possibly.

**Comment by NuvensCorporation** [comment]
i will add a timeout of 60s to control this, thanks
