### ISSUE TITLE
Logs don't seem to show up

### ISSUE THREAD

**Issue by dyedgreen** [denoland/deploy_feedback#307]
I'm using Deno deploy to host a small fresh web app, which logs each request using middleware using

- `console.error`
- `console.warn`
- and `console.info`

(giving a single string argument to each which contains some basic information like the date, url visited, etc)

I'm trying to view logs using Safari (and also briefly tried Firefox), but when I browse the page, no logs seem to show up (I opened the logging panel first, then kept it open while browsing the page to wait for logs).

**Comment by mattezell** [comment]
+1 - Same. 

I assumed I was doing something in my project to mess things up, but even viewing official sample projects fail to display console.* entries - they don't show in the logs slide-out, nor do they display in the console area of developer tools (Chrome, Edge, Firefox). 

Since this was my first Deno Deploy project, it made debugging issues significantly more difficult - which, on the bright side, made me have to actually dig into the docs, which resulted in me learning a bit more (though not how to get console.log to work 🤣).

**Comment by whomwah** [comment]
+1 bump

<img width="775" alt="Screenshot 2022-11-03 at 10 26 06" src="https://user-images.githubusercontent.com/2031/199697703-2ad5dd64-97c2-49f9-a0e9-7d40430e264a.png">

**Comment by dalyd14** [comment]
+1 Bump
Seeing the same thing. Anyone find a work-around?

**Comment by lucacasonato** [comment]
We are working on this. Sorry for the inconvenience.

**Comment by lucacasonato** [comment]
Fixed now. Once again very sorry for the inconvenience.

**Comment by memiux** [comment]
Mmm... I think that they're broken again.
![v2z3o8_r1_250](https://user-images.githubusercontent.com/37290/202538142-1ea8b998-0f9e-431d-9ebe-eb446ffd0dab.gif)

**Comment by Snurppa** [comment]
> Mmm... I think that they're broken again. ![v2z3o8_r1_250](https://user-images.githubusercontent.com/37290/202538142-1ea8b998-0f9e-431d-9ebe-eb446ffd0dab.gif) [ ![v2z3o8_r1_250](https://user-images.githubusercontent.com/37290/202538142-1ea8b998-0f9e-431d-9ebe-eb446ffd0dab.gif) ](https://user-images.githubusercontent.com/37290/202538142-1ea8b998-0f9e-431d-9ebe-eb446ffd0dab.gif) [ ](https://user-images.githubusercontent.com/37290/202538142-1ea8b998-0f9e-431d-9ebe-eb446ffd0dab.gif)

Yeah same. Can't see anything happening, though I am hitting successful responses for routes that definitely have some logging side-effects.

**Comment by memiux** [comment]
@lucacasonato Non-Chromium based browsers such as Firefox and Safari, can't parse strings like "2022-11-23 20:47:09.867428066 UTC" as date. <sup>[1]</sup>

![Screen_Shot_2022-11-23_at_14 52 15](https://user-images.githubusercontent.com/37290/203836075-a2be9ba2-39f4-44b2-915e-3638650348c3.png)

The API endpoint [...]/deployments/latest/logs should return the `time` attribute as iso8601 `YYYY-MM-DDTHH:mm:ss.sssZ`.

Actual:
```
{"time":"2022-11-23 20:47:09.867428066 UTC","message":"isolate start time: 2.30 ms","level":"debug","region":"us-south1"}
```

Expected:
```
{"time":"2022-11-23T20:47:09.867Z","message":"isolate start time: 2.30 ms","level":"debug","region":"us-south1"}
```


1. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/Date#date_string

**Comment by sibljon** [comment]
I just wanted to +1 and note that I'm not able to see logs either on the Deno Deploy web interface, but I do see a single item in the "Crashes" tab (not sure if I had multiple uncaught exceptions or not – so I'm not sure if this is accurate, or should include more things).

Thanks in advance for your time, Deno team!
