### ISSUE TITLE
Compress served responses ?

### ISSUE THREAD

**Issue by lowlighter** [denoland/deploy_feedback#31]
I'm not sure, but I think that served responses are not compressed?
Is there a way (or plans) to compress responses to speed up response time?

Example deno deploy app:
![image](https://user-images.githubusercontent.com/22963968/117568876-22916f80-b0c3-11eb-9689-aee263caa715.png)

Example nginx + express + compress:
![image](https://user-images.githubusercontent.com/22963968/117568908-43f25b80-b0c3-11eb-8913-8206f0434209.png)

**Comment by satyarohith** [comment]
The response body is now compressed with either brotli or gzip: https://deno.com/deploy/docs/compression

**Comment by lowlighter** [comment]
Nice !

**Comment by melhosseiny** [comment]
Not sure if I'm doing something wrong, but I have `accept-encoding: gzip, deflate, br`, `content-type` is `application/javascript`, and response size is 6400 bytes and I'm getting uncompressed responses and no `content-encoding` in the response

**Comment by lucacasonato** [comment]
Response body compression had to be temporarily disabled due to some infrastructure changes. We will be re-enabling the feature soon.

**Comment by satyarohith** [comment]
Automatic compression is now active.

Docs: https://deno.com/deploy/docs/compression

**Comment by mashaal** [comment]
I've been trying to debug why compression still seems to be disabled on all of my deployments.

This is a vanilla css file that I am serving statically. Correct `content-type` and request headers as far as I can tell?

https://ultrajs.dev/style.css

Site for reference, all of the other files do not have compression either: https://ultrajs.dev

---

![image](https://user-images.githubusercontent.com/6100364/158047307-a5c51cb4-f9f5-43bf-b962-c88aaa120d81.png)
