### ISSUE TITLE
Which Deno version is used?

### ISSUE THREAD

**Issue by jakeg** [denoland/deploy_feedback#310]
Currently my site runs on Heroku and I use `Deno.version.deno` to get the current version, but this API isn't supported on Deploy. How can I find out what version of Deno is being used?

Similarly, I can't do `Deno.memoryUsage()` to find out about memory usage on Deploy.

**Comment by timfish** [comment]
The Deploy runtime aims to be similar to the Deno runtime but differs quite significantly:
https://deno.com/deploy/docs/runtime-api

**Comment by jakeg** [comment]
Yes, I understand that. But when new Deno releases are made when do changes from them get released to Deploy? And when changes do occur, is there a way to pin a project to an old release in case of incompatible API changes? eg when flash (`Deno.serve()`) becomes stable, when will it be added to Deploy?

**Comment by lucacasonato** [comment]
We aim to be out of date by at most 2 weeks with upstream Deno releases. For big runtime features such as `Deno.serve` you can expect them to be available in Deno CLI and Deno Deploy within the same week.

**Comment by magurotuna** [comment]
I'm going to close the issue since I suppose Luca's answer suffices. Also to answer another question:

> is there a way to pin a project to an old release in case of incompatible API changes?

Unfortunately there's no such a way.


Feel free to ask if you have other questions.

**Comment by lucacasonato** [comment]
> is there a way to pin a project to an old release in case of incompatible API changes?

This is also not needed, as we don't make incompatible API changes.
