### ISSUE TITLE
Support npm: specifiers

### ISSUE THREAD

**Issue by so1ve** [denoland/deploy_feedback#314]
`npm:` specifiers are stable now, but Deno Deploy still doesn't support it.

**Comment by so1ve** [comment]
Sorry = =

**Comment by siygle** [comment]
Any update on this issue?
Really want to use the npm compatibility on Deno Deploy directly, that's really helpful for dev. 🤞😃

**Comment by dnk8n** [comment]
I must say, from a fresh user (excuse the pun), this information wasn't obvious to me. Had I been forewarned, I would have avoided the route I ended up taking. Is it possible to make this caveat a bit more visible? What are the isolated issues that need to be closed in order to have this feature?

Looking for other ways to import package so that I can remain on deno deploy. Just when I thought I was done developing :(.

Is there not a way for a warning to appear during `deno task start`? One which cautions a user that if they are using deno deply, npm specifiers won't be able to be deployed?

**Comment by so1ve** [comment]
Well, I think there is a workaround: if the deno bundle supports the `npm:` specifier, we can run the bundle locally and upload it afterwards

**Comment by bobmoff** [comment]
I dont think the bundle/pack command supports npm specifiers yet 😢

https://github.com/denoland/deno/issues/15960

**Comment by satyarohith** [comment]
Status update: we are working towards supporting `npm:` specifiers in Deno Deploy and it's a priority for us, but it will take time and we don't have an ETA yet.

**Comment by nzoschke** [comment]
Is there a way to work around this with import maps?

I have this error

```
The deployment failed: Module not found "npm:protocol-buffers-schema@3.6.0".
```

I tried this import map but no luck:

```json
{
  "imports": {
    "npm:protocol-buffers-schema": "https://esm.sh/protocol-buffers-schema@3.6.0"
  }
}
```

**Comment by Roosteridk** [comment]
any update on this?

**Comment by vixalien** [comment]
> any update on this?

I think they just announced `npm:` specifiers in `deno compile` as beta, so I hope the next step will be deploy

**Comment by MarkBennett** [comment]
> > any update on this?
> 
> I think they just announced `npm:` specifiers in `deno compile` as beta, so I hope the next step will be deploy

Perhaps [this is what you're referring to](https://github.com/denoland/deno/pull/19005) @vixalien? Looks like you might be right that support in `deno compile` is coming, so hopefully support on Deno Deploy won't be far behind!

**Comment by so1ve** [comment]
Update: Deno Deploy supports node builtins now!

https://deno.com/blog/node-builtins-on-deploy

**Comment by vixalien** [comment]
seems it's just `node:` specifiers and **NOT** `npm:` specifiers.

> We are working to bring [npm specifiers](https://deno.com/manual/node/npm_specifiers) support natively to Deno Deploy. Stay tuned for updates on this soon.

**Comment by so1ve** [comment]
> seems it's just `node:` specifiers and **NOT** `npm:` specifiers.

Yes you are right, but node specifiers are already supported, will npm be far away? :)

**Comment by rlee1990** [comment]
Are there any new updates on this?

**Comment by lucacasonato** [comment]
It's finally here.
NPM support on Deno Deploy.
Import over 2 million NPM modules from the edge.

:boom:

https://deno.com/blog/npm-on-deno-deploy
