### ISSUE TITLE
Is a directory (os error 21) - Internal Server Error

### ISSUE THREAD

**Issue by Astisme** [denoland/deploy_feedback#318]
Hello deno!

I'm having a little bit of trouble with the deployment of my Astro website even though I'm pretty sure that it's not their fault as the preview in dev mode works fine.

Currently I'm getting an `Internal Server Error` when trying to access my website on deno.
Looking through the logs, I get the error in the picture.

![Is a directory os error 21](https://user-images.githubusercontent.com/96465880/206525322-1ea68415-0a5f-4271-b74f-b6750131bed5.png)

I've followed Astro's instructions to setup deno as the adapter both as [an integration](https://docs.astro.build/en/guides/integrations-guide/deno/) and as [a deploy medium](https://docs.astro.build/en/guides/deploy/deno/).

What should I do? Do you need anything to help you solve this case?
The source is [laying around on Github](https://github.com/Astisme/alfredoit-dev)
Thanks :sauropod:

**Comment by lino-levan** [comment]
ref: https://github.com/withastro/astro/pull/5573

**Comment by lino-levan** [comment]
Pretty sure this is an upstream issue, but I think we should keep this open until we can confirm this.

**Comment by Astisme** [comment]
![image](https://user-images.githubusercontent.com/96465880/208307353-b0cb0e1c-6f8a-44a0-ae79-2d05fd9a87b2.png)

I'm still getting the same error after reinstalling the whole project.

I guess this isn't the only fix there is to it.

**Comment by Astisme** [comment]
Ok so basically this is why this error was coming up (it has nothing to do with Deno and only with Astro):

I created a websiteConfig.json file which contained the website name and the favicon name.
I put this file inside the public folder and was then importing it from the files in the src directory.

While I was using npx astro dev, everything was working as expected (I suspect because I was in localhost) but when I then pushed to Deno, the file configuration obviously changes and everything broke.

# Fix

The fix here is to use the src/config.ts file for any configuration.

My problem was that I didn't find this file until I created a new Astro project from scratch (not the basic one).
