### ISSUE TITLE
Please support Decorators

### ISSUE THREAD

**Issue by thomas3577** [denoland/deploy_feedback#319]
Decorators are such a fine thing and there are already some packages that use it. e.g. [Danet](https://deno.land/x/danet@1.3.2), [oak_nest](https://github.com/jiawei397/deno-oak-nest), [alosaur](https://github.com/alosaur/alosaur).

**Comment by lucacasonato** [comment]
We will not support decorators in Deno Deploy until web standard decorators ship in Chrome stable.

**Comment by thomas3577** [comment]
That makes sense
