### ISSUE TITLE
we need a simpletuto for  deploy helloword with oak or http module 

### ISSUE THREAD

**Issue by elycheikhsmail** [denoland/deploy_feedback#32]

**Comment by wperron** [comment]
We have a [hello world example in the official docs](https://deno.com/deploy/docs/hello-world) and Oak has a [page about Deploy integration](https://oakserver.github.io/oak/deploy), what else are you missing?

**Comment by elycheikhsmail** [comment]
> We have a [hello world example in the official docs](https://deno.com/deploy/docs/hello-world) and Oak has a [page about Deploy integration](https://oakserver.github.io/oak/deploy), what else are you missing?

thank you all you said is right. but I just see deploy option in oak docs today, in fact I don't searche oak option inside oak docs instead I think it must be in serverless provider like deno deploy. any way if deno deploy have link to oak deploy it will be usefull.
