### ISSUE TITLE
Domains on demand

### ISSUE THREAD

**Issue by bardouni** [denoland/deploy_feedback#321]
At https://www.lightfunnels.com/ we are using cloudflare for ssl and cloudflare workers to serve "Funnels/Stores" for our users with custom domains.
We are experimenting Deno deploy to see if it would work better since CF's workers have some limitations, Is it possible to somehow be able to add more domains , It's oky to pay for extra domains just like cf's 0.1$/Domain.
Thank you

**Comment by lino-levan** [comment]
Do you mean subdomains?

**Comment by bardouni** [comment]
I mean domains 
and an api to manage it
I heard this is not possible atm

**Comment by lino-levan** [comment]
You don't have to close it? This is cloud feedback. This is the right place for this sort of thing.
