### ISSUE TITLE
deploy must be a standalon section in deno.land menu ?

### ISSUE THREAD

**Issue by elycheikhsmail** [denoland/deploy_feedback#34]
are you agree with me ? it make deploy section more visible

**Comment by satyarohith** [comment]
We do have a link to Deploy on the navbar. Thanks!

![CleanShot 2023-05-20 at 12 29 46@2x](https://github.com/denoland/deploy_feedback/assets/29819102/f5f3f501-979c-473f-88d4-a1190b361dca)
