### ISSUE TITLE
Deploy/Fresh - long delay in generating response for twind plugin, main.js and island js files

### ISSUE THREAD

**Issue by cknight** [denoland/deploy_feedback#340]
My app is a Fresh app (v1.1.3) running in Deploy.  It has excellent performance locally (achieving 100 in lighthouse) and in Deploy too (except on 1st hits).  After deployment, the request of the initial route request generally consistently loads quickly, but the download of tailwind.js, main.js and the islands js files are delayed significantly (3-7 seconds generally).  Locally, I see around 400ms to load these on my 8+ yr old Linux box.  Here's a webpagetest snapshot of the network traffic: 

![image](https://user-images.githubusercontent.com/1248238/219487169-9a26db6d-60ad-4e52-b1f4-db6b8005fb4c.png)

WebPageTest result: https://www.webpagetest.org/result/230216_AiDcRR_KFG/

Any ideas why I am experiencing this?

-----------------

This is also happening for other Fresh sites such as merch.deno.com:

![image](https://user-images.githubusercontent.com/1248238/219902722-6295b45a-167d-45ab-afa6-97c69ef6d67a.png)

So the question is, can this initial load/cache time be improved?  Why is it so slow on Deploy?

**Comment by Vehmloewff** [comment]
@cknight I am pretty sure that the delay you are seeing is the time it takes Fresh to transpile and bundle the islands. This appears to happen the first time that any asset is requested after the isolate starts up.

Looking through the source code, [here is where an asset is sourced](https://github.com/denoland/fresh/blob/1.1.4/src/server/context.ts#L627) once a request comes in for it. That `get` function [will bundle the islands](https://github.com/denoland/fresh/blob/1.1.4/src/server/bundle.ts#L134) if the cache is empty (which will be the case when the isolate starts up).

**Comment by cknight** [comment]
Thanks @Vehmloewff , that was the conclusion I came to as well.  I also found this:  https://github.com/denoland/fresh/issues/1062.  Happy to close this off in favour of that proposed solution.
