### ISSUE TITLE
Deployment failed because std@0.180.0/encoding/_yaml/loader/loader.ts not found

### ISSUE THREAD

**Issue by metadream** [denoland/deploy_feedback#346]
It was fine a few days ago, but I reported an error when deploying today. I didn’t change any code, and didn’t use yaml (maybe it was used by a certain dependency, but it worked before).

```
deployctl deploy --token=xxxxxxxxxxxxxxxxxxxxxxxx --project=docz ./start.ts
✔ Project: docz
ℹ Uploading all files from the current dir (/home/Codebase/docs)
✔ Found 34 assets.
✔ Uploaded 1 new asset.
✖ Deployment failed.
error: The deployment failed: HTTP status client error (404 Not Found) for url (https://deno.land/std@0.180.0/encoding/_yaml/loader/loader.ts)
```

**Comment by ayame113** [comment]
It looks like the same problem as https://github.com/denoland/deno_std/pull/3264 and https://github.com/denoland/deno_std/issues/3256.

As noted in the comments [here](https://github.com/denoland/deno_std/pull/3264#issuecomment-1473718031), until a new version of deno.land/x/markdown is published, it seems that import-map can be used to work around this issue.

**Comment by metadream** [comment]
Yes, thanks. From the source code, the markdown module does not specify the std version number. Since it has not been maintained for several years, I decided to replace it with https://deno.land/x/marked.
