### ISSUE TITLE
Will a period fail domain validation from Cloudflare?

### ISSUE THREAD

**Issue by motss** [denoland/deploy_feedback#347]
## Issue

I noticed that the `CNAME` contains a period at the end of the content value for `_acme-challenge.<subdomain>`, like so `<string>._acme.deno.dev.`. However, Cloudflare automatically trims the ending period once you save the value. Will the domain validation fail because of the final period in the `CNAME`?

**Comment by lucab** [comment]
Hi and thanks for reaching out. The trailing `.` at the end of the DNS domain is only meant as an indication that the domain is a fully-qualified one.
Some providers trim it or prevent users' input from having a trailing dot, as they already assume the input is a fully-qualified domain name (FQDN).
In those cases it should work equally fine to use the unqualified form, without the trailing dot.
If you end up with domain validation issues on some specific domain/provider, feel free to open a new ticket that we may help debugging.

**Comment by motss** [comment]
Thanks @lucab. Unfortunately, nothing works for me. I need help on setting up a custom domain. Let's continue at #356.
