### ISSUE TITLE
Discord login 502 Bad Gateway

### ISSUE THREAD

**Issue by mrtornado** [denoland/deploy_feedback#349]
I'm using a free account for now but I don't think that matters , so the discord login works, but after I logout and try to login again I get 

```
502 Bad Gateway
The deployment failed while serving the request.
code: UNCAUGHT_EXCEPTION
```
the error in logs is : 
```
Interrupted: operation canceled
    at async Object.pull (ext:deno_web/06_streams.js:751:27)
```

But still if I retry it works again, should I expect this kind of troubles in productions also ?

**Comment by ry** [comment]
We are experiencing odd reports like this from Western Europe - there may be a regional problem there. Are you in that region?

**Comment by mrtornado** [comment]
yes, indeed I am , I'm from Romania, I hope you guys fix them soon :) I still have a few weeks until I'm production ready :) but yea ... let me know here please if you guys managed to fix them.

**Comment by lucab** [comment]
@mrtornado thanks for letting us know, it looks like it was a transient glitch in one of our regions that got automatically fixed by next deployment. We'll keep an eye to see if the problem re-appears, but also feel free to open a new ticket if you observe this again.
