### ISSUE TITLE
New deployments nor working

### ISSUE THREAD

**Issue by fro-profesional** [denoland/deploy_feedback#350]
Hi there I have an api that was working just fine not sure what happen but new deployments are not working, on my local works, and the deployment from 5 days ago works, but any new deployment don't

I'm using the pusher library with esm.sh, just wonder if anything changed recently 👀

I mean the deployment works** but the endpoint don't not sure why we didn't change the code

- clau-platform-api-scjgw1efdwxg.deno.dev/pusher doesnt work
- clau-platform-api-renyce2zgbr0.deno.dev/pusher it works

Not code change 2-3 days apart, no new deployment is working since then
Code

```
import { Router } from "oak";
import { logger } from "../utils/logger.ts";
import { pusher } from "../modules/pusher.ts";
import { getFakeName } from "../tests/faker.ts";

const pusherRouter = new Router();

pusherRouter.all("/pusher", async (ctx) => {
  let pResponse = null;

  try {
    let name = await getFakeName();

    const date = new Date();
    const options: any = {
      year: "numeric",
      month: "2-digit",
      day: "2-digit",
      hour: "2-digit",
      minute: "2-digit",
      second: "2-digit",
      fractionalSecondDigits: 3,
    };
    const mexicanDate = date.toLocaleString("es-MX", options);

    pResponse = await pusher.trigger("chat-room", "new-message", {
      message: Hi from ${name} at ${mexicanDate},
    });

    pResponse = await pResponse.json();
    logger.info({ pResponse });
  } catch (error) {
    pResponse = error;
    logger.error({ pResponse });
  }

  ctx.response.body = {
    pResponse,
  };
});

export { pusherRouter };
```

**Comment by ry** [comment]
It might be that esm.sh is delivering a slightly different transpilation? That would account for why the previous versions still work. 

We are working towards support of npm modules in Deploy which will alleviate problems like this.

**Comment by fro-profesional** [comment]
> It might be that esm.sh is delivering a slightly different transpilation? That would account for why the previous versions still work.
> 
> We are working towards support of npm modules in Deploy which will alleviate problems like this.

@ry You are right, I didn't even consider that! I'll look into it, thanks!

**Comment by fro-profesional** [comment]
You were absolutely right, I changed my url:
from: https://esm.sh/pusher@5.1.2
to: https://esm.sh/pusher@5.1.2?bundle
And now works!

**Comment by fro-profesional** [comment]
Any ideas?

deno run -A test.js

//test.js

import Pusher from "pusher"
// const Pusher = require('pusher');

const pusher = new Pusher({

});


async function doSome() {
  const response = await pusher.trigger('chat-room', 'new-message', { message: 'Ey, it seems the implementation works! :)' });
  console.log({
    response
  })
}

doSome()

error: Uncaught TypeError: Ue is not a function
    at Object.Ie [as send] (https://esm.sh/v124/pusher@5.1.3/deno/pusher.mjs:2:5690)
    at i.post (https://esm.sh/v124/pusher@5.1.3/deno/pusher.mjs:3:6398)
    at Object.M.trigger (https://esm.sh/v124/pusher@5.1.3/deno/pusher.mjs:2:3699)
    at i.trigger (https://esm.sh/v124/pusher@5.1.3/deno/pusher.mjs:3:6166)
    at doSome (file:///Users/franciscoramos/Documents/clau/code/clau/test.js:15:33)
    at file:///Users/franciscoramos/Documents/clau/code/clau/test.js:21:1

**Comment by fro-profesional** [comment]
https://dash.deno.com/playground/paco-dev

**Comment by fro-profesional** [comment]
I think https://github.com/esm-dev/esm.sh/issues/649 will solve it
