### ISSUE TITLE
Missing Deno.core.setPromiseHooks?

### ISSUE THREAD

**Issue by Grunet** [denoland/deploy_feedback#351]
I was trying to get an OpenTelemetry example with async/await going based off of https://github.com/open-telemetry/opentelemetry-js/issues/2293#issuecomment-1373080258 but ran into Deno.core being undefined (let alone Deno.core.setPromiseHooks)

Would it be possible to add that specifically in?

**Comment by Grunet** [comment]
Oh wait I see is this already on the way?

https://github.com/denoland/deno_std/pull/3150

I'm not really sure how changes from Deno make their way to Deno Deploy exactly

**Comment by danopia** [comment]
Did you check `Deno[Deno.internal].core.setPromiseHooks`? I've been using that successfully on deno deploy via [my own opentelemetry tests](https://github.com/cloudydeno/deno-observability/blob/c44d90fd949f8180144d87e4fd0af1b78bf7793a/tracing/context-manager.ts#LL19C3-L19C43).

**Comment by ry** [comment]
You can also try AsyncLocalStorage. Here's an example https://dash.deno.com/playground/asynclocalstorage

```ts
import { serve } from "https://deno.land/std@0.175.0/http/server.ts";
import { AsyncLocalStorage } from "https://deno.land/std@0.175.0/node/async_hooks.ts";

const reqIdStore = new AsyncLocalStorage();

serve(async (req: Request) => {
    const reqId = crypto.randomUUID();
    const resp = await reqIdStore.run(reqId, () => handler(req, reqId));
    resp.headers.set("x-req-id", reqId);
    return resp;
});

async function handler(req: Request, expectedId: string): Promise<Response> {
    const resp = await fetch("https://example.com");
    await resp.body.cancel()
    const reqId = reqIdStore.getStore();
    return new Response(`expected: ${expectedId}\nactual: ${reqId}`);
}
```

Soon one will import AsyncLocalStorage by using `import { AsyncLocalStorage } from "node:async_hooks"`. But right now it's still unsupported.

**Comment by Grunet** [comment]
@danopia's trick seemed to work (!) and that AsyncLocalStorage support looks like just what is needed for async/await support!

I will close this issue and work on seeing if I can get the otel-js setup based on AsyncLocalStorage for Node.js working
