### ISSUE TITLE
serveTls - TypeError: Deno.readTextFileSync is not a function

### ISSUE THREAD

**Issue by sebringrose** [denoland/deploy_feedback#353]
### To reproduce:

```
import { serveTls } from "https://deno.land/std@0.181.0/http/server.ts";

const certFile = "./path/to/cert.crt";
const keyFile = "./path/to/key.key";

serveTls((_req) => new Response("Hello, world"), {
  certFile,
  keyFile,
  onListen: () => console.log("I'm aliiiiiiive!"),
});
```

### Suggested fix:

Refactor to use Deno.readTextFile (async)

**Comment by lucacasonato** [comment]
You don't need `serveTls` on Deno Deploy. TLS is automatically terminated by the platform.

**Comment by sebringrose** [comment]
But I would like to use a custom cert to serve IoT microcontrollers with TLS

**Comment by lucacasonato** [comment]
@sebringrose Is this resolved for you?

**Comment by sejori** [comment]
> @sebringrose Is this resolved for you?

I have uploaded a custom certificate and that seems to have worked fine. 

I need to fix my clients private key fingerprint to test properly but that is a separate issue so I think we can close this 👌
