### ISSUE TITLE
Fixed production URL?

### ISSUE THREAD

**Issue by MyWay** [denoland/deploy_feedback#354]
Hi, I noticed that even the production URL changes, when deploying.

I was wondering if there is a way to keep it fixed, e.g. myapp.production.deno.dev, so that we don't have to update callers each time?

Thanks

**Comment by magurotuna** [comment]
The fixed URL is provided for production deployment - suppose your project name is myapp, then the production URL is myapp.deno.dev. See https://deno.com/deploy/docs/projects#creating-a-project for more detail.

**Comment by MyWay** [comment]
Thanks.
