### ISSUE TITLE
Failed to receive BroadcastChannel message

### ISSUE THREAD

**Issue by xbol0** [denoland/deploy_feedback#355]
I've received this error many times.

I tried to catch the error, but it would still panic and restart my server.

```
TypeError: failed to receive BroadcastChannel message
    at async recv (ext:deno_broadcast_channel/01_broadcast_channel.js:31:21)
```

**Comment by ayame113** [comment]
I have been encountering this since April 1st as well.
From my error log, I'm guessing there's a fair amount of errors.

![image](https://user-images.githubusercontent.com/40050810/229511486-274cbfb5-7435-4d93-9adf-7a720f6ec02f.png)

**Comment by lucacasonato** [comment]
Thanks for the report, we'll get this fixed up very soon!

**Comment by lucacasonato** [comment]
This has been fixed.

**Comment by piscisaureus** [comment]
This should have been fixed now, if the issue pops up again please open another issue.

**Comment by ayame113** [comment]
Thank you for your quick response.
