### ISSUE TITLE
Unable to add custom domain

### ISSUE THREAD

**Issue by motss** [denoland/deploy_feedback#356]
## Issue

I have tried to add my domain to my own project but it does not seem to work even after waiting for days. Also tried removing then adding a new one but nothing works so far.

1. Added all required records in Cloudflare
   <img width="1693" alt="cloudflare DNS dashboard" src="https://user-images.githubusercontent.com/10607759/229493867-0ede5e6e-6509-445e-8b21-46d6bfed783c.png">
1. DNS records from Deno Deploy
   <img width="853" alt="failed to validate domain in Deno Deploy" src="https://user-images.githubusercontent.com/10607759/229494161-d9429c46-1e83-46c7-a861-1867dc13c39b.png">

**Comment by lucab** [comment]
@motss I think the `Proxied` status for your DNS is actually rewriting the entries in order to hide them behind Cloudflare infrastructure. Have you are tried already setting up plain (i.e. non proxied) records instead?

**Comment by crowlsyong** [comment]
I am experiencing the exact same issue using cloudflare + deno deploy. 

[joeyc.xyz](https://joeyc.xyz) and you'll see the error. 

I will attempt to turn off the proxied status in cloudflare on a different site and I'll report back.

**Comment by crowlsyong** [comment]
I did what @lucab said and turned off `Proxied` DNS in Cloudflare and it worked!

![image](https://user-images.githubusercontent.com/81304661/229513441-7942b051-e435-4fd0-98e2-7245728b77b6.png)

![image](https://user-images.githubusercontent.com/81304661/229514045-16fa772c-06af-4203-93b8-0dc9b7c5bacf.png)

**Comment by motss** [comment]
> @motss I think the `Proxied` status for your DNS is actually rewriting the entries in order to hide them behind Cloudflare infrastructure. Have you already tried setting up plain (i.e. non proxied) records instead?

I actually tried that yesterday but did not work. Tried that just now and it worked like a charm. Also, it would be great if this can be added to the documentation or the UI.

Thanks again, @lucab @crowlsyong .

**Comment by alexgleason** [comment]
Spent an hour or so frustrated by this. For me, the only thing that made a difference was disabling SSL:

![image](https://github.com/denoland/deploy_feedback/assets/3639540/7f07b9b5-fa19-4787-a111-21cf7da98852)

Then it worked.
