### ISSUE TITLE
What does "requests per day" actually mean?

### ISSUE THREAD

**Issue by ngdangtu-vn** [denoland/deploy_feedback#359]
I'm a bit confuse on request would mean in [here](https://deno.com/deploy/pricing).

- Does it a request for every single resource like html, css, js, json(rest api), etc.
- Or it is per page, HTML page (anything load from it will not be counted)

**Comment by lucacasonato** [comment]
Every HTTP request counts. Thus CSS and JS also.

**Comment by ngdangtu-vn** [comment]
What about websocket?
