### ISSUE TITLE
can't refresh anv var if we want !

### ISSUE THREAD

**Issue by elycheikhsmail** [denoland/deploy_feedback#36]

**Comment by satyarohith** [comment]
What does "refresh env var" mean?

If my guess is correct, you might be looking to update the environment variables of an existing deployment. Deployments by design are immutable. You cannot update the environment variables of an existing deployment. New environment variables are made available to deployments that are made after the edits.

**Comment by elycheikhsmail** [comment]
> What does "refresh env var" mean?
> 
> If my guess is correct, you might be looking to update the environment variables of an existing deployment. Deployments by design are immutable. You cannot update the environment variables of an existing deployment. New environment variables are made available to deployments that are made after the edits.

thank you.

**Comment by mpcref** [comment]
It would be useful if the "Environment Variables" page had a "re-deploy" button that would repeat the last deployment but with the updated env vars.

**Comment by bartlomieju** [comment]
As a reference - Heroku automatically creates a new deploy when env vars are getting updated.

**Comment by shina** [comment]
Came here to report the same "issue". 
A manual "re-deploy" would be better than automatic, imho. If an automatic workflow is needed, then it could be triggered through API. (which I don't think exists, but will exist at some point)

**Comment by elycheikhsmail** [comment]
> Came here to report the same "issue".
> A manual "re-deploy" would be better than automatic, imho. If an automatic workflow is needed, then it could be triggered through API. (which I don't think exists, but will exist at some point)

may be FAQ setion in deno deploy doc will be usefull for avoiding to report the same "same"

**Comment by satyarohith** [comment]
We now automatically create a new deployment when env vars are updated. Thanks for opening the issue.
