### ISSUE TITLE
[Bug]:  https://deno.land/std/async/mod.ts not found

### ISSUE THREAD

**Issue by fro-profesional** [denoland/deploy_feedback#362]
### Problem description

Getting this error: `gcp-us-west2module not found: https://deno.land/std/async/mod.ts`

<img width="1035" alt="Screenshot 2023-04-13 at 15 18 26" src="https://user-images.githubusercontent.com/97365498/231895600-900f9255-b420-465f-a70f-1168ce6bdfdc.png">

### Steps to reproduce

Deploy function

### Expected behavior

https://deno.land/std/async/mod.ts should work

**Comment by piscisaureus** [comment]
Thanks for the report! This should be fixed now.
