### ISSUE TITLE
Problem in deployment: Unexpected non-whitespace character after JSON at position 3

### ISSUE THREAD

**Issue by mrtornado** [denoland/deploy_feedback#365]
Hi guys, so I researched this for like the last 2 days ... and tried different stuff. I have no ideea why this is happening, the main ideea is that in development the code works without any problem. After I upload it to deno.dev I'm getting Unexpected non-whitespace character after JSON at position 3 . I'm using Fresh and Deno , here is the code that I think is the problem 

```javascript
    const response = await fetch(
      `${config.base_url}/api/members/securedApi/trial`,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          memberKey: user,
        }),
      }
    );
```

I think this is it because I get no console.logs from the api endpoint in production so clearly it doesn't reach the api endpoint.
Here are the files: 
JSX File: https://paste.ofcode.org/ms7sKfGdUg7DdMqbrLwaCW
API FILE https://paste.ofcode.org/tDN3V5k7Y8FASGSw6WNAKW

Again development is working great here are the server logs from development: 
```
Request body: {"memberKey":"9770"}
Parsed request body: { memberKey: "9770" }
Fetched member: { member_key: 9770, username: "toro", email_address: "xxx@xxx.com" }
Response data: InsertResult {}
Response status: 200
Response body: {}
```

and here are the logs from deno.dev:
```
gcp-europe-central2An error occurred during route handling or page rendering. SyntaxError: Unexpected non-whitespace character after JSON at position 3
    at parse (<anonymous>)
    at packageData (ext:deno_fetch/22_body.js:362:14)
    at consumeBody (ext:deno_fetch/22_body.js:239:12)
    at async POST (file:///src/routes/24-hours-free-proxy.tsx:39:30)
    at async https://deno.land/x/rutt@0.1.0/mod.ts:143:36
    at async Server.handler (https://deno.land/x/fresh@1.1.5/src/server/context.ts:220:25)
    at async Server.#respond (https://deno.land/std@0.178.0/http/server.ts:220:24)
2023-04-17 01:22:42
gcp-europe-central2Response status: 508
2023-04-17 01:22:42
gcp-europe-central2{"memberKey":"9770"}
2023-04-17 01:22:42
```

If anybody could help that would be great because at this point I have no more clue what to do ...

**Comment by magurotuna** [comment]
According to the log from deno.dev, the HTTP response code you got is 508, which means a loop was detected. Deno Deploy prevents recursive requests where your deployment (say, deployment ID is `A`) makes a request to the same deployment `A`.
So can you try and fix your code so that it won't make any recursive HTTP requests?

**Comment by magurotuna** [comment]
Probably related to https://github.com/denoland/deploy_feedback/issues/187

**Comment by mrtornado** [comment]
thanks for answering, yes I saw the 508 code also and tried to find the loop, but I can't rly find any loop in my code, but yet again I'm not that experianced, as reading through 187 I still can rly identify the problem, could you point me in the right direction, like what I have to do so I won't get the error anymore ?

**Comment by mrtornado** [comment]
so basically after reading again I can't make a fetch request from a server page, I would have to move the request to an island in Fresh, so it would be on the frontend , right ?

**Comment by mrtornado** [comment]
I managed to make it work by importing the heandler and creating a fake request. Here is the code for who's interested: 

in my JSX file: 
First import the handler as trialRequest because I had another handler in the file: 

`import { handler as trialRequest } from "@/routes/api/members/securedApi/trial.ts";`

JSX File: https://paste.ofcode.org/ms7sKfGdUg7DdMqbrLwaCW

The I replaced the fetch request with: 

```javascript
    //TODO: when you get 508 error, check this
    const fakeRequest = {
      json: () => {
        return {
          // The request body you need to pass to the handler
          memberKey: user,
        };
      },
    };

    // Call the handler directly
    const response = await trialRequest.POST(fakeRequest);
```

**Comment by magurotuna** [comment]
> I would have to move the request to an island in Fresh, so it would be on the frontend , right ?

Yes that can be one solution you could take. If a request to your deployment `A` is made from frontend (instead of server side, i.e. Deno Deploy server) then it's not considered a loop.

Another possible solution would be to achieve what you want to do without making a HTTP request to the deployment itself. More specifically, you're making a request to `${config.base_url}/api/members/securedApi/trial` now and the endpoint will perform some operation when invoked. But instead, you could consider invoking the operation without making a HTTP request, for example just by calling a function.

**Comment by mrtornado** [comment]
yes that's what I did in the end. Thanks for explaining it to me.

**Comment by magurotuna** [comment]
Oh I didn't notice that you added extra comment while I was writing. Glad you did it!
I'm gonna close it as I think it's solved.
