### ISSUE TITLE
[Bug]: Latest Deployments on project Overview has a stale list

### ISSUE THREAD

**Issue by audionerd** [denoland/deploy_feedback#369]
### Problem description

The ”Latest Deployments” list on the project Overview (https://dash.deno.com/projects/:name/deployments) is missing the most recent deployment (in my case, a preview deployment).

All deployments are listed correctly on the Deployments page (https://dash.deno.com/projects/:name/deployments)

When looking only at the Overview page, this issue makes deployment seem slower than it actually is.

For context: I have both production and preview deployments.

### Steps to reproduce

1. Setup a Deno Deploy project with automatic Git integration
2. git push to a non-production branch
3. the deployment will appear on https://dash.deno.com/projects/:name/deployments but not https://dash.deno.com/projects/:name
4. git push another commit
5. the prior deployment will now appear in both places, but the most recent will only appear on /projects/:name/deployments

### Expected behavior

The most recent deployments should be listed correctly in both places shortly after the deployment succeeds

**Comment by magurotuna** [comment]
Thanks so much for the detailed description. We'll look into it.

**Comment by magurotuna** [comment]
We'll land the fix soon. Once it's fixed I'll close the issue then.

**Comment by satyarohith** [comment]
The fix was rolled out a few weeks ago thanks to Yusuke.

I'm closing the issue as resolved.
