### ISSUE TITLE
Fetching to ipify.org returns the Deno Deploy IP addresses. 

### ISSUE THREAD

**Issue by mrtornado** [denoland/deploy_feedback#373]
I'm using Fresh and Deno. 
I'm trying to get client IPV4 ip address to insert it into a database so they can't get more then 1 trial requests. The fetch works well on localhost and returns the right IP address but when I do it from Deno Deploy it returns the Deno Deploy IP addresses: 

This is what I get when I try it with my normal IP address:
`gcp-europe-central2 - 34.118.84.185`

and this is what I get when I try it with a UK proxy: 
`gcp-europe-west2 - 35.242.182.41`

If there any way I can make this fetch request return the user IP address ? BTW this is run from the SSR side, not from a island. 
I'm not using `ctx.remoteAddr` because if I use IPV6 it returns the IPV6 ip address and I want only the IPV4 ip address. 

Below is the function.  

```javascript
async function saveIpAddress(memberKey: any) {
  try {
    const ipAddr = await fetch("https://api.ipify.org?format=json");
    const ip = await ipAddr.json();
    console.log(ip.ip);

    // Check if the IP address and member_key combination already exists in the database
    const existingRecord = await db
      .selectFrom("fingerprints_ip")
      .selectAll()
      .where("ip", "=", ip.ip)
      .where("member_key", "=", memberKey)
      .executeTakeFirst();

    // If the combination does not exist, insert the IP address and member_key into the database
    if (!existingRecord) {
      await db
        .insertInto("fingerprints_ip")
        .values({ ip: ip.ip, member_key: memberKey })
        .execute();
    }
  } catch (error) {
    console.error("Error fetching and saving public IPv4:", error);
  }
}
```

**Comment by danopia** [comment]
I understand that `ctx.remoteAddr` is in fact the correct way to get the user's IP address.

> I'm not using ctx.remoteAddr because if I use IPV6 it returns the IPV6 ip address and I want only the IPV4 ip address.

Unfortunately, this is not possible from the server side - if the user's request was sent over IPv6, you cannot know their IPv4 address from the server (if they even have an IPv4 address at all).

It's probably most forward-thinking to go ahead and tackle how you can implement your rate-limiting with IPv6 addresses. A simple method would be trimming every address to the first /64 bits before checking your rate limits, but advanced solutions might also consider larger blocks like /56 for example. Here's a random post I found with some more words about IPv6 + rate limiting: https://adam-p.ca/blog/2022/02/ipv6-rate-limiting/

**Comment by mrtornado** [comment]
thanks for answering @danopia yea maybe we should have a way in Deno Deploy to turn off IPV6 , anyway still this doesn't answer my other question, why ipify.org can only see Deno Deploy IP addresses instead of the end user ip address ? 

or is there any way to make Fresh to accept only ipv4 addresses ?

**Comment by danopia** [comment]
> why ipify.org can only see Deno Deploy IP addresses instead of the end user ip address ?

It's because you are connecting to ipify.org from Deno Deploy instead of from the end user's browser. BTW, ipify.org is really just returning its own `ctx.remoteAddr` value in the response body.

So ipify is doing its job in telling you the IP address of where you ran the code from:

```mermaid
sequenceDiagram
    Browser->>+DenoDeploy: I'd like do to the thing
    DenoDeploy->>+ipify: What is my IP address?
    ipify-->>-DenoDeploy: Here is your IP address, Deno Deploy
    DenoDeploy-->>-Browser: Some response
```

I believe you are comparing to sending a request from the browser?:

```mermaid
sequenceDiagram
    Browser->>+ipify: What is my IP address?
    ipify-->>-Browser: Here is your IP address, end user
```

As the diagrams show, requests sent from Deno Deploy do not get sent from the Browser.

> Deno Deploy to turn off IPV6

I'm only a user here but I would not expect to see this offered for `.deno.dev` names. IPv6 is modern, just like Deno, and it would be best to go forward with it, or come up with a different solution for free trials, such as email validation

**Comment by mrtornado** [comment]
Hi thanks for taking the time to explain it to me , so basically I would need to run the detection from an Island if i want to be the end user IP address. Anyway I think in the end I'll just use the ctx.remoteAddr and store the ip even if it's ipv6 . Thanks again @danopia .

**Comment by satyarohith** [comment]
Thanks for taking the time to help the community @danopia!
