### ISSUE TITLE
[KV Feedback]: Visits counter example does not match actual

### ISSUE THREAD

**Issue by sylc** [denoland/deploy_feedback#375]
### 🔍

- [X] Did you search for existing issues?

### Type of feedback

Documentation improvement

### Description

example provided at https://deno.com/kv does not _fully_ work. 

example provided
<img width="455" alt="image" src="https://user-images.githubusercontent.com/10268458/235459987-28fcf6be-b9ec-48c6-abd7-4b2ad9fdca15.png">
Expect results: `Visits: 1`

Actual:
<img width="647" alt="image" src="https://user-images.githubusercontent.com/10268458/235460114-2e5bd955-bb6f-492a-8409-5787e00eef5f.png">

### Expected behavior (if applicable)

Example match actual

### Possible solution (if applicable)

update example with:
```diff
- return new Response(`Visits: ${res.value}`)
+ return new Response(`Visits: ${res.value.value}`)
```

**Comment by ry** [comment]
Oops, we're waiting for https://github.com/denoland/deno/pull/18656 to land which will make `res.value` work.

**Comment by sylc** [comment]
This has been fixed
