### ISSUE TITLE
[KV Feedback]: Deno SaaSKit server error "Transaction domain not found"

### ISSUE THREAD

**Issue by iuioiua** [denoland/deploy_feedback#376]
### 🔍

- [X] Did you search for existing issues?

### Type of feedback

Bug report

### Description

The following server error is being thrown on https://saaskit.deno.dev/:
```
An error occurred during route handling or page rendering. Error: txnproxy call failed with client error, status: 404 Not Found, message: {
  "code": "transactionDomainNotFound",
  "message": "Transaction domain not found"
}
    at eventLoopTick (ext:core/01_core.js:165:11)
    at async KvListIterator.<anonymous> (ext:deno_kv/01_db.ts:107:31)
    at async KvListIterator.next (ext:deno_kv/01_db.ts:379:27)
    at async getAllItems (file:///src/utils/db.ts:42:22)
    at async GET (file:///src/routes/index.tsx:10:23)
    at async https://deno.land/x/rutt@0.1.0/mod.ts:143:36
    at async handler (file:///src/routes/_middleware.ts:26:22)
    at async Server.handler (https://deno.land/x/fresh@1.1.5/src/server/context.ts:220:25)
    at async Server.#respond (https://deno.land/std@0.178.0/http/server.ts:220:24)
```
This is only happening for the production deployment. Other deployments are fine. I have not yet seen this issue on my local machine.

### Steps to reproduce (if applicable)

Deploy to Deno Deploy via GitHub PR merge (automatic Git integration). This is the 3rd time this same issue has occurred. Previously, I could remove the error by merging another PR.

I'm unable to identify a pattern when this issue has arisen.

**Comment by losfair** [comment]
Hi @iuioiua ,

Did you redeploy commit https://github.com/denoland/saaskit/commit/db6a1ea0260b7bef8459d581354fc2118ef084e8 twice, for example by modifying an env var?

There is a known bug that prevents KV from working if a deployment is created by a re-deploy of the same commit.

**Comment by iuioiua** [comment]
Yes, actually, I did. If this is a known bug, do you guys require any further data? If so, I'll keep the site in its state till resolution. If not, I'll push a change.

**Comment by losfair** [comment]
@iuioiua Thanks for confirming! We have the details on this issue and are working on a fix. You can push any changes you want :)

**Comment by iuioiua** [comment]
Changes were pushed, and the site is back online. Please feel free to close this now or once the bug is fixed (mainly so other users can see this issue) 😄

**Comment by losfair** [comment]
This issue has been fixed. Environment variable changes no longer break KV access now.

**Comment by shaunie2fly** [comment]
Thank you @losfair
