### ISSUE TITLE
[Bug]: 416 error when generating LinkedIn post preview for static app

### ISSUE THREAD

**Issue by hylozoid** [denoland/deploy_feedback#377]
### Problem description

We have a web app hosted on Deno Deploy that has a small API but serves static content to the browser via the std/http/file_server.ts library. The app is accessible via https://stillme.app and we are trying to ensure that open graph post previews work, and they do in all places except LinkedIn.

We used their [Post Inspector](https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fstillme.app) tool and saw that their crawler receives a 416 error when trying to access our app. Almost no other details are provided. (Sometimes it fails with a server error instead, but we see the 416 more often.)

Our experience is identical to an Azure Static Web App issue reported here, which seemed to be resolved by the Azure team on their side: https://github.com/Azure/static-web-apps/issues/57

We are trying to reproduce using a sharable example, but figured we'd post the question while we do that. We are unable to reproduce with any apps that do not use the file_server, e.g. merch.deno.com, the Fresh demo app, etc.

### Steps to reproduce

1. Open the [Post Inspector](https://www.linkedin.com/post-inspector/inspect/https:%2F%2Fstillme.app) tool.
2. Try to generate a preview for https://stillme.app

### Expected behavior

We expect a preview to be generated with a 200 OK status.

### Environment

Code snippet of the main.ts entrypoint:

```
import { serve } from "https://deno.land/std@0.185.0/http/server.ts";
import { serveDir } from "https://deno.land/std@0.185.0/http/file_server.ts";

async function handler(req: Request): Promise<Response> {
  // Check if the route is "api" and handle
  ...

  // Serve the static web app if no route matches.
  return serveDir(req, {
    fsRoot: "app",
  });
}

serve(handler, { port: 8080 });
```

**Comment by ayame113** [comment]
linkedin Post Inspector sends `range: bytes=0-3145727` headers. Currently, std's file server considers `3145727` to be a bad range request and rejects it with status `416`.

Other servers seem to respond with a `206 Partial Content` if they receive such a request. I think we need to change your std's fileserver implementation to not give an error here. (II am fixing in https://github.com/denoland/deno_std/issues/3353)

**Comment by hylozoid** [comment]
@ayame113 Thank you so much for digging into this! Out of curiosity, how did you determine the headers sent by the Post Inspector?

**Comment by ayame113** [comment]
I deployed a server like below in deno deploy and generated a preview in Post Inspector. After that I saw the header in the log.

```ts
import { serve } from "https://deno.land/std@0.185.0/http/server.ts";

serve((req: Request) => {
  console.log([...req.headers]);
  new Response("Hello World");
});
```

**Comment by ayame113** [comment]
A new version of std has been published (https://github.com/denoland/deno_std/releases/tag/0.186.0). Hopefully the problem should have been fixed.

**Comment by hylozoid** [comment]
After upgrading our dependencies to 0.186.0, the problem is resolved! Thank you so much for your help in identifying the issue and supplying the fix!

Post Inspector for confirmation of fix: https://www.linkedin.com/post-inspector/inspect/stillme.app
