### ISSUE TITLE
[Bug]: Deno.listenTls is not a function

### ISSUE THREAD

**Issue by vijaysundaram** [denoland/deploy_feedback#379]
### Problem description

I am attempting to deploy an Oak-based WebSocket server using sample code in the Deno docs, but updating it to use TLS/HTTPS. Specifically, I updated the following call to include the TLS parameters:

`await app.listen({ port: port, cert: cert, key: key });`

This works correctly in my local dev environment but throws the following error when I deploy:

```
TypeError: Deno.listenTls is not a function
    at HttpServer.listen (https://deno.land/x/oak@v12.4.0/http_server_native.ts:45:74)
    at Application.listen (https://deno.land/x/oak@v12.4.0/application.ts:340:39)
    at file:///src/server.js:296:5
```

I then tried to run an even more simplified HTTPS server using the `Deno.listenTls` API directly, and had the same results: worked locally but threw `Deno.listenTls is not a function` error when deployed.

### Steps to reproduce

1. Write any code snippet that directly calls Deno.listenTls
2. Run locally successfully
3. Deploy and see error logs

### Expected behavior

Deno deployment behavior should match local development behavior, with the Deno.listenTls API working. Or if there is a different issue at hand, better error messaging and/or documentation. 

### Environment

- Deno 1.33.1 (release, aarch64-apple-darwin)
- macOS 12.4

**Comment by satyarohith** [comment]
Deno Deploy handles TLS termination for your code, so we don't support the `Deno.listenTls` function. We can make the error message friendly.

If you want to use custom certificates, you can upload them on the Deno Deploy dashboard ([docs](https://deno.com/deploy/docs/custom-domains#step-4-provision-a-certificate-for-your-custom-domain)).

**Comment by vijaysundaram** [comment]
What's the right way to configure the WebSocket client and server given automatic TLS termination? If, for the server, I can just use `await app.listen({ port: 8080 });` and set up custom certificates via Deno, should the clients use: `wss://mycustomdomain.com:8080` or `ws://mycustomdomain.com:8080` or something different? I thought I tried every permutation of non-TLS, TLS, automatic certs, and custom certs without any success getting around this error but perhaps I missed the right combination?

**Comment by satyarohith** [comment]
Deno Deploy ignores the port number passed to `await app.listen({ port: 8080 })` and always listens on 443.

In development mode, the client should use `ws://localhost:8080`. When the script is deployed on Deno Deploy, the client should use `wss://mycustomdomain.com`.

Since you're working on WebSocket server, I'm posting some related content here:
- Deno Deploy Playground: https://dash.deno.com/playground/websocket
- Web Streams blog post: https://deno.com/blog/deploy-streams#websockets

**Comment by vijaysundaram** [comment]
Ah super-helpful, your instructions worked like a charm. Thanks so much for the prompt help and the pointers! I had caught some of it in my research but this combination of default behaviors/conventions for TLS in development vs. deployment and ambiguity form the error messaging made it challenging to pin down if the issue was in code vs. certs vs. ops, etc.

Thanks again!
