### ISSUE TITLE
[Bug]: Changing Github username does not change Deno organisation name and url.

### ISSUE THREAD

**Issue by beingminimal** [denoland/deploy_feedback#380]
### Problem description

We have updated our Github username but Deno organisation bind older url of organisation. It seems there is no way to change it.

### Steps to reproduce

Sign up with deno and connect Github Org
Change username of Github org
Sign in again with deno and go to organisation.
It still connect to older url of Github org.

### Expected behavior

Deno organisations should show new name of Github organisation.

**Comment by satyarohith** [comment]
Hi, @beingminimal. We fixed it [a few days ago](https://github.com/denoland/deploy_feedback/issues/156#issuecomment-1550661159). Can you try to sign out and sign in again?

Closing this issue as fixed, but feel free to comment if you're still facing it, and we will re-open and fix it.
