### ISSUE TITLE
[KV FEEDBACK]: is there Bulk update to Deno Deploy KV

### ISSUE THREAD

**Issue by OldManFroggy** [denoland/deploy_feedback#385]
### What problem are you trying to solve?

I have a need where, I need to pre-populate a rather large KV on Deno Deploy.

Normally, I would do this via a client app and stream (sets) to a remote location.  

However, if I connect to a deno KV on a remote (not deno deploy) machine it will always write to local storage.

is there a way to do this currently, or did I miss it in the current documentation?

### Describe the solution you'd like

be able to have a connection setting/configuration when connecting to Deno KV to tell it to connect to an existing Deno Deploy KV on my account (I suspect by account project)

currently can pass a file location for local file store, so something similar could work -> maybe the Deno deploy internal URL of an APP or API, and in the connection, code detect if a file path or valid URL has been passed. (or if an api key/keypair passed)
 
The current config seems to check for file location, or a set of JSON options like maxAge, encryption, etc..., so that seems a good place to add keys and project names...)

this way the developer experience is clean and almost no documentation changed or new API signatures to worry about

the above also allows multiple projects to share a KV in some instances. (Which is also a use case I have)

### Describe alternatives you've considered

right now, there are none since there seems to be no way to connect to an exsiting Deno Deploy store, without deploying to the project it belongs to.

### Documentation, Adoption, Migration Strategy

existing local file location format of kv.open

```
const kv = await Deno.openKv("my-kv.db")
```

version that supports a url
```
const kv = await Deno.openKv("https://sub.domain.com")
```

version that supports account api key/tokens
```
const kv = await Deno.openKv("e15b7480-c51b-47ef-bab9-6627bb4cc41a")
````

**Comment by losfair** [comment]
Hello,

Deno can now [connect to managed databases](https://docs.deno.com/deploy/kv/manual/on_deploy#connect-to-managed-databases-from-outside-of-deno-deploy) on Deno Deploy or elsewhere.
