### ISSUE TITLE
Add project description and allow searching

### ISSUE THREAD

**Issue by omar2205** [denoland/deploy_feedback#388]
### What problem are you trying to solve?

I have to guess what a project is (using the randomly generated name).

### Describe the solution you'd like

Adding a description and the ability to search.

### Describe alternatives you've considered

N/A

**Comment by satyarohith** [comment]
Thanks for the feedback! We will consider supporting project description. Btw, you can search for projects by name using the search bar provided on the [projects page](https://dash.deno.com/projects)
![CleanShot 2023-05-20 at 11 59 10@2x](https://github.com/denoland/deploy_feedback/assets/29819102/3b8090b8-4c04-4d8c-8734-cb368fde82b2)

**Comment by omar2205** [comment]
The problem is I don't often change the project name (I like random ones). So descriptions would be really cool.

**Comment by vwkd** [comment]
Maybe it could show a link to the connected GitHub repo.

The GitHub repo can serve as documentation which IMO is a much better place than Deploy.
