### ISSUE TITLE
Node style import in deno workers.

### ISSUE THREAD

**Issue by Kartik4152** [denoland/deploy_feedback#389]
I am using deno on supabase for edge functions.

I require the crypto library for some functionality, particularly (createCipheriv, createDecipheriv).
Before 0.178.0 I could import directly from the `std/node` directory, but since that was merged there is no way to import on deno workers.
The `node:` syntax is not supported on edge workers as it is not a valid url.
Is there any way to make node style imports work on workers?

**Comment by ry** [comment]
It’s coming to Deno Deploy very soon now.

**Comment by satyarohith** [comment]
Yes, `node:` will come soon along with `npm:`. Closing this as a duplicate of https://github.com/denoland/deploy_feedback/issues/314
