### ISSUE TITLE
[Bug]: Unable to deploy application

### ISSUE THREAD

**Issue by metadream** [denoland/deploy_feedback#393]
### Problem description

Regardless of whether it is through the deployctl tool or associated with the github repository, an error is reported (I am not using version 0.188.0): 
```
error: The deployment failed: HTTP status client error (404 Not Found) for url (https://deno.land/std@0.188.0/encoding/_yaml/loader/loader.ts)
```
Had a similar problem before and it took a long time to retry to succeed.

### Steps to reproduce

1. deployctl upgrade
2. deployctl deploy --token=xxx --project=xxx mod.ts
3. error:
```
✔ Project: xxx
ℹ Uploading all files from the current dir (/home/xehu/Codebase/xxx)
✔ Found 25 assets.
✔ Uploaded 25 new assets.
✖ Deployment failed.
error: The deployment failed: HTTP status client error (404 Not Found) for url (https://deno.land/std@0.188.0/encoding/_yaml/loader/loader.ts)
```

### Expected behavior

successful deployment

**Comment by magurotuna** [comment]
Looks like that's because the breaking change in deno_std. You may find https://github.com/denoland/deno_std/issues/3256 helpful - could you take a look and try again?

**Comment by metadream** [comment]
Thanks and sorry, I forgot to submit the same issue, which was caused by the x/markdown module not specifying the std version. Just use the x/marked module instead.
