### ISSUE TITLE
Not implemented `URL.createObjectURL`

### ISSUE THREAD

**Issue by AkiaCode** [denoland/deploy_feedback#4]
I want to show the picture through `URL.createObjectURL` in fetch API -> Blob, but it is not implemented.

**Comment by bnoordhuis** [comment]
It's not implemented in Deno itself either, see the feature request in https://github.com/denoland/deno/issues/9210. No ETA.

Maybe you can create a polyfill off of https://github.com/denoland/deno/blob/ccee2f01ba2f6304720ab17e99dee17bf6687bd8/js/url.ts#L295-L315?
