### ISSUE TITLE
[Bug]: Error while creating Fresh project in the playground

### ISSUE THREAD

**Issue by zbynekwinkler** [denoland/deploy_feedback#402]
### Problem description

I get an error when trying to create Fresh project in the playground.

### Steps to reproduce

1. Click `+New Project`
2. In `Full-stack web app using Fresh` click `Fork`

Instead of the new project, I get the following error:

> Cannot read properties of undefined (reading 'login')

### Expected behavior

Create the project, no error.

**Comment by zbynekwinkler** [comment]
Today it gets further. Today I get to see the url https://dash.deno.com/new_from_template?template=fresh_app&org=f04b44d4-e58e-4ba2-aa12-10233aea50db but inside is endless spinner with the text "Checking GitHub App installation". In dev tools I can see the url https://dash.deno.com/_api/github/installations has returned 500. The body says

```json
{
    "name": "ApiError",
    "status": 500,
    "code": "internalServerError",
    "traceId": "6ad79a91876627fd090d198a0a7599e4",
    "message": "An internal server error occurred."
}
```

**Comment by lucab** [comment]
Thanks for the report. From our side we see that our backend calls to GitHub API are failing with `Bad credentials`.
Could you maybe check https://github.com/settings/installations and see how the `Deno Deploy` app is configured there? Is it installed and if so, which kind of permissions and repository access it has?

**Comment by zbynekwinkler** [comment]
I don't see why creating something on https://dash.deno.com/ would need any permissions on github. The Deno app is not installed on any account I have access to.

Hmm, I see. You have update the wording and workflow - now it says it wants to "Fork" something.

> We'll create a new GitHub repository from this template.

So now using the Fresh template I get another page where it tells me it is going to create a fork of a repository and allows me to install Deno github app on my account.

However using "Jsx example" also has a fork button but it actually does not fork anything on gihub and it works without Deno app installed. That is why I was confused. Two cases create something on github first and then link it to deno, while the other two create something on deno and then link it to github.

Installing the Deno app on my account I am told it needs these permissions:

> Read and write access to administration, code, commit statuses, and deployments

Why does it need admin access to everything? That does seem excessive. For example Cloudflare Pages has these permissions:

> Read access to code and metadata
> Read and write access to checks, deployments, and pull requests

That seems expected and reasonable.

**Comment by lucab** [comment]
Thanks for the additional feedback.

As you correctly mentioned, some of the templates involve forking a repository into your GitHub account. That requires installing the app and giving it enough permissions to manage repos and webhooks.

We have taken an internal note that having different actions under the same "Fork" verb is somehow confusing, we'll see how to improve the webUI in that regard.

It seems you were eventually able to create projects from templates, both Fresh and JSX ones.
Unless you have encountered further blockers that we should be aware of, I'm now closing this ticket.
