### ISSUE TITLE
Run with --lock flag

### ISSUE THREAD

**Issue by benadamstyles** [denoland/deploy_feedback#405]
### What problem are you trying to solve?

Do deploy projects run with the `--lock` flag? If not, could they?

### Describe the solution you'd like

Allow using the `--lock` flag to ensure subresource integrity.

### Describe alternatives you've considered

I don't know of any alternatives, as I don't think we have control over the runtime flags.

**Comment by lucab** [comment]
Thanks for the report.

Each project deployment is built upfront, when the user pushes a new deployment to Deno Deploy infra. All subsequent runs re-use the same artifacts, and there are different layers performing hashing and looking them up along the way.

You are correct that Deno Deploy does not directly offer the same level of user control as the Deno CLI, in particular regarding custom runtime flags or lockfile.
However, the integrity of resources in your deployment should be already guaranteed by the above mechanism, which is conceptually similar to Deno CLI generating a lockfile on first run.
