### ISSUE TITLE
[Bug]: Deno.stat() returns wrong time field values

### ISSUE THREAD

**Issue by cpetrov** [denoland/deploy_feedback#409]
### Problem description

Time fields returned by `Deno.stat()` for a file are all: `"1970-01-01T00:00:00.000Z"`:

```
"mtime":"1970-01-01T00:00:00.000Z",
"atime":"1970-01-01T00:00:00.000Z",
"birthtime":"1970-01-01T00:00:00.000Z"
```

This has undesired consequences. E.g., as `std/http/file_server.ts` uses `mtime` to calculate weak ETags (https://github.com/denoland/deno_std/blob/8bd34c3/http/file_server.ts#L176), this results in constant ETags across deployments that break caching.

### Steps to reproduce

1. Create a file.
2. Run `console.log(await Deno.stat(filepath))` in script.
3. Deploy.
4. Observe deployment logs.

### Expected behavior

In case time fields are not supported, `Deno.stat()` should return `null` rather than `"1970-01-01T00:00:00.000Z"`.

### Environment

- `std@0.192.0`

### Additional context

Related: 

- https://github.com/denoland/deploy_feedback/issues/334
- https://github.com/denoland/deploy_feedback/issues/191

**Comment by lucab** [comment]
Thanks for the report! It looks like there may be something going wrong internally in one of the Deno libraries, I've opened https://github.com/denoland/deno/pull/19586 for this.

**Comment by lucab** [comment]
The fix for this has been merged in Deno and also landed in Deno Deploy:
```
{
  isFile: true,
  size: 203,
  mtime: null,
  atime: null,
  birthtime: null,
  ...
}
```
