### ISSUE TITLE
[Bug]: Logs are not show in chronological order

### ISSUE THREAD

**Issue by cknight** [denoland/deploy_feedback#410]
### Problem description

When viewing live logs on Deploy, the logs from different regions are shown out of order, or possibly the timestamp of the region is shown?  Either way it's confusing looking at logs which show timestamps which jump forward and backward in time.

![image](https://github.com/denoland/deploy_feedback/assets/1248238/a63e8743-ccfd-4dc0-81f1-671b34c61501)

### Steps to reproduce

1. Access a Deploy application with logs written from multiple global regions.
2. Examine Deploy logs timestamps

### Expected behavior

Log timestamps would all be in the same timezone (local or GMT) and in chronological descending order.

### Environment

N/A (using Deploy)

**Comment by magurotuna** [comment]
Thanks for reporting! I'll look into it.

**Comment by magurotuna** [comment]
The fix for this issue had landed.
