### ISSUE TITLE
[Bug]: KV - Transaction domain not found

### ISSUE THREAD

**Issue by cknight** [denoland/deploy_feedback#413]
### Problem description

Immediately after deploying a new commit to Deploy and accessing my site, I got the following error in Deploy:

![image](https://github.com/denoland/deploy_feedback/assets/1248238/9a78d250-ace7-4371-b8db-dd2e8b4f388c)

A refresh of the page successfully loaded the site and I have not had the issue since, however, this suggests there is a small window during deployments where KV can fail.  Perhaps this is a developer/client side concern (in which case it should be documented) but it would be better if this could be handled transparently by Deploy.

### Steps to reproduce

1. Release new commit to Deploy
2. Immediately visit page which initiates a KV.list operation

Note that I have not attempted to reproduce this.

### Expected behavior

Deploy seamlessly handles KV operations throughout the deployment process, queuing operations as required to let propagation complete.

### Environment

Deploy

**Comment by lucacasonato** [comment]
Are you using strong or eventual consistency for your query?

**Comment by cknight** [comment]
eventual, https://github.com/cknight/kvSpeedCheck/blob/main/routes/index.tsx#L38

**Comment by ry** [comment]
this has been fixed
