### ISSUE TITLE
[Bug]: New deployment was not triggered by git push with mono-repo

### ISSUE THREAD

**Issue by AnxinYang** [denoland/deploy_feedback#417]
### Problem description

Hi Deno team,

My project currently have three deno folders for different endpoints, and they are all inside one mono-repo.
Started from today, 06/28/2023, I noticed that after I pushed my change, only one or two out of three deployments were updated.

### Steps to reproduce

1. push changes to github.
2. check deployment page.

### Expected behavior

Expect all deployments picks up new updates and re-deploy.

### Additional context

![image](https://github.com/denoland/deploy_feedback/assets/32281036/e792c7d5-d0e2-4138-8a03-d7d2528b84af)

**Comment by igorzi** [comment]
Hi @AnxinYang - does this happen every time (on every commit)? Or sporadically?

**Comment by AnxinYang** [comment]
@igorzi it's everytime now. Just did a update.
![image](https://github.com/denoland/deploy_feedback/assets/32281036/25fe112c-8434-49a8-a5c8-4156a1678e4c)

**Comment by AnxinYang** [comment]
I'm trying to re-link all projects. after I removed all link.
when I tried to link my project. I got this error:
![image](https://github.com/denoland/deploy_feedback/assets/32281036/d3799c54-77fa-4441-8618-e3f5fa6eb00c)

Project did got re-deploy after re-link, but not sure why this error.

#### Update
 I did a minor push again. Only one of the deployment picked up the commit.
![image](https://github.com/denoland/deploy_feedback/assets/32281036/0256e870-2f44-4b37-be9e-97ec781d7f30)

**Comment by igorzi** [comment]
This is due to Github outage: https://www.githubstatus.com/

**Comment by lucab** [comment]
The underlying GitHub outage was https://www.githubstatus.com/incidents/ws2l6203cs7g.
It has been marked as resolved at 06:43 UTC, things seem to be back to normal on our side.
I'm closing this ticket now, but let us know if you are still encountering issues.

**Comment by AnxinYang** [comment]
Verified, it works now. Thanks for looked into this.
