### ISSUE TITLE
[Bug]: Failed tests prevent deploy

### ISSUE THREAD

**Issue by jorjun** [denoland/deploy_feedback#419]
### Problem description

Couldn't see from deploy control panel that the reason an automatic deploy had failed to show up was due to a failing test. 

Now that I know tests are run as part of the deployment I will improve my process. This is not really a bug but a feedback notice. In my opinion there ought to be a deploy-fail status and reason.

### Steps to reproduce

Push changes that contain failing tests.

### Expected behavior

Control panel shows that deployment has failed due to failed test: preferably further particulars.

**Comment by lucab** [comment]
Thanks for the report.
Could you maybe add some more details about the actual failure you have observed? On which kind of project was this happening? Do you have some some log messages or a screenshot you can share?

In general I think this depends on how the source code for the project is structured. Perhaps you had some test functions directly reachable from the entrypoint? Is this some public code we can have a look at, or can you maybe share the relevant bits for a minimal reproducer?

**Comment by jorjun** [comment]
Hi there, the overview of my issue is that I have gotten used to automatic deployment, and then that suddenly stopped. No log, no explanation.

On further examination I believe that it was due to a failing test. This should be easy to verify - commit a project with a failing test. I think this behaviour is good: failing to deploy a project with a failing test. But there also ought to be some sort of customer feedback on that in the control panel. OK, the tests failed. Let's see a notice.

**Comment by arnauorriols** [comment]
Hi @jorjun. We have added failed deployments to the deployments list, together with the error message, and the ability to see the build logs of all deployments. All this will be available going forward for new deployments (no retrofitting). I believe this covers the feedback you provided. I'm closing the issue, but feel free to reopen if you want to elaborate further.
