### ISSUE TITLE
oak 7.5.0 don't work with deno deploy

### ISSUE THREAD

**Issue by elycheikhsmail** [denoland/deploy_feedback#42]
why deno deploy run ts code with checking ? it will bundle our code to js then run it, why not use  --not-check option by default ?

**Comment by ngdangtu-vn** [comment]
To make sure your code won't fail in runtime? If the problem is about type checking then it is oak fault, I assume. I quit fancy deno frameworks because of it. Don't know why type checking got really poor support. But I don't think this is deno fault.

**Comment by elycheikhsmail** [comment]
> To make sure your code won't fail in runtime? If the problem is about type checking then it is oak fault, I assume. I quit fancy deno frameworks because of it. Don't know why type checking got really poor support. But I don't think this is deno fault.

thanks

**Comment by satyarohith** [comment]
Closing the issue as stale.
