### ISSUE TITLE
[Bug]: module source not found

### ISSUE THREAD

**Issue by waptik** [denoland/deploy_feedback#421]
### Problem description

I made a report on [discord](https://discord.com/channels/684898665143206084/826085979344470037/1125368847298465827) about an issue i have been facing since morning. It's about my telegram bot built using [grammY](https://grammy.dev) that has not been functioning properly [Ref](https://t.me/grammyjs/147119)
![Screenshot 2023-07-03 at 10 02 51](https://github.com/denoland/deploy_feedback/assets/1687551/1a012979-1884-498a-abd9-01e23f7400f2)

### Steps to reproduce

1. Fork https://github.com/grammyjs/examples/tree/main/deno-deploy and clone it locally
2. Create a new project on deploy, link your copy and set environment variables
3. Click the deploy button, send message through your bot and view your project logs on deno deploy

### Expected behavior

That error shouldn't be available.

### Environment

- Deno version: deno 1.34.3
- Os version: MacOS Ventura 13.4

**Comment by xditya** [comment]
Same issue here.

Facing similar issues with [deno_mongo](https://deno.land/x/mongo@v0.31.2) as well:
![IMG_20230703_164352_795](https://github.com/denoland/deploy_feedback/assets/58950863/ffe14892-309f-4546-ad22-0efac83a84ea)

**Comment by roziscoding** [comment]
Exact same issue as @waptik here

**Comment by waptik** [comment]
> Exact same issue as @waptik here

It's so annoying. According to their reply on discord, there was a recent update (this morning) that cause of it but no ETA on a fix

**Comment by laosb** [comment]
8 hours later still not fixed. Wow.

Not even an official response on that. The status page still reads All systems operational.

**Comment by waptik** [comment]
Guys, i think it has been fixed now. Bot working perfectly and no error from project logs.
Unfortunately, it took 24hrs for it to get fixed which is sad.

Please check on your side if it works before i close this issue.

**Comment by laosb** [comment]
Works for me now!

**Comment by waptik** [comment]
> Works for me now!

Good good! Waiting for others to reply as well

**Comment by lucab** [comment]
Thanks all for the reports and apologies for not posting earlier updates here.
Yesterday (2023-07-03) we rolled out some code changes to support [statically analyzable dynamic imports](https://deno.com/deploy/changelog#2023-07-03) and we believe that the `module source not found` error is a bug that surfaced as a side-effect of those changes.
We've temporarily applied a quick-fix which should avoid that issue, it is already live on our production infrastructure since this morning (4:30 UTC) and from the feedback here it seems to be working fine.

However, we are still investigating the underlying issue, which is specific to some codebases and thus affects only a number of specific projects.
If you have a public codebase that we can look at and where you were encountering this problem, we'll gladly take a look in order to collect more elements for our bug investigation.

**Comment by waptik** [comment]
> Thanks all for the reports and apologies for not posting earlier updates here. Yesterday (2023-07-03) we rolled out some code changes to support [statically analyzable dynamic imports](https://deno.com/deploy/changelog#2023-07-03) and we believe that the `module source not found` error is a bug that surfaced as a side-effect of those changes. We've temporarily applied a quick-fix which should avoid that issue, it is already live on our production infrastructure since this morning (4:30 UTC) and from the feedback here it seems to be working fine.
> 
> However, we are still investigating the underlying issue, which is specific to some codebases and thus affects only a number of specific projects. If you have a public codebase that we can look at and where you were encountering this problem, we'll gladly take a look in order to collect more elements for our bug investigation.

Thanks for responding about the fix and giving us an explanation as to why we faced that issue.

Unfortunately, i don't have any public codebase that faced that issue, only private codebase did. And in my case, it was because i'm importing `https://deno.land/x/grammy@v1.17.1/mod.ts` which in turn imports its helper modules as `dependencies`. See [this](https://deno.land/x/grammy@v1.17.1)

**Comment by roziscoding** [comment]
> If you have a public codebase that we can look at and where you were encountering this problem, we'll gladly take a look in order to collect more elements for our bug investigation.

@lucab The codebase I experienced this bug on is public at https://github.com/roziscoding/amandapix-telegram-bot.
I hope this helps further investigate the issue!
