### ISSUE TITLE
[Bug]: Cannot read properties of undefined (reading 'find')

### ISSUE THREAD

**Issue by SimonKraushaar** [denoland/deploy_feedback#425]
### Problem description

for no apparent reason my account dashboard will no longer display with the error above shown.

### Steps to reproduce

1> Sign in to my account
2 > Error displayed
<img width="1488" alt="image" src="https://github.com/denoland/deploy_feedback/assets/96875962/66e1dfa4-b30f-4681-963c-f22fd40a577e">

### Expected behavior

show my dashboard

**Comment by igorzi** [comment]
Thanks for reporting. This has been fixed.
