### ISSUE TITLE
[Bug]: Deno deploy shows "n.domainMappings is undefined"

### ISSUE THREAD

**Issue by pagoru** [denoland/deploy_feedback#426]
### Problem description

![image](https://github.com/denoland/deploy_feedback/assets/1551265/6f725040-dfc1-4544-b657-c29261f81a17)

### Steps to reproduce

1. Go to deno deploy
2. See the error

### Expected behavior

Work(?)

**Comment by arnauorriols** [comment]
Thanks for reporting! The issue has been fixed now. Make sure to refresh the application for the changes to take effect.
