### ISSUE TITLE
Can’t handle specific module specifiers

### ISSUE THREAD

**Issue by rojvv** [denoland/deploy_feedback#431]
See https://github.com/denoland/fresh/issues/1432#issuecomment-1627477531.

**Comment by lucab** [comment]
Thanks for the report. Indeed it looks like there is some problem on Deno Deploy side with regards to non-ASCII file path. We are looking into this, and it should be hopefully fixed soon. I'll post an update to this ticket once the fix is the deployed.

**Comment by lucab** [comment]
This should be fixed now on Deno Deploy side, closing this ticket. Let us know in case we overlooked something.

**Comment by rojvv** [comment]
Thanks, I tried again and it seems fine now :)
