### ISSUE TITLE
[Bug]: Switching to Deno.serve causing CPU time limit exceeded

### ISSUE THREAD

**Issue by rajsite** [denoland/deploy_feedback#434]
### Problem description

I made a straightforward change from `std/http/server serve` to `Deno.serve` and now get frequent `CPU time limit exceeded` errors on Deno Deploy in the logs.

In the following demos the goal is to see that the pages load without network errors and that the "loop iteration" counter starts running (signifying that the wasm-app resources all loaded and JS can run).

Can see the previous behavior (no errors) deployed to:
https://rajsite.deno.dev
https://rajsite-961gh4f7qarg.deno.dev/ (in-case I make updates)

And the new `Deno.serve` behavior (cpu time errors):
https://rajsite-test.deno.dev/
https://rajsite-test-zde2pshxxy5g.deno.dev/

I see timeouts n the `Deno.serve` case in both the production url and the associated deployment url from Chrome 114.0.5735.199 and Firefox 115.0.2. However, it looks like the production url seems to hit the cpu time error more frequently than the associated deployment url. But seems inconsistent and maybe Chrome-specific? Hard to say.

### Steps to reproduce

Switch to `Deno.serve` as illustrated in the following commit: https://github.com/rajsite/webvi-experiments/commit/98c874975f7c356fafb22ff0a464255757dca7a8

### Expected behavior

More efficient and less overhead, or at least breaks even.

### Environment

Deno deploy

**Comment by rajsite** [comment]
I'm wondering if it's related to brotli compression. Found this issue fixed in Deno 1.35.1: https://github.com/denoland/deno/pull/19758

Initially thought I could not reproduce the deno deploy issue locally as responses were always fast. Tried clearing the cache locally and found Deno.serve was very slow with Deno 1.35.0. Just updated to Deno 1.35.1 and the demo ran much quicker locally. It looks like deploy is still slow though, know when the changes should end up in deploy?

**Comment by rajsite** [comment]
Tried to check the Deno version on deploy but nada:
<img width="744" alt="image" src="https://github.com/denoland/deploy_feedback/assets/1588923/fdbe69ca-d1dc-4656-bdca-48e2e8603dbb">

```ts
console.log("Current Deno version", Deno.version.deno);
```

So yea, assuming the brotli behavior is the issue anyway to know when it'll show up on Deno deploy?

**Comment by lucab** [comment]
Thanks for the report and the additional feedback.
We bumped Deno Deploy internal libraries to 1.35.1 today (around 5:30 UTC). If this is indeed caused by the Brotli-related regression at https://github.com/denoland/deno/issues/19737, it should behave better now.

**Comment by rajsite** [comment]
@lucab Looks like the timeouts are resolved! For a large asset (4.2 MB JS blob 😅) in a very manual un-scientific test with caching disabled it looks like std http results in a very steady ~550ms serving end-to-end while `Deno.serve` is almost always higher at 550ms to 800ms.

Doesn't block me from continuing to try `Deno.serve` since I'm not getting timeouts but not sure the extra cycles for the brotli compression are helpful for server utilization or  for users from my manual trials (in coffee shop wifi :P).

Out of curiosity Is there an option to disable the brotli compression and just use gzip? I see the discussion for [disabling it altogether](https://deno.land/manual@v1.35.1/runtime/http_server_apis#automatic-body-compression) in the manual but not about narrowing the options available. Not blocking, just curious.

I'd consider the issue closed, thanks for the response!
