### ISSUE TITLE
[Bug]: memory hard limit exceeded - logfiles gone

### ISSUE THREAD

**Issue by ghost** [denoland/deploy_feedback#440]
### Problem description

gpc-europe-west2 memory hard limit exceeded, terminated 7/19/2023 9:05:03 AM (GMT + 2)

after this the logfiles were emptied en stay empty during +/- 1 hour

no Denostatus messages

### Steps to reproduce

I can not reproduce this.

### Expected behavior

Running without termination

### Environment

Deno deploy

### Possible solution

As I have no insights in memory use of the deployed scripts/projects I can not see if this from the scripts/project itself or from the outside.

**Comment by magurotuna** [comment]
I would like to clarify, what do you mean by "the logfiles"?

**Comment by ghost** [comment]
By 'the logfiles' I mean the 'The logs from production deployment' that each Deno Deploy project has.

**Comment by magurotuna** [comment]
OK, thanks for the clarification. Currently logs are ephemeral and stored nowhere, so if they are gone there's no way for you to get them again. But we're very actively working on making them retained for a certain amount of time. This feature is pretty close to ship, and I hope this will solve the issue you encountered.

**Comment by ghost** [comment]
Wow, pretty close indeed. It's already working!
Thanks for your help.
