### ISSUE TITLE
[Bug]: A new private github repository created when "Create private repository" option is unchecked

### ISSUE THREAD

**Issue by waptik** [denoland/deploy_feedback#441]
### Problem description

So i just witnessed some weird things happening on the platform.
I tried creating a new project based a [template](https://dash.deno.com/new_from_template?template=oak_rest) and i unchecked the option to create a private repository. 
After the project was created, i went to check my github repositories and there it was, the new created project onDeploy that specifically didn't want it to create a new repository in my GH account

### Steps to reproduce

1. Go to https://dash.deno.com/new_from_template?template=oak_rest or any other template
2. Uncheck the "Create private repository" option
3. Click on "Create and Deploy" and wait
4. Go to https://github.com/`you`?tab=repositories (replace `you` with your github username) and you'll find unwanted repository there

### Expected behavior

A new repository should not be create when a user has unchecked the "Create private repository" option

**Comment by hashrock** [comment]
This is the correct behavior by design.
This checkbox is for switching public/private of the created repository. So a public repository should have been created. 

However, the label description seems to be incorrect or confusing.

cc @kt3k

**Comment by kt3k** [comment]
Unchecking `Create private repository` means that you creates "public" repository on GitHub. So this is the expected behavior.

If you want to try Deno Deploy without creating github repository, you can do it with Playground projects (You can create a playground project by clicking "Hello world" template in [new project page](https://dash.deno.com/new)).

**Comment by waptik** [comment]
Ah ok. I understood it differently
I think a tooltip or a small text underneath it with some description would have been great. 

Thanks for the explanation
