### ISSUE TITLE
Error The deployment failed: Module not found "npm:graphql@16.7.1".

### ISSUE THREAD

**Issue by dogukanakkaya** [denoland/deploy_feedback#444]
I have the below import map in my `deno.jsonc` file:

```
"graphql": "npm:graphql@16.7.1",
```

Which works completely fine in a local environment. But when i try to create the project on Deno deploy I got module not found.

Deno version: `1.35.1`

**Comment by magurotuna** [comment]
npm specifier isn't supported in Deno Deploy yet, although we are very actively working on it. Please stay tuned. Also see #314

**Comment by ry** [comment]
We should probably have a better error message until npm specifiers is supported.

**Comment by lucacasonato** [comment]
NPM specifiers are now supported!

https://deno.com/blog/npm-on-deno-deploy
