### ISSUE TITLE
[Bug]: gcp-asia-east1 is requesting european sources

### ISSUE THREAD

**Issue by ghost** [denoland/deploy_feedback#446]
### Problem description

A Deno deploy that requests multiple files repeatedly from dutch (EU) sites is routed to/served from Google Asia (gcp-asia-east1).
This is technically seen maybe not a bug, but it is not edge first 'minimal latency worldwide'. 
As I can not see the logic in this, maybe there is a problem with Google? (Nothing mentioned in their network status)

The delay or geographicals blocks by the sources cause errors like receiving empty files or msgs like these:
gcp-asia-east1

TypeError: error sending request for url (https://www.vakantiehuis-frankrijk.nl/ical/exporteren.php?ical=XV7N3@RyBHmxFMvYY3Bp3MrfA): connection error: unexpected end of file
    at async mainFetch (ext:deno_fetch/26_fetch.js:266:12)
    at async fetch (ext:deno_fetch/26_fetch.js:490:7)
    at async _getical (file:///src/icalio.js:4549:15)
    at async Server.update (file:///src/icalio.js:4666:32)
    at async Server.#respond (file:///src/icalio.js:190:24)

### Steps to reproduce

Run a Deno script that fetches a european source and see that it is executed from Asia (in the logs)

### Expected behavior

Normally the sources should be fetched from edge locations near the source.

### Environment

Deno deploy

### Possible solution

Ask Google to repair this?
(Google is the last to say the don't know anything about the ID and the locations of their users ...)

**Comment by lucacasonato** [comment]
Hey, could you email us your project ID and GitHub username to support@deno.com?

**Comment by Errel2022** [comment]
Since 13:30 GMT it's executing scripts from Asia again, and causing errors. 
Since my first msg it has switched to US south and east, both without errors.

**Comment by ghost** [comment]
Not fixed within reasonable time.
Production has no priority?
Bye
