### ISSUE TITLE
[Bug]: Logs custom time frame has no warning for end date before start date

### ISSUE THREAD

**Issue by cknight** [denoland/deploy_feedback#449]
### Problem description

When using the custom timeframe, if you set the end date before the start date it does not give you any warning that this is an invalid input and simply returns 0 logs which is confusing.

### Steps to reproduce

1. Visit logs page in Deploy
2. Select Custom timeframe
3. Enter any time frame where the end date is chronologically before the start date
4. 0 results are returned

### Expected behavior

A warning message is presented to the user letting them know the end date should be after the start date or prevent them from entering an end date which is before the start date.

### Environment

Deno Deploy

**Comment by magurotuna** [comment]
In my project custom time frame works fine. Could you give us a little bit more detail?

![image](https://github.com/denoland/deploy_feedback/assets/23649474/526caed4-8020-49de-9e43-bd6be76e58ee)

**Comment by cknight** [comment]
Ahah, I've realised what has happened.  I've been editing the 'end date' as if it were the start date (clearly I need more coffee this morning).  I'll update the title and report.
