### ISSUE TITLE
deno deploy specific docker ?

### ISSUE THREAD

**Issue by elycheikhsmail** [denoland/deploy_feedback#45]
I think deno_ts dev prefere deploying there project using deno instead of using other hosting provider. can deno deploy deploy dockerise deno app in the future? or will deno his specific version of docker for deno app ? we need feedback

**Comment by wperron** [comment]
No, the goal of deploy is to be a fully serverless offering, with no server configuration involved at all.

**Comment by elycheikhsmail** [comment]
ok thank you

**Comment by jsejcksn** [comment]
@wperron How can future breaking API changes be handled by user code if no configuration is possible?

**Comment by wperron** [comment]
@jsejcksn We're still playing around with the APIs while we're in Beta -- we obviously want to be as backwards compatible as possible but breaking changes could happen.

We don't yet have a definite idea of what backwards compatibility and API changes will look like once we reach General Availability, but we will for sure have docs and notices on that topic once that happens.
