### ISSUE TITLE
[Bug]: Log region filtering not working

### ISSUE THREAD

**Issue by cknight** [denoland/deploy_feedback#450]
### Problem description

If I select a region, such as gcp-us-west1, no logs are displayed despite there being log entries for this region.

### Steps to reproduce

1. Visit logs page
2. From list of logs in Live view choose a region for which logs appear
3. Filter on that region by selecting that region in the drop down box
4. Zero logs are shown

### Expected behavior

Logs for that region are shown

### Environment

Deno Deploy

### Possible solution

Looking at the request parameters, there appears to be an extra space in the data.  E.g. here's the (abbreviated) decoded data:

```
{
  query: "",
  timeRangeOption: "custom",
  recentValue: "24hours",
  customValues: { start: "2023-07-23T07:34:22.473Z", end: "2023-07-22T07:00:00.000Z" },
  logLevels: { debug: false, info: false, warning: false, error: false },
  regions: {
    "gcp-asia-east1": false,
    " gcp-asia-east2": false,
    " gcp-asia-northeast1": false,
    " gcp-asia-northeast2": false,
    " gcp-asia-northeast3": false,
    " gcp-asia-south1": false,
   etc.
```

Note the extra space before each region except for the first region.  If I manually edit the request parameter string to remove this space, it correctly filters on the region.

**Comment by magurotuna** [comment]
Thanks for the bug report and sorry for the trouble. We are rolling out the fix right now, so it's going to be fixed shortly. Let us know if there's still something wrong with it.
