### ISSUE TITLE
[Bug]: Log timestamps are out of order

### ISSUE THREAD

**Issue by cknight** [denoland/deploy_feedback#452]
### Problem description

The log entries are not shown in chronological order and there is no sorting mechanism.  This makes for confusing reading:

![image](https://github.com/denoland/deploy_feedback/assets/1248238/ae365b98-87c3-427b-9099-f0519825399e)

See also https://github.com/denoland/deploy_feedback/issues/410

### Steps to reproduce

1. Visit Deno Deploy
2. View logs

### Expected behavior

Logs are sorted in chronological order (ideally descending). 

### Environment

Deno Deploy

**Comment by magurotuna** [comment]
I am not able to reproduce this issue although I looked at a couple of busy projects. Are you seeing this issue constantly? Also, are there specific steps to help reproduce it?

**Comment by cknight** [comment]
Thanks for looking into this.  I'm unable to reproduce it as well.    I'll close this for now and reopen if it comes back.
