### ISSUE TITLE
[Bug]: problem parsing JSON

### ISSUE THREAD

**Issue by roberto-morado** [denoland/deploy_feedback#454]
### Problem description

There appears to be a problem parsing JSON. It is hard to debug because this error does not occur on localhost only when I deploy.

I'm using Fresh, I created a file called `posts.tsx` on the _routes_ directory which renders a list using the `map()` method. It renders fine on _localhost_ but there are problems on Deno Deploy.

The page returns this message:

<img width="468" alt="Screenshot 2023-07-25 at 3 20 04 AM" src="https://github.com/denoland/deploy_feedback/assets/122580309/355c48f0-4c04-400c-83d5-145bd83b3297">

After some tweaking I got the following message:

```ts
An error occurred during route handling or page rendering. SyntaxError: Unexpected non-whitespace character after JSON at position 3
    at JSON.parse (<anonymous>)
    at Object.Repos (file:///src/routes/repos.tsx:48:20)
    at m (https://esm.sh/v129/preact-render-to-string@6.2.0/X-ZS8q/denonext/preact-render-to-string.mjs:2:2602)
    at m (https://esm.sh/v129/preact-render-to-string@6.2.0/X-ZS8q/denonext/preact-render-to-string.mjs:2:3167)
    at m (https://esm.sh/v129/preact-render-to-string@6.2.0/X-ZS8q/denonext/preact-render-to-string.mjs:2:3167)
    at m (https://esm.sh/v129/preact-render-to-string@6.2.0/X-ZS8q/denonext/preact-render-to-string.mjs:2:3167)
    at m (https://esm.sh/v129/preact-render-to-string@6.2.0/X-ZS8q/denonext/preact-render-to-string.mjs:2:3167)
    at E (https://esm.sh/v129/preact-render-to-string@6.2.0/X-ZS8q/denonext/preact-render-to-string.mjs:2:1312)
    at renderInner (https://deno.land/x/fresh@1.3.1/src/server/render.ts:209:16)
    at renderSync (https://deno.land/x/fresh@1.3.1/src/server/render.ts:234:7)
```

### Steps to reproduce

Create a new route and iterate through the object using the `map()` function.

```ts
export const handler: Handlers = {
  async GET(req: Request, ctx: any) {
    try {
      const posts = await fetch(`${new URL(req.url).origin}/api/posts`).then(
        (r) => r.json(),
      );
      return ctx.render({ posts });
    } catch (err) {
      return new Response(err, { status: 500 });
    }
  },
};

export default function Repos(_props: PageProps) {
  const { posts } = _props.data;
  return (
         .
         .
         .
```

### Expected behavior

The page will not render.

### Environment

- deno 1.35.2 (release, aarch64-apple-darwin)
- v8 11.6.189.7
- typescript 5.1.6
- fresh 1.3.1

**Comment by marvinhagemeister** [comment]
The stack trace points at `at Object.Repos (file:///src/routes/repos.tsx:48:20)`. What does the file look like at this line?

> Create a new route and iterate through the object using the map() function.

What does the line with the `map()` function look like? It's not included in the snippet.

**Comment by lucacasonato** [comment]
You can not recursively fetch a deployment from itself in Deploy (so you don't accidentally start an infinite recursion loop 😅). If you inspect the response status code and body, you'll find it shows 508 Loop Detected with a more helpful error message.

Try rewriting your code so that instead of fetching your API from the handler, you just do a direct function call. This will also be more performant, because your data does not have to be serialised to / from HTTP and sent over the network.

**Comment by roberto-morado** [comment]
> You can not recursively fetch a deployment from itself in Deploy (so you don't accidentally start an infinite recursion loop 😅). If you inspect the response status code and body, you'll find it shows 508 Loop Detected with a more helpful error message.
> 
> Try rewriting your code so that instead of fetching your API from the handler, you just do a direct function call. This will also be more performant, because your data does not have to be serialised to / from HTTP and sent over the network.

🤯🤯🤯 I understand; and now that I'm thinking about it, what was I thinking, right? 🤣
