### ISSUE TITLE
[Bug]: Environment Variables

### ISSUE THREAD

**Issue by hapaxlife** [denoland/deploy_feedback#459]
### Problem description

I have set a DENO_DEV variable at the beginning of Deno Deploy.

I can't delete it now.

I have the message error that environnement variable cannot begin by DENO_ 

### Steps to reproduce

set a DENO_DEV variable at the beginning of Deno Deploy 1 year ago
Delete it now

### Expected behavior

I can delete environnement variable begin by DENO_

**Comment by rbetts** [comment]
Hello @hapaxlife - we reserved `DENO_` as a namespace after you created this environment variable. If you would like us to clean this up for your project(s), can you please email support@deno.com with your project name(s) and the variable(s) you'd like us to remove?

Sorry for causing this confusion. Thank you for your feedback.

**Comment by hapaxlife** [comment]
Hi, Thanks
I have sent you an email
