### ISSUE TITLE
[Question] How does outgoing requests count on CPU time?

### ISSUE THREAD

**Issue by JokerQyou** [denoland/deploy_feedback#460]
Deno deploy plans have CPU time limits (10ms for free and 50ms for Pro). If an API route was deployed, and calling the API requires the handler to connect to a third-party (sending notifications via external HTTP requests, for example), how does the outgoing request contribute to the billed CPU time usage? If the external service degraded and only respond after 40ms, does that mean I have only 10ms left to run my own business logic?

**Comment by magurotuna** [comment]
While waiting for the response, CPU time is not consumed because during that period CPU sits idle, just waiting until it's notified that the response has arrived.
You may find https://github.com/denoland/deploy_feedback/issues/290 helpful as well.
