### ISSUE TITLE
[Bug]: Awaiting validation 

### ISSUE THREAD

**Issue by irekgroup** [denoland/deploy_feedback#463]
### Problem description

```
404 Not Found
The requested deployment does not exist.

code: DEPLOYMENT_NOT_FOUND
```

### Steps to reproduce

I'm trying to add my second domain 
It's been a long time but I still get the PENDING Awaiting validation message
I have added all the necessary DNS RECORDS

### Expected behavior

I have already successfully added my first domain, but for some reason the second one is not being added.

**Comment by ry** [comment]
Can you let me know your project id, we can investigate. Feel free to send it to deploy@deno.com if you want to keep it private.

**Comment by irekgroup** [comment]
Send to [deploy@deno.com](mailto:deploy@deno.com). Thanks for the quick feedback!

**Comment by ry** [comment]
solved out-of-band

**Comment by denyncrawford** [comment]
Same here @ry! openv0-worker
