### ISSUE TITLE
API endpoints for environment variables

### ISSUE THREAD

**Issue by nmanoogian** [denoland/deploy_feedback#470]
### What problem are you trying to solve?

Hey Deno team!

I'm on the engineering team at [Doppler](https://www.doppler.com/), a security tool focused on managing secrets. We have integrations with lots of [app hosting providers](https://www.doppler.com/integrations) which allow our mutual users to continuously sync secrets from Doppler to their platforms whenever secrets are modified.

We'd love to see some endpoints available to manage Deno Deploy's environment variables, in order to build an integration.

### Describe the solution you'd like

I noticed that the Deno Deploy website uses `PATCH https://dash.deno.com/_api/projects/:id/env` to manage environment variables. However, it doesn't appear that CLI access tokens can be used with this endpoint. This endpoint format would be perfect for building out an integration.

### Describe alternatives you've considered

N/A

**Comment by piscisaureus** [comment]
@nmanoogian 

We don't have a stable API yet, but we're working on one. In the meantime you're welcome to use the unofficial one that is documented here: https://deno-deploy.redoc.ly/#/paths/~1projects~1%7BprojectId%7D~1env/patch.

**Comment by nmanoogian** [comment]
@piscisaureus Amazing, thanks so much!
