### ISSUE TITLE
[Bug]: Data must be valid JSON

### ISSUE THREAD

**Issue by isaced** [denoland/deploy_feedback#471]
### Problem description

A simple project, after successful deployment, reports an error "Data must be valid JSON".

![image](https://github.com/denoland/deploy_feedback/assets/2088605/cf9f10d4-1808-41b6-a77b-20817f76d0db)

### Steps to reproduce

1. deploy my project
2. visit https://dash.deno.com/projects/xxx

### Expected behavior

Visit the Deno Depoly projects page

**Comment by isaced** [comment]
It seems to be working now

**Comment by lucab** [comment]
Thanks for the report. I think this was a temporary backend glitch, but I couldn't find more details on our logs.
I'm closing this as your project seems fine right now.
If this happens again, feel free to re-open and possibly check your browser console to see if there are more details about the data in the faulty response.
