### ISSUE TITLE
Typo on new_from_repo page

### ISSUE THREAD

**Issue by duffpop** [denoland/deploy_feedback#475]
The GitHub button has a small typo for the word `Organization` - it is currently `Select User or *Organzation*`

<img width="528" alt="image" src="https://github.com/denoland/deploy_feedback/assets/45819703/59b76f85-c6d4-450f-a110-f68196b5cf06">

**Comment by lucab** [comment]
Thanks for the report! The typo has been addressed and the fix should be already live.
