### ISSUE TITLE
[Bug]: Fresh App stopped deploying

### ISSUE THREAD

**Issue by sco** [denoland/deploy_feedback#476]
### Problem description

My Fresh app works in development but stopped deploying to Deno Deploy a few days ago, with the error: "The deployment failed: npm: specifiers are not yet supported on Deno Deploy".

I don't see any npm: specifiers in my project. The build logs don't provide any clues as to the location of the problem.

### Steps to reproduce

1. Attempt to deploy my project ("micro.guru")

### Expected behavior

Successful deployment or an actionable error message

**Comment by ry** [comment]
Maybe related https://github.com/denoland/deploy_feedback/issues/473? Are you using `deno.land/x/marked`?

**Comment by sco** [comment]
@ry that was it -- removing `marked` fixed it. Thank you!
