### ISSUE TITLE
[Bug]: Error: An internal server error occurred.

### ISSUE THREAD

**Issue by dogukanakkaya** [denoland/deploy_feedback#488]
### Problem description

I am trying to deploy my project that uses npm modules via GitHub actions (since it's supported from now on https://deno.com/blog/npm-on-deno-deploy)

But i am having the error in the title.

When I check the logs from the network in Deno Deploy and I see that the last log is:
```json
{
    "type": "error",
    "code": "internalServerError",
    "ctx": "An internal server error occurred."
}
```

I also face the same issue when I do it from the dashboard without any GitHub action step.

### Steps to reproduce

There is no exact steps to reproduce. I am not sure if this is related to project dependencies or not.

### Expected behavior

It should deploy the project.

### Environment

- Deno version: v1.36.4

**Comment by nestarz** [comment]
I also have the same issue, @dogukanakkaya  did you overcome this error ?

**Comment by dogukanakkaya** [comment]
No, still the same.

**Comment by dogukanakkaya** [comment]
I was just developing and commiting new features to my project and CI for deploy was already there and was keep failing before. And all of a sudden one of the deploy workflows succeeded. I am not sure what was the issue to be honest or if it was related with Deno Deploy services (I almost changed nothing that could affect such a problem, unless lock file can create this problem). Because yesterday I was having 500s even from Deno deploy dashboard maybe some issues internally...

**Comment by toyworlds** [comment]
I ran into this as well, needed to delete and recreate deno.lock. It updated from version 2 to 3 which fixed the deploy error.
