### ISSUE TITLE
Deno Deploy: prevent preview builds from going to prod by default

### ISSUE THREAD

**Issue by JorensM** [denoland/deploy_feedback#491]
When I push changes to my repo, Deno Deploy automatically creates a deployment and makes it the production deployment. I would like to have newly created deployments not be made prod by default. Thanks!

**Comment by marvinhagemeister** [comment]
@JorensM Only the branch you selected in Deno Deploy is treated as the production branch. To make preview deployments you can create an new branch and open a PR for that in your repository. Every PR gets their own preview deployment.

**Comment by JorensM** [comment]
@marvinhagemeister I see. Thanks for clarifying!
