### ISSUE TITLE
[KV Feedback]: Value committed

### ISSUE THREAD

**Issue by kitsonk** [denoland/deploy_feedback#492]
### 🔍

- [X] Did you search for existing issues?

### Type of feedback

Bug report

### Description

Attempting to upload data remotely, the data appears briefly in [dash.deno.com](https://dash.deno.com/projects/tswhy/kv) but then disappears after a bit, making it unavailable for the application.

### Steps to reproduce (if applicable)

1. Run `deno task build docs -p` from [ts-why/tswhy](https://github.com/ts-why/tswhy)
2. Note values visible in project
3. Note that values disappear

### Expected behavior (if applicable)

Values persisted to Deno KV do not disappear.  This is what occurs locally with Deno CLI.

**Comment by losfair** [comment]
Hello,

We have identified the cause to be a recent backward-incompatible change in the KV system. It caused written values from remote clients to incorrectly have an expiration time of zero. We are working on a fix.

Projects on Deno Deploy are not affected.

**Comment by kitsonk** [comment]
Thanks for the update. For my use case it is really impossible to work around, as the source data requires source data from outside the deploy deployment. Hopefully it is a quick fix.

**Comment by losfair** [comment]
A fix has been deployed. @kitsonk could you try it again?

**Comment by kitsonk** [comment]
@losfair thank you, it appears to be resolved.
