### ISSUE TITLE
Error in logs: TypeError: Cannot read property 'UnexpectedEof' of undefined   at https://deno.land/std@0.84.0/io/bufio.ts:15:51

### ISSUE THREAD

**Issue by ymeskini** [denoland/deploy_feedback#5]
I get the following error once I deployed a simple version of the web server from the docs

```
TypeError: Cannot read property 'UnexpectedEof' of undefined   at https://deno.land/std@0.84.0/io/bufio.ts:15:51
```

**Comment by bnoordhuis** [comment]
Thanks for the report. It's been fixed upstream. The next release (std@0.93.0) will work seamlessly on Deploy.

**Comment by rodchile** [comment]
Hello Team! I have a similar error on my deployed app on Deno.com

```
TypeError: Cannot read property 'UnexpectedEof' of undefined
    at https://deno.land/std@0.69.0/io/bufio.ts:15:51
```

Was wondering if this might be related with this issue?

**Comment by rodchile** [comment]
For context, the only dependency I have on the project is Opine 1.5.4 which seems to rely on std 0.100.0

**Comment by satyarohith** [comment]
Hi, @rodchile. From the error message, I see that you are using `std@0.69.0`. Support for `io/bufio` on Deploy has been introduced in `0.92.0`. Is the issue reproducible with the latest version of std (`0.100.0`)?
