### ISSUE TITLE
link fails for pogo (http server library)

### ISSUE THREAD

**Issue by sigs** [denoland/deploy_feedback#50]
Maybe I'm doing something wrong here (not listening to "fetch" event but trying directly pogo that uses deno http server), but...

I get
```
Failed to link project
The deployment failed: Expected >, got basePath at https://deno.land/x/pogo@v0.5.2/lib/helpers/directory.tsx:30:43
```

when I try to "link" the following file: https://github.com/sigs/mutaatti/blob/main/src/start-server.ts

I think next I'll try creating another entry point / server file that uses the "fetch" listener described in https://deno.com/deploy/docs/hello-world

It's just, that syntax seems a bit unwieldy... what's the reason you wouldn't unify "running http server locally" and deno deploy? Would make life much easier for deno developers.

**Comment by lucacasonato** [comment]
> what's the reason you wouldn't unify "running http server locally" and deno deploy? Would make life much easier for deno developers

We're working on it!

**Comment by sigs** [comment]
also a bit unclear in the documentation if it's possible to read "local" files in the script, since that's I guess not a common thing for Web Workers to do...

**Comment by sigs** [comment]
I mean, I guess I could package whatever data the script needs into the file (or a dependency that would them be imported), but maybe my current approach of "read and parse and xml file" is right out?

**Comment by lucacasonato** [comment]
> also a bit unclear in the documentation if it's possible to read "local" files in the script

It is not possible yet. We are working on that too though :-)

**Comment by sigs** [comment]
thank you for the super quick responses! It's going to require a bit of refactoring / new stuff the learn then I guess, but really interesting project nevertheless. I guess I'll first try more traditional cloud (like https://github.com/TooTallNate/vercel-deno) then come back after that's running :)
