### ISSUE TITLE
[Bug]: KV Viewer crashes with 'String contains an invalid character' when KV value is `new Uint8Array()`

### ISSUE THREAD

**Issue by johnspurlock** [denoland/deploy_feedback#507]
### Problem description

 KV Viewer crashes with 'String contains an invalid character' when KV value is `new Uint8Array()`

### Steps to reproduce

add an entry to your project's KV db with the value: `new Uint8Array()`

Select the "KV" tab in the project dashboard:

Tab rendering crashes:
![image](https://github.com/denoland/deploy_feedback/assets/528937/25e44c4d-a531-496f-9008-35b1d957395a)

### Expected behavior

view the data

**Comment by ry** [comment]
This bug should be fixed now.

**Comment by johnspurlock** [comment]
confirmed, thanks!
<img width="145" alt="image" src="https://github.com/denoland/deploy_feedback/assets/528937/0fdd1ae0-d07f-4679-bf44-235b1934f32d">
