### ISSUE TITLE
[Bug]: Create Project page duplicate repos data pulled from github

### ISSUE THREAD

**Issue by champkeh** [denoland/deploy_feedback#509]
### Problem description

<img width="1828" alt="image" src="https://github.com/denoland/deploy_feedback/assets/7316006/41cf8cda-0654-44a3-b37b-08aaf1f9bcd9">

It seems to be related to paging, repeating every 30 items

### Steps to reproduce

Refer to the screenshot above

### Expected behavior

Get the correct repos data

**Comment by ry** [comment]
This bug has been fixed.
