### ISSUE TITLE
Error: internal communication error

### ISSUE THREAD

**Issue by MarkTiedemann** [denoland/deploy_feedback#51]
A function I wrote is hitting a bunch of "internal communication errors":

```
Error: internal communication error
    at deno:core/core.js:86:46
    at unwrapOpResult (deno:core/core.js:106:13)
    at Object.opSync (deno:core/core.js:120:12)
    at respondWith (deno:deploy/js/10_sr.js:97:34)
    at FetchEvent.respondWith (deno:deploy/js/10_sr.js:49:7)
    at https://gist.githubusercontent.com/(...redacted...)
```

```javascript
async function new_response() {
  // ...
  let response_html = `// ...`;
  let response = new Response(response_html, {
    headers: { "content-type": "text/html; charset=utf-8" }
  });
  return response;
}

addEventListener("fetch", async function (event) {
    event.respondWith(await new_response());
});
```

Not sure whether I can ignore them.

**Comment by lucacasonato** [comment]
This snippet is working for me no problem: https://gist.githubusercontent.com/lucacasonato/d3a5048d2f910c91e1362efc07c52ca0/raw/9d5cdb0ab2302ca1c3424bce3283e3963db49f4f/test.js

https://kind-crow-36.deno.dev/

Also pass the `Promise<Response>` to `respondWith` without awaiting it (respondWith can take a `Response` or `Promise<Response>`). The event handler shouldn't be async.

**Comment by MarkTiedemann** [comment]
> Also pass the `Promise<Response>` to `respondWith` without awaiting it (respondWith can take a `Response` or `Promise<Response>`). The event handler shouldn't be async.

I know that I could pass `Promise<Response>` as well.

The question is: Why should it not be async? I think an async event handler should work fine, too. And it does -- just some of the time. That's the feedback, I guess. I hit `Error: internal communication error` every now and then - but not for every request. The behavior is quite inconsistent.

**Comment by lucacasonato** [comment]
It works right now, but that is due to a bug and will be fixed soon (before we go into GA). Event responses always have to be registered synchronously in the event handler - that is what the web specs mandate :-)

**Comment by MarkTiedemann** [comment]
Okay, got it. Thanks, @lucacasonato!

**Comment by lucacasonato** [comment]
And thannks for reporting that `Error: internal communication error`. I have found the root cause. It should be resolved soon.
