### ISSUE TITLE
Help Wanted: It works fine locally, but not where I deployed it with deno deploy

### ISSUE THREAD

**Issue by Seasawher** [denoland/deploy_feedback#512]
I deploy my p5js project on GitHub Action to deno deploy.

When I open the deployed URL, the js does not seem to be working.

In the developer tools, the following error message appears in the deployed environment.

> Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "". Strict MIME type checking is enforced for module scripts per HTML spec.

How can I get the js to load correctly?

my code is here: https://github.com/Seasawher/game-of-life/tree/333e0b7ef20ae979251e5532e5fca6826d1b8bb5

**Comment by Sasikumar00** [comment]
Make sure your server is configured to serve JavaScript files with the correct MIME type, which is "application/javascript". This can usually be done in your server configuration or in a .htaccess file if you're using Apache.

**Comment by marvinhagemeister** [comment]
@Sasikumar00 Deno Deploy does not run on apache2.

@Seasawher I can reproduce the issue locally when I remove the `dist/` argument from the `serve` task. I think that's the way it's run on Deploy, but maybe the Deploy team can chime in.

**Comment by Seasawher** [comment]
@Sasikumar00 

> Make sure your server is configured to serve JavaScript files with the correct MIME type, which is "application/javascript". This can usually be done in your server configuration or in a .htaccess file if you're using Apache.

How can deno deploy allow me to configure it?

I thought deno deploy would set it up automatically.
