### ISSUE TITLE
[KV Feedback]: KV seems to take a while to kick in on redeployments

### ISSUE THREAD

**Issue by Smidgens** [denoland/deploy_feedback#517]
### 🔍

- [X] Did you search for existing issues?

### Type of feedback

General feedback

### Description

Whenever I push changes to my project's source repo, I see an immediate `Deno.openKv is not a function` error in the project logs, and then nothing for a while until suddenly it starts working.

Is there an extra step I'm missing? Like declaring that the app uses unstable features, because it almost seems like Deploy is stepping in after the error to infer what happened and applying a fix (setting `--unstable` for the execution environment or some such).

**Comment by igorzi** [comment]
@Smidgens - thanks for reporting this. We've identified the problem, and the fix will rollout today or tomorrow.

**Comment by Smidgens** [comment]
> We've identified the problem, and the fix will rollout today or tomorrow.

Brilliant!
