### ISSUE TITLE
[Bug]: Module not found error on dynamic imports

### ISSUE THREAD

**Issue by dogukanakkaya** [denoland/deploy_feedback#518]
### Problem description

I have this piece of GraphQL Schema build code.
```ts
import * as path from "std/path/mod.ts";
import { loadFiles } from "graphql-tools/load-files";

const typeDefFiles = await loadFiles(path.join(Deno.cwd(), "src/**/types.graphql"));
const resolverFiles = await loadFiles(path.join(Deno.cwd(), "src/**/resolvers.ts"), {
  requireMethod: async (path: string) => {
    const module = await import(path);
    return module.default;
  },
  recursive: true,
});
```

This works completely fine in local but I am having the below issue on Deno Deploy environment. First I thought `/src/src` one could be duplicate and tried to remove it by replacing one but error consist. Anyways `mod.ts` file works fine which is in the same directory as `resolvers.ts` file, so it's certain the file is there.

> TypeError: module not found: 'file:///src/src/graphql/resolvers.ts'
    at async requireMethod (file:///src/src/graphql/mod.ts:15:20)
    at async file:///node_modules/.deno/@graphql-tools+load-files@7.0.0/node_modules/@graphql-tools/load-files/esm/index.js:170:33
    at async Promise.all (index 0)
    at async file:///src/src/graphql/mod.ts:13:23

<br/>

You can also see my directory structure to check if the files are there.
<img width="255" alt="Screenshot 2023-10-07 at 16 05 53" src="https://github.com/denoland/deploy_feedback/assets/51231605/71a63167-46fe-4a28-aa7e-b68adde1025c">

### Steps to reproduce

To reproduce you can create the same structure and same code as above. See the dependencies for it:

`deno.jsonc`
```json
"imports": {
    "std/": "https://deno.land/std@0.198.0/",
    "graphql": "npm:graphql@16.8.0",
    "graphql-tools/schema": "npm:@graphql-tools/schema@10.0.0",
    "graphql-tools/merge": "npm:@graphql-tools/merge@9.0.0",
    "graphql-tools/load-files": "npm:@graphql-tools/load-files@7.0.0"
  },
```

### Expected behavior

Should work as expected, same as local.

### Environment

- Deno version: 1.37.1

**Comment by ry** [comment]
Deploy only supports dynamic imports with a string literal, not dynamically importing modules that are not known ahead of time.
