### ISSUE TITLE
Proxy to some servers fails

### ISSUE THREAD

**Issue by fu-sen** [denoland/deploy_feedback#52]
I see some servers returning `400 Bad Request` or` 404 Not Found` when referencing an external server with a proxy from Deno Deploy.

The sample code has a simple configuration using Sift:
```
import { h, serveStatic, serve } from "https://deno.land/x/sift@0.3.2/mod.ts";

serve({
  "/example": serveStatic("/", { baseUrl: "https://example.net.eu.org", cache: false }),
});
```

I also used a source like this on Cloudflare Workers. This also works with Deno Deploy.
```
const proxyMAP = new Map([
  ["/example", "https://example.net.eu.org/"]
])

async function handleRequest(request) {
  const requestURL = new URL(request.url)
  const location = proxyMAP.get(requestURL.pathname)
  const search = requestURL.search

  if (location) {
    let response = await fetch(location + search, request)
    return new Response(response.body, response)
  }

  return new Response("Not Found", {
    headers: { "content-type": "text/plain" },
    status: 404
  })
}

addEventListener("fetch", event => {
  event.respondWith(handleRequest(event.request))
})
```

<del>Of course you can see it in such a simple source:</del>
```
addEventListener("fetch", (event) => {
  event.respondWith(handleRequest(event.request));
});

async function handleRequest() {
  return fetch("https://example.net.eu.org/");
}
```

Servers (web services and clouds) that I have confirmed to return errors in references.

- Microsoft Azure Web App (*.azurewebsites.net)
- Neocities (*.neocities.org)
- Surge (*.surge.sh)

Other servers may have the same problem with this feel.
Cloudflare Workers has confirmed that these servers can be referenced normally.
Therefore, I have determined this to be a Deno Deploy server level issue and reported it here.

Edit: While reporting here, it was confirmed that this problem does not occur for simple source.

**Comment by satyarohith** [comment]
This is working as expected. The HTML in `https://example.net.eu.org`, for example, makes requests to `/css/base.cs`, which resolves to `yoursite.com/css/base.css` instead of `yoursite.com/example/css/base.css`. Hence, you're encountering 404s. The below code will work.
```js
import { h, serveStatic, serve } from "https://deno.land/x/sift@0.3.2/mod.ts";

serve({
  "/example": serveStatic("/", { baseUrl: "https://example.net.eu.org", cache: false }),
  "/:filename+": serveStatic("/", { baseUrl: "https://example.net.eu.org", cache: false }),
});
```
Deployment: https://proud-rook-25.deno.dev/example

**Comment by fu-sen** [comment]
> This is working as expected. The HTML in `https://example.net.eu.org`, for example, makes requests to `/css/base.cs`, which resolves to `yoursite.com/css/base.css` instead of `yoursite.com/example/css/base.css`. Hence, you're encountering 404s. The below code will work.

This has nothing to do with this report. `example.net.eu.org` is what I provide as an alternative to` example.com` and `example.net`. You can check at the appropriate address.

**Comment by fu-sen** [comment]
Oh, I know @satyarohith is the author of sift. So you would have replied quickly. 
But proxies other than Sift also have this issue, so I'm reporting it to the Deno Deploy issue.

However, Sift `serveStatic()` is an easy proxy implementation for Deno Deploy, so this should also affect Sift.

**Comment by lucacasonato** [comment]
I don't understand what the issue is. https://far-ant-41.deno.dev/ is the following code:
```js
addEventListener("fetch", (event) => {
  event.respondWith(handleRequest(event.request));
});

async function handleRequest() {
  return fetch("https://example.net.eu.org/");
}
```

Proxy looks to be working correctly. Do you have an example that reproduces the issue you are seeing?

**Comment by fu-sen** [comment]
> Proxy looks to be working correctly. Do you have an example that reproduces the issue you are seeing?

You guys don't understand my report correctly. "I have a problem when proxying to a particular server".

> Servers (web services and clouds) that I have confirmed to return errors in references.
>
> - Microsoft Azure Web App (*.azurewebsites.net)
> - Neocities (*.neocities.org)
> - Surge (*.surge.sh)

**Comment by lucacasonato** [comment]
https://far-ant-41.deno.dev/ now proxies to `https://foo.azurewebsites.net`, and it works fine. Do you have an example of a request that is failing?

**Comment by lucacasonato** [comment]
And https://far-ant-41-29c3a24b.deno.dev/ now proxies to https://foo.neocities.org/. Again working fine for me.

**Comment by fu-sen** [comment]
Thank you for your confirmation. Check the same source in my account and check https://foo.neocities.org/ and it works. I understand Azure as well.

But something strange is happening. I can publish more specific code:

Gist: https://gist.github.com/fu-sen/2dea61502377c212f250e31bc4f551b2
RAW: https://gist.githubusercontent.com/fu-sen/2dea61502377c212f250e31bc4f551b2/raw/c703b9dc26687a5b18f909158e2ad5648078b1a8/server-test.js

I have this at `20210617-7aa91e9b.deno.dev`

- https://20210617-7aa91e9b.deno.dev/
- https://20210617-7aa91e9b.deno.dev/test
- https://20210617-7aa91e9b.deno.dev/neocities
- https://20210617-7aa91e9b.deno.dev/surge

What's happening between the servers?

**Comment by fu-sen** [comment]
With Sift:

Gist: https://gist.github.com/fu-sen/dd29a16dc0dedf1e588c7b719e740d91
RAW(To Deploy URL): https://gist.githubusercontent.com/fu-sen/dd29a16dc0dedf1e588c7b719e740d91/raw/1898eb5984040919f2747006c963fb55050a9fa5/server-test.js

I prepared this in `20210617-7aa91e9b.deno.dev`:

- https://20210617-2-fefe69a3.deno.dev/
- https://20210617-2-fefe69a3.deno.dev/test
- https://20210617-2-fefe69a3.deno.dev/neocities
- https://20210617-2-fefe69a3.deno.dev/surge

**Comment by fu-sen** [comment]
A simple source. This was enough to encounter the problem.

```
async function handleRequest(request) {
  const url = new URL(request.url)
  url.hostname = "foo.neocities.org"
  return await fetch(url.toString(), request)
}

addEventListener("fetch", event => {
  event.respondWith(handleRequest(event.request))
})
```

For example, if you change `foo.neocities.org` to` example.net.eu.org`, you can connect normally.

**Comment by lucacasonato** [comment]
The issue is that you are explicitly setting a `Host` header (this understandably is confusing the upstream host), because you are using the original `request` as the option bag for `fetch`. I have opened an issue to get this fixed in Deno: https://github.com/denoland/deno/issues/11017.

**Comment by fu-sen** [comment]
I understand that the answer may be related to the problem. I will test it again after the correction is made.

**Comment by fu-sen** [comment]
I tried this again. Now every server works. I can close this issue. Thank you for your support and response!
