### ISSUE TITLE
Deno.version gives empty strings on Deno Deploy playground

### ISSUE THREAD

**Issue by rattrayalex** [denoland/deploy_feedback#533]
At https://dash.deno.com/playground/

Input:
```ts
console.log(Deno.version)
```
Output:
```
gcp-us-east4 { deno: "", v8: "", typescript: "" }
```
Expected: 
```
{ deno: "1.37.2", v8: "11.8.172.13", typescript: "5.2.2" }
```
(or equivalent)

**Comment by fro-profesional** [comment]
Deno cli and deno deploy are not the same runtime

**Comment by rattrayalex** [comment]
Ah, sorry, thank you for forwarding to the correct location!

**Comment by adamtaylor13** [comment]
Note that this is not limited to the playground: https://github.com/denoland/deploy_feedback/issues/437

**Comment by satyarohith** [comment]
Closing this as duplicate of https://github.com/denoland/deploy_feedback/issues/437
