### ISSUE TITLE
dash.deno.com dark mode

### ISSUE THREAD

**Issue by nhrones** [denoland/deploy_feedback#537]
### What problem are you trying to solve?

Moving to https://docs.deno.com/deploy/manual (dark mode) and then back to https://dash.deno.com/projects is a very jarring experience.  Will dash.deno.com eventually get a dark mode?

### Describe the solution you'd like

dash.deno.com -- dark mode

### Describe alternatives you've considered

none

**Comment by arnauorriols** [comment]
Consolidating into https://github.com/denoland/deploy_feedback/issues/82

**Comment by nhrones** [comment]
The problem with closed source!  You can't use public resources to accomplish something as trivial as a Dark-Theme!
