### ISSUE TITLE
[Bug]: dark mode on Deno Deploy changelog

### ISSUE THREAD

**Issue by felix-schindler** [denoland/deploy_feedback#541]
### Problem description

There's a bug on the Deno Deploy Changelog site where the Markdown content is rendered in dark mode but with grey text color and the other half of the site still being white.

<img width="1792" alt="Bildschirmfoto 2023-11-15 um 19 15 29" src="https://github.com/denoland/deploy_feedback/assets/65357346/d52bbc65-4cf1-4d5e-8465-1711260c4e70">

### Steps to reproduce

1. Activate dark mode on your system
2. Launch a browser that supports dark mode
3. Visit https://deno.com/deploy/changelog

### Expected behavior

Markdown content in light mode

### Environment

- OS: macOS 14.1.1
- Browser: Safari 14.1

**Comment by kt3k** [comment]
@felix-schindler Thanks for reporting! That page wasn't ready for dark mode. We changed the color scheme of the page back to light mode.
