### ISSUE TITLE
[Bug]: Cannot invite members

### ISSUE THREAD

**Issue by NikoLandgraf** [denoland/deploy_feedback#544]
### Problem description

I have a pro account and would like to invite other members. 
I tried both, their github username as well as their github e-mail address - both resulting in an "API ERROR - the user was not found...". error.

### Steps to reproduce

1. invite member with github account

### Expected behavior

invite should work

**Comment by magurotuna** [comment]
Do the invited members have an account in Deno Deploy? In order for someone to be invited to Deno Deploy, an invited user has to have signed up already.
This section of doc might also be helpful: https://docs.deno.com/deploy/manual/organizations#add-members

**Comment by NikoLandgraf** [comment]
Thanks for letting me know.

**Comment by magurotuna** [comment]
I'm closing this issue as (probably) resolved. If you still have an issue, feel free to reopen or create a new one, we're happy to answer.
