### ISSUE TITLE
[KV Feedback]: `DENO_KV_ACESS_TOKEN` shown in Deno Deploy on KV tab has typo

### ISSUE THREAD

**Issue by bdevos** [denoland/deploy_feedback#545]
### 🔍

- [ ] Did you search for existing issues?

### Type of feedback

Documentation improvement

### Description

On the KV tab in Deno Deploy for your Project, there is the section: "Connect to this database from Deno CLI"

In the description below it says:

```
You'll need to [store an access token](https://docs.deno.com/kv/manual/on_deploy#connect-to-managed-databases-from-outside-of-deno-deploy) in the DENO_KV_ACESS_TOKEN environment variable to use this. [Set up access tokens for Deno CLI](https://dash.deno.com/account#access-tokens)
```

But when using `DENO_KV_ACESS_TOKEN`, Deno will complain that it is looking for `DENO_KV_ACCESS_TOKEN`.

### Steps to reproduce (if applicable)

1. Go to the KV page on Deno Deploy, the URL is something like this https://dash.deno.com/projects/***/kv
2. The typo in the env variable is on the above page 😄 

### Possible solution (if applicable)

Change `DENO_KV_ACESS_TOKEN` to `DENO_KV_ACCESS_TOKEN`.

**Comment by magurotuna** [comment]
Thanks for flagging, this is certainly a typo. We'll fix this shortly.

**Comment by magurotuna** [comment]
We plan to ship the fix next week.
