### ISSUE TITLE
[Bug]: Deno Deploy KV may be down

### ISSUE THREAD

**Issue by evbogue** [denoland/deploy_feedback#554]
### Problem description

Seeing `TypeError: KV reads quota is exhausted.` but none of my projects have more than 500 reads this month.

Seeing `Error: k.ranges is undefined` in deno.dev dashboard when trying to view data tables.

This error appears across all projects.

### Steps to reproduce

See above.

### Expected behavior

Deno KV on Deploy should work until quota is reached.

**Comment by evbogue** [comment]
More info from the Deno team on Discord. Apparently this hit counter example app https://github.com/evbogue/deno-visits/blob/master/serve.js ran up 820k reads for some reason. 

How the app did that I haven't been able to figure out yet. It should have wrote every time it was loaded, so not sure why the reads and the writes aren't the same.

**Comment by evbogue** [comment]
Turns out is a loop that requests from all of the edge functions calling kv.get onmessage. Closing.

**Comment by h7ml** [comment]
Again, I've had this problem for two days now. I know that the kv of that project is full. But I can't clear the kv in the interface of that project right now. There's also no official channel to contact for feedback to reset it.
