### ISSUE TITLE
Unable to invite members to a PRO plan

### ISSUE THREAD

**Issue by jtomchak** [denoland/deploy_feedback#556]
### Problem description

Under Org -> Settings -> Invite Members Adding user's GitHub handle returns the following error: 
![Safari 2023-12-04 at 08 37 21@2x](https://github.com/denoland/deploy_feedback/assets/76360/945d7876-2d26-4cfc-924d-2b6580eead46)
The request returns 404, URL: https://dash.deno.com/_api/organizations/d216e8d4-3d8d-4d20-a764-45484a0c5a92/invites
Status: 404

### Steps to reproduce

1. With a PRO plan try to add a new member to the Org by GitHub Handle
2. Add only the handle, not the full url `rileyhCode`
3. User does not get an invite, the request 404's, and the UI displays an error. 

### Expected behavior

1. Add member as pending
2. Send out invite to Org

### Environment

- Browser Mac Safari Version 17.1.2 (19616.2.9.11.12)

**Comment by lucacasonato** [comment]
Right now the user has to create a Deploy account first. Sorry about that!

**Comment by jtomchak** [comment]
> Right now the user has to create a Deploy account first. Sorry about that!

Oh!!! 🤦‍♂️ I didn’t even think about that route. Easy peasy. Thanks.
