### ISSUE TITLE
[Bug]: Can not open KV tab in project

### ISSUE THREAD

**Issue by bockoblur** [denoland/deploy_feedback#557]
### Problem description

When trying to open KV tab in any of my projects, I am getting:

````
    Uncaught (in promise) TypeError: Cannot set properties of undefined (setting '__private_7__options')
        at new de (kv.tsx?v=vgte4av277d5:1:3658)
        at kv.tsx?v=vgte4av277d5:1:8442
````

And page is stuck

### Steps to reproduce

1. open any project
2. click on 'KV' tab

### Expected behavior

Being able to see the KV page/tab

### Environment

Deno Deploy

**Comment by losfair** [comment]
Thanks for reporting this. A recent frontend rollout broke the KV tab. We are working on a fix.

**Comment by losfair** [comment]
This should be fixed now.
