### ISSUE TITLE
[KV Feedback]: I seem to have broken the online KV ui

### ISSUE THREAD

**Issue by kewp** [denoland/deploy_feedback#558]
### 🔍

- [ ] Did you search for existing issues?

### Type of feedback

Bug report

### Description

Not sure why, but my KV page won't load. https://dash.deno.com/projects/ucn-prices-api/kv

### Steps to reproduce (if applicable)

Click on page https://dash.deno.com/projects/ucn-prices-api/kv
Wait forever

### Possible solution (if applicable)

Maybe I have too much data? Not sure

**Comment by losfair** [comment]
Duplicate of https://github.com/denoland/deploy_feedback/issues/557.

A recent rollout caused the KV tab to stop working. This has been fixed.

**Comment by kewp** [comment]
Yup, it's working now. Thanks
