### ISSUE TITLE
[Bug]: TypeError: Queue backlog limit exceeded

### ISSUE THREAD

**Issue by DonsWayo** [denoland/deploy_feedback#559]
### Problem description

Im trying to make some tries with a lot of new queues, working well all day and now get this error:

TypeError: Queue backlog limit exceeded
    at async Kv.enqueue (ext:deno_kv/01_db.ts:153:26)
    at async generateEnq (file:///src/queue.ts:24:5)

the body is:

```ts
 await kv.enqueue({ "test": 1 });
```

### Steps to reproduce

1. create a queue
2. consume on deno deploy

### Expected behavior

process the kv.enqueue

### Possible solution

maybe hit the free limits?

**Comment by igorzi** [comment]
The project reached the queue backlog limit, which is 100K messages. This means that you've enqueued 100K messages without getting dequeued. Was this the intention?

**Comment by DonsWayo** [comment]
Build a status monitor and test the perfomance, similar thing that already have in AWS.

I cannot see any event log with the dequeued process.

```ts
kv.listenQueue((msg) => {
  console.log("msg", msg);
});

```

**Comment by igorzi** [comment]
Did you enqueue messages with `delay` set? Or are they enqueued to be processed immediately?

**Comment by DonsWayo** [comment]
no, just like that:

```ts
 await kv.enqueue({ "test": 1 });
```
I processed immediately every minute, also see that have a big delay to process 500 events.

After some hours I be able to make more request.
