### ISSUE TITLE
Why second subdomains is not supported?

### ISSUE THREAD

**Issue by ngdangtu-vn** [denoland/deploy_feedback#56]
I have my domain xxx.com, now I want to test deno with second subdomains deno.beta.xxx.com. My domain got `Validated, has certificate`. However it couldn't work due to: `SSL_ERROR_NO_CYPHER_OVERLAP`. And the reason is cert [doesn't work with second subdomains](https://community.cloudflare.com/t/community-tip-fixing-ssl-error-no-cypher-overlap-in-mozilla/42323). So I had to stop the idea and went with deno.xxx.com

It's kinda pity. Can I have and option to not use cert? It just testing anyway.

**Comment by bnoordhuis** [comment]
TLS is always enabled on Deploy, that's not something we can or want to change.

I want to make sure I understand the problem properly. You are saying `deno.xxx.com` works (one subdomain) but `deno.beta.xxx.com` (two subdomains) does not?

**Comment by ngdangtu-vn** [comment]
> I want to make sure I understand the problem properly. You are saying deno.xxx.com works (one subdomain) but deno.beta.xxx.com (two subdomains) does not?

Yes, I did the same setup steps for both domain but only deno.xxx.com works.

**Comment by bnoordhuis** [comment]
It should work when you have both `beta.xxx.com` and `deno.beta.xxx.com` set up at Deploy. Just `deno.beta.xxx.com` without the 1st level subdomain won't work.

**Comment by ngdangtu-vn** [comment]
I've tried as you suggested but it doesn't work for `deno.beta.xxx.com` even though it works well for `beta.xxx.com`.

Can I share my domain in here?

**Comment by lucacasonato** [comment]
Yes. You can also send us an email with details if you don't want to make the domains public.

**Comment by lucacasonato** [comment]
I am closing this issue now. If you are experiencing a similar issue, please email us at deploy@deno.com.
