### ISSUE TITLE
[KV Feedback]: I would like to use KV queue listener on a project but it is not working

### ISSUE THREAD

**Issue by fxnoob** [denoland/deploy_feedback#561]
### 🔍

- [X] Did you search for existing issues?

### Type of feedback

Bug report

### Description

I wanted to test out this queue listener feature but it's not working out for my project here: https://dash.deno.com/projects/sps.

This error message is coming:

TypeError: Default database is not available

**Comment by losfair** [comment]
Hey,

How are you deploying to this project? Is it `deployctl` or another custom tool?

**Comment by fxnoob** [comment]
I am using `deployctl`

**Comment by losfair** [comment]
We have applied a fix. Please redeploy this project and KV should work now.
