### ISSUE TITLE
[Bug]: Deno Deploy Not Recognizing nodeModulesDir Setting

### ISSUE THREAD

**Issue by gibbygano** [denoland/deploy_feedback#564]
### Problem description

When deploying on deno deploy no JS is loaded and when I check the logs I see 
![image](https://github.com/denoland/deploy_feedback/assets/9158457/2a61a8c9-8413-4187-8c42-42576b4780fb).
This happened after changing twind to tailwindcss with the latest fresh update. 

Here is my deno.json file: 
![image](https://github.com/denoland/deploy_feedback/assets/9158457/ab14bb2b-e768-4c06-88ad-3690dfb32973)
This is not an issue in my local environment.

### Steps to reproduce

Use npm:*, set "nodeModulesDir": true in deno.json, then deploy.

### Expected behavior

Application builds and serves JS.

### Environment

Production deno deploy

**Comment by marvinhagemeister** [comment]
@gibbygano Fresh maintainer here. The tailwind plugin requires ahead of time builds to be set up to work. Did you follow step 7 of https://fresh.deno.dev/docs/examples/migrating-to-tailwind ?

**Comment by gibbygano** [comment]
> @gibbygano Fresh maintainer here. The tailwind plugin requires ahead of time builds to be set up to work. Did you follow step 7 of https://fresh.deno.dev/docs/examples/migrating-to-tailwind ?

This yml file here I added? 
![image](https://github.com/denoland/deploy_feedback/assets/9158457/52e59d27-9183-4be4-a459-382008371862)

**Comment by marvinhagemeister** [comment]
@gibbygano That looks good! Did you also switch from "GitHub automatic" to Github Actions" as the deployment mode?

![image](https://github.com/denoland/deploy_feedback/assets/1062408/0cecfe86-332a-4cc1-b651-7f71b14def5b)

**Comment by gibbygano** [comment]
It's not letting me interact with the component, do I need to unlink it first? 

EDIT: Ignore that, yes I do.
