### ISSUE TITLE
Max number of BroadcastChannel connections?

### ISSUE THREAD

**Issue by mikecann** [denoland/deploy_feedback#57]
Suppose I built a chat app on Deno Deploy and it took off, or I wanted to build a multiplayer game that has hundreds of thousands or millions of players.

What are limits on the number of connections from clients that Deploy can handle? The [docs](https://deno.com/deploy/docs/pricing-and-limits) mention 64kb/s "per instance" but no mention on the number of connections each "instance" can handle. 

What is an "instance" anyways? Are they automatically created and destroyed behind the scenes?

**Comment by bnoordhuis** [comment]
"Client connection" means incoming connection from the public internet, like from a browser? There's no hard limit. Deploy is in theory infinitely scalable. It can comfortably handle 10,000s or 100,000s concurrent connections.

If you mean between instances, there's no limit there either, we only rate limit bandwidth.

At the moment we have about 25 edge locations worldwide. An instance runs at the edge and they're created and destroyed on demand. At full capacity, your app would have ~25 instances running concurrently - the number will go up as we bring more locations online.

**Comment by mikecann** [comment]
Thanks for your replay. So for example say I had a chat app that had 100,000 connected users and each of those users sent 1 message every 60 seconds. Each of those messages would then be passed on to 100 of those 100,000 members. 

I would only pay for each of those messages sent from client to server, is that correct? You arnt billed for the time that the client is conected, or for messages sent, only for each message recieved?

**Comment by bnoordhuis** [comment]
We haven't finalized our billing plans yet so I can't really say but I expect we'll charge for bandwidth, not message count, with the first $x GB (TBD) free. Unless that user sends or receives big GIFs or videos, you'd stay well within the free tier.

**Comment by mikecann** [comment]
Okay thats great thanks.
