### ISSUE TITLE
[KV Feedback]: Please use international time formats in Deploy Cron status

### ISSUE THREAD

**Issue by cnrdh** [denoland/deploy_feedback#570]
### 🔍

- [X] Did you search for existing issues?

### Type of feedback

Feature request

### Description

Please use [the correct way](https://xkcd.com/1179/) to write a date in Deploy Cron status, or let the user decide locale via browser settings or input.

Dates likes `12/4` and also  `AM`/`PM` are not accommodating to an international audience.

```md
Name | Schedule | Last Run | Next Run
sync external data to kv | 11 * * * * | Succeeded (12/4/2023, 8:30:00 AM UTC) | 12/18/2023, 12:11:00 PM UTC
```

### Steps to reproduce (if applicable)

Inspect Cron panel on https://dash.deno.com/projects/*/cron

### Expected behavior (if applicable)

Using ISO date/time format with 24H clock

### Possible solution (if applicable)

```js
new Date("2023-12-18T11:11:11Z").toISOString().substring(0,10)
// "2023-12-18"

new Date("2023-12-18T11:11:11Z").toLocaleTimeString([],{ timeZone: "UTC", timeZoneName: "short" })
// "11:11:11 UTC"
```

**Comment by igorzi** [comment]
This should be fixed now
