### ISSUE TITLE
[Bug]:  Deno.env didn't read Environment Variables

### ISSUE THREAD

**Issue by cj-1010-1414** [denoland/deploy_feedback#574]
### Problem description

I have registered environment variables on deployment tab on my dashboard. I access it with `Deno.env.get()`. The result didn't return as I expected when I tested on local development environment with `.env` file. This is what I got:

`error: Uncaught (in promise) LibsqlError: URL_INVALID: The URL is not in a valid format` 

The deployment always fails.

### Steps to reproduce

-

### Expected behavior

It should succeed in deployment.

**Comment by kt3k** [comment]
Deno doesn't automatically load `.env` file. To load it in your local Deno runtime, you need to import `std/dotenv` module like the below:

```js
import "https://deno.land/std@0.210.0/dotenv/load.ts";
```

Alternatively you can also specify `--env` flag to let Deno load `.env` file.

```
deno run --env main.ts
```

**Comment by cj-1010-1414** [comment]
It's not local. In local environment, it works fine without import. It's in the deployment, Deno deploy.

**Comment by satyarohith** [comment]
Hi @kj-1010-1414. If you can provide any code/steps that I can use to reproduce the bug that would be helpful! :)

**Comment by cj-1010-1414** [comment]
wait. I'll create a repo.

**Comment by cj-1010-1414** [comment]
I don't understand. I do it the same way. It succeed on new repo I just created, but failed for my project.

**Comment by cj-1010-1414** [comment]
I'll try to delete and redeploy my project.

**Comment by cj-1010-1414** [comment]
The problem was because I don't put the db connection in a function

```
  const db = createClient({
    url: Deno.env.get("turso_url") as string,
    authToken: Deno.env.get("turso_token")
  })
```

When I put those codes inside a function or a component, it works!
