### ISSUE TITLE
Deploy cron bug

### ISSUE THREAD

**Issue by Luchooo** [denoland/deploy_feedback#588]
Version: Deno 1.39.2

When the cron is configured to run every 10 minutes (minute: {every: 10}), and I make another commit to my main branch, triggering a deployment with a cron set to run every 2 hours (hour: {every: 2}), the cron starts running every 2 minutes instead.

WorkAround: 
1. Create a commit to remove cron and push main.
2. Create a commit to add cron and push main.

**Comment by igorzi** [comment]
Currently `{ hour: {every: 2} }` means "Every 2 hours, run the job every minute for that hour". If you want the job to run once every hour, you should change it to: `{ minute: 0, hour: {every: 2} }`

**Comment by Luchooo** [comment]
> Currently `{ hour: {every: 2} }` means "Every 2 hours, run the job every minute for that hour". If you want the job to run once every hour, you should change it to: `{ minute: 0, hour: {every: 2} }`

Let me try and come back with the success or failed :bowtie:
