### ISSUE TITLE
Enable/clarify wildcard domain support

### ISSUE THREAD

**Issue by jed** [denoland/deploy_feedback#59]
Currently, attempting to add a wildcard domain results in the following error:

> ❌ Failed to update project
> This is a wildcard domain, and this account is not participating in the wildcard domain beta. To get enrolled please contact deploy@deno.com.

Per @lucacasonato [this is incoming](https://discord.com/channels/684898665143206084/826085979344470037/857532189780213811), but I just wanted to clarify.

**Comment by satyarohith** [comment]
Wildcard domains are available under pro subscription: https://deno.com/deploy/pricing

Thanks for opening the issue.
