### ISSUE TITLE
[Bug]: Node/Express runs fine locally but when deployed starts many app servers per request 

### ISSUE THREAD

**Issue by egave** [denoland/deploy_feedback#593]
### Problem description

Hi,
I have a basic node/Express server listening to a port and responding to some paths.
It runs locally without any problem.
But when deployed it calls the entrypoint and initialises/starts the app express server many times.
 
For exemple, in the logs we can see server is started several times in a second... 
`gcp-europe-west2
Express http server started...
16/01/2024 23:17:43`
`gcp-europe-west2
isolate start time: 676.43 ms (user time: 20.66 ms)
16/01/2024 23:17:43`
`gcp-europe-west2
Express http server started...
16/01/2024 23:17:43`
`gcp-europe-west2
isolate start time: 542.47 ms (user time: 18.04 ms)
16/01/2024 23:17:43`
`gcp-europe-west2
Rendering Web site...
16/01/2024 23:17:43`
`gcp-europe-west2
Express http server started...
16/01/2024 23:17:47`
`gcp-europe-west2
isolate start time: 1.19 s (user time: 20.27 ms)
16/01/2024 23:17:47`

### Steps to reproduce

1. Run locally and make some requests : everything runs fine
2. Deploy and make some requests: we can see server is started several times

### Expected behavior

When deployed Express Server is started only once and responds to requests without restarting the server several times.

### Environment

- deno 1.39.2
- OS: Ubuntu

### Possible solution

N/A

**Comment by ry** [comment]
Deno Deploy is a serverless system and restarts your isolate to make room for other users. This is behaving as expected.
