### ISSUE TITLE
[Bug]: cannot add member by github username

### ISSUE THREAD

**Issue by jimz-yucolab** [denoland/deploy_feedback#594]
### Problem description

tried adding member to my organization ( with paid subscription ) with github, it always show "API error", saying : 
```
API Error : the user you are requesting was not found, or you do not have access to view it.
```  

### Steps to reproduce

1. add member to organization via github username

### Expected behavior

member can be added.

### Environment

deno.dev admin dashboard, accessed via browser.

browser : Brave browser
version : 
- v1.61.116 ( failed )
- v1.61.120 ( failed, same error message )
tried both "shields-up" / "shields-down", same failing results.

### Possible solution

nil

### Additional context

nil

**Comment by magurotuna** [comment]
Has the user you were trying to add already signed up for Deno Deploy? If not, please do so and try sending another invite again. (Sorry for the unfriendly error message. This should be improved.)

**Comment by jimz-yucolab** [comment]
@magurotuna , no problem, and you're right, after they have signed-in to Deno Land, invitations can now be made as expected.

i'm good for now, and will close this issue as completed.  Thank you for your prompt response indeed ~

**Comment by magurotuna** [comment]
Glad it's solved! We'll definitely add this improvement as a TODO item.
