### ISSUE TITLE
[Bug]: Incorrect estimated size of KV database

### ISSUE THREAD

**Issue by cknight** [denoland/deploy_feedback#599]
### Problem description

The estimated size of my KV database on Deploy for my 'onjara' project is 318KiB.  However there are only two entries on KV which total roughly 12KiB in size perhaps.  While the values change daily, the maximum size that two entries can be is 132KiB (2 KiB key + 64 KiB value x 2 entries).

### Steps to reproduce

Go to https://dash.deno.com/projects/onjara/kv.  View 'Estimated Size" which shows 318KiB.  Scroll down to data and see only two entries.

### Expected behavior

Estimated size accurately reflects the data in KV.

**Comment by lucab** [comment]
Thanks for the report. The displayed size is a an estimated value reported by the DB, based on some data sampling approximation. It is generally accurate for sets larger than 3 MiB, but for smaller datasets with few entries like in your case it can only provide a very rough approximation.
For that reasons, the value is not used for any kind of billing and it only provides a general idea about DB size, mostly for cases of larger datasets that cannot be visually estimated.
