### ISSUE TITLE
Support Deno.emit API

### ISSUE THREAD

**Issue by jsejcksn** [denoland/deploy_feedback#60]
Even if only remote sources are supported (without filesystem access), this would enable lots of interesting possibilities.

**Comment by wperron** [comment]
At the moment we're leaning towards _not_ including this API in Deploy. The reason being that it is a fairly intricate bit of code that relies on having tsc and swc bundled in the CLI, while we want to keep Deploy as lean as possible. The recommended approach to transpile TS to JS on the fly at the moment would be to use a userland transpiler, something like swc or esbuild compiled to wasm. Incidentaly, this is how [fresh](https://github.com/lucacasonato/fresh) works and it's working pretty well too.

**Comment by jsejcksn** [comment]
> use a userland transpiler, something like swc or esbuild compiled to wasm

@wperron Can you provide any pointers on how I'd get started with this? My first use case is doing JIT compilation and bundling of browser-compatible (not using the `Deno` namespace) modules from deno_std.

I know that Deno uses swc (I see [`@swc/wasm`](https://unpkg.com/browse/@swc/wasm/) and [`@swc/wasm-web`](https://unpkg.com/browse/@swc/wasm-web/)), but I've never used swc apart from Deno, and don't know if there's special configuration needed (e.g. for handling literal specifiers ending in `.ts`, etc.). Is there maybe an example of this case in a repo somewhere? Any help would be appreciated.

**Comment by wperron** [comment]
@jsejcksn I think [fresh](https://github.com/lucacasonato/fresh) is probably the best place to look to get started (it uses esbuild). If you want to check out swc in wasm, maybe look at how Parcel is doing it, I know they rewrote part of Parcel to use swc compiled to wasm under the hood recently.
