### ISSUE TITLE
Github → GitHub

### ISSUE THREAD

**Issue by felix-schindler** [denoland/deploy_feedback#601]
### What problem are you trying to solve?

This authentication button:
<img width="305" alt="Screenshot 2024-01-28 at 14 24 31" src="https://github.com/denoland/deploy_feedback/assets/65357346/32d49780-3912-4765-829e-54c0e41276b5">

### Describe the solution you'd like

Please change the lowercase `h` to an upper case `H`.

> As a programmer you could also say
> "GitHub" needs to be CamelCase

### Describe alternatives you've considered

Leaving it as-is.

**Comment by lucab** [comment]
Thanks for the report. We queued up a fix for this internally, it will go live soon (today/tomorrow).
