### ISSUE TITLE
Keep hitting deploy rate limit

### ISSUE THREAD

**Issue by ca-d** [denoland/deploy_feedback#61]
I keep hitting the limit on too many deploys per hour with my self-deploying deno editor at [https://ide.deno.dev] .

Is there any way I could deploy more frequently? I don't need to keep all the old deployments around either if space is an issue.

**Comment by ca-d** [comment]
![delpoy-rate-limit](https://user-images.githubusercontent.com/20446628/124447592-cf196600-dd81-11eb-9a8e-19e501abde03.png)

This is what it looks like when I hit the deploy rate limit.

**Comment by bnoordhuis** [comment]
I've seen your site, cool project.

We're open to raising the deployment limit. Right now it's 15/hour. Would 30/hour work for your use case?

**Comment by ca-d** [comment]
> I've seen your site, cool project.
> 
> We're open to raising the deployment limit. Right now it's 15/hour. Would 30/hour work for your use case?

Thanks, that's a kind offer, and will surely help a bit, but I think the intended use case would basically require deploying as often as one would hit ctrl+s in a text editor (use deploy as a compiler and linter of sorts), so I guess I'd have to wait for the paid version.

Do you already know whether paid accounts will still have deploy frequency limits?

**Comment by bnoordhuis** [comment]
That might be a problem because we keep old deployments around forever. The frequency is something we can tweak but the storage costs are another matter. I'll bring it up with the team.

**Comment by lewisl9029** [comment]
Also ran into this limit just now. Even the current limit of 30/hour feels excessively restrictive. 

It's not uncommon for a single engineer on a solo project to deploy well past 30 times per hour when prototyping (like I was doing just now), and I can imagine a team of engineers could run against that limit constantly.

Even while prototyping, hitting that limit while you're on a roll _really_ sucks. If this was a production app, being suddenly blocked from deploying when I need to fix a bug would be a complete showstopper that would make me seriously consider migrating away.

I would personally much rather have a limit on old deployments than a limit on deploy rates (outside of maybe a x/s limit to prevent obvious abuse).

**Comment by ca-d** [comment]
> That might be a problem because we keep old deployments around forever. The frequency is something we can tweak but the storage costs are another matter. I'll bring it up with the team.

For this particular use case it would be fine to not keep old versions around forever. Keeping only the latest `n` versions (for small `n`) or only one version per day or something like that would definitely suffice.

**Comment by ca-d** [comment]
Doesn't look like this is too much of an issue for most users, and I've moved on from playing around with the deploy IDE long since. I'll close this for the time being, if anyone still needs this it can be re-opened any time.
