### ISSUE TITLE
[Bug]:  error sending request for url (https://registry-staging.deno.com/@std/collections/meta.json): error trying to connect: dns error: failed to lookup address information: Name or service not known

### ISSUE THREAD

**Issue by juliendorra** [denoland/deploy_feedback#612]
### Problem description

My deployements are failing with 

`The deployment failed: error sending request for url (https://registry-staging.deno.com/@std/collections/meta.json): error trying to connect: dns error: failed to lookup address information: Name or service not known`

Which is not really helpful and might be an error on Deno Deploy part?

### Steps to reproduce

Not sure, as it might be a transient bug? 

### Expected behavior

Deployed repositories 

### Environment

Deno Deploy

**Comment by juliendorra** [comment]
Apparently it was some dependency bug.

The error message is really confusing. There might be improvement on the error reporting to do here

**Comment by magurotuna** [comment]
During a meetup event, one of the participants encountered this issue when running `deno install -Arf jsr:@deno/deployctl`, which is the install command of `deployctl` now instructed in https://github.com/denoland/deployctl
Not sure where this issue comes from, but we definitely need to look into it.

**Comment by magurotuna** [comment]
Confirmed that this issue doesn't happen when running with recent versions of Deno (I think >= 1.40). Updating Deno CLI should solve this issue, so closing this issue now.
Please feel free reopen it when this issue still happens.
