### ISSUE TITLE
[Bug]: Deploys fail with ISOLATE_INTERNAL_FAILURE

### ISSUE THREAD

**Issue by Jess182** [denoland/deploy_feedback#619]
### Problem description

Hi I have tried to deploy different projects and all fail with same error: ISOLATE_INTERNAL_FAILURE
Even I have deployed just a file with `console.log` and it fails too
Is it a global/general error or it's especific for my account?
Thanks

### Steps to reproduce

1. Deploy from GitHub repo
2. No build
3. Packing complete
4. Error

### Expected behavior

Deploy my projects

### Environment

- Deno deoloy

**Comment by machulav** [comment]
I have the same issue when deploying this commit: https://github.com/connery-io/gmail/commit/2e464cfb3d3a7918e50602e59bd9c38897b5af6d

Tried to deploy in both ways:
- Deploy from Deno Deploy UI (https://dash.deno.com/new)
- Deploy using `deployctl deploy`

At the same time the `deno run ./src/index.ts` runs the code successfully.

This is a blocker for us as we can not deploy the project to Deno Deploy.

**Comment by machulav** [comment]
I think I found the reason. The code I tried to deploy didn't do anything and just exported an object. So it's runtime ended up very fast. However, when I added the following line of code, the repo deployed successfully. I assume that Deno Deploy only works if the deployed app runs continuously, like a web server that listens for incoming requests.

```
Deno.serve((req: Request) => new Response("Hello World"));
```

Even though it would be nice to have a more self-explanatory error message in this case 😉

**Comment by Jess182** [comment]
> I think I found the reason. The code I tried to deploy didn't do anything and just exported an object. So it's runtime ended up very fast. However, when I added the following line of code, the repo deployed successfully. I assume that Deno Deploy only works if the deployed app runs continuously, like a web server that listens for incoming requests.
> 
> ```
> Deno.serve((req: Request) => new Response("Hello World"));
> ```
> 
> Even though it would be nice to have a more self-explanatory error message in this case 😉

Thanks for reply, and you are right! after initializing my server, the deployment worked, thanks for the help!
