### ISSUE TITLE
Expose `x-deno-ray` header on inbound requests

### ISSUE THREAD

**Issue by jed** [denoland/deploy_feedback#62]
Currently, the `x-deno-ray` header is added to the response after it is returned from user code, but since this information would be helpful in associating metadata with requests, it would be helpful to pass it as an inbound request header (as do Cloudflare and API Gateway Lambdas).

**Comment by wperron** [comment]
This is now fixed! :tada: the `x-deno-ray` header is available on the Request object on `event.request`

**Comment by jed** [comment]
oh great! thanks, @wperron!
