### ISSUE TITLE
[Bug]: `ISOLATE_INTERNAL_FAILURE` on deploy

### ISSUE THREAD

**Issue by sunnyclimber456** [denoland/deploy_feedback#625]
### Problem description

I'm trying to deploy my project (`weak-alpaca-13`) using `deployctl`. The first deploy worked well, however subsequent deploys fail with:

```
ℹ Using config file '/Users/***/code/***/deno.json'
⠋ Fetching project 'weak-alpaca-13' information...
✔ Deploying to project weak-alpaca-13.
✔ Entrypoint: /Users/***/code/***/script.ts
ℹ Uploading all files from the current dir (/Users/***/code/***)
✔ Found 4 assets.
✔ No new assets to upload.
✖ Deployment failed.
error: The deployment failed: ISOLATE_INTERNAL_FAILURE
```

The only interesting feature I can think of in this project is usage of `Deno.cron`.

### Steps to reproduce

1. Create a project
2. Deploy using `deployctl`
3. Deploy again using `deployctl`

### Expected behavior

Deployment succeeds

### Environment

- Deno 1.41.0
- macOS 13.6

**Comment by lucab** [comment]
Thanks for reaching out.
You didn't mention the whole `deployctl` command you are using, but it sounds like you are trying to push a preview (i.e. non-production) deployment with a cron definition.
You may try pushing your deployment to production instead (with the `--prod` flag), or remove the cron definition for preview deployments.
In any case, you should be able to see failure details in the logs for the specific deployment that failed, in the list at the bottom of https://dash.deno.com/projects/weak-alpaca-13 (under the three-dots menus next to the timestamps).

**Comment by sunnyclimber456** [comment]
Adding `--prod` to the `deployctl deploy` command does the trick! Thanks so much
