### ISSUE TITLE
[KV Feedback]: Transaction domain not found for no apparent reason

### ISSUE THREAD

**Issue by m4rocks** [denoland/deploy_feedback#640]
### 🔍

- [X] Did you search for existing issues?

### Type of feedback

Bug report

### Description

Hello! I have a project where new deployments give this error:
```
Error: txnproxy call failed with client error, status: 404 Not Found, message: {
  "code": "transactionDomainNotFound",
  "message": "Transaction domain not found"
}
    at async KvListIterator.<anonymous> (ext:deno_kv/01_db.ts:141:30)
    at async KvListIterator.next (ext:deno_kv/01_db.ts:579:21)
    at async getAppsRandom (file:///src/src/lib/db.ts:176:26)
    at async Welcome (file:///src/src/routes/index.tsx:28:15)
    at async render (https://deno.land/x/fresh@1.6.8/src/server/render.ts:215:19)
    at async https://deno.land/x/fresh@1.6.8/src/server/context.ts:406:24
    at async handler (https://deno.land/x/fresh@1.6.8/src/server/context.ts:293:14)
    at async ext:deno_http/00_serve.js:455:18
```
Previous deployments don't have this problem and new deployments did not modify any related dependencies or files.

I did come across a similar issue related to env variables. I did delete some env variables recently, but it never became a issue even after a few deployments.

**Comment by losfair** [comment]
Hello,

Thanks for reporting this issue. Our KV cluster in Europe stopped receiving configuration updates during the past few hours. This has been resolved - your project should be working now.

https://denostatus.com/clu6vqrdo0880b4n5hh5unb4r

**Comment by m4rocks** [comment]
Hi! Sorry I forgot to check denostatus.com before. The issue has been fixed. Thanks!
