### ISSUE TITLE
Express-like http framework?

### ISSUE THREAD

**Issue by rikilele** [denoland/deploy_feedback#65]
I've started to create an express-like http framework called [Kyuko](https://deno.land/x/kyuko).
It currently supports the minimum features needed like `res.send()`, `res.redirect()`, and `res.json()`.

Would anyone here care to review whether the project's going in the right decision and follows the philosophies for Deno Deploy well?

I'd also be delighted to be taught what it would take for Kyuko to be worthy of being featured on the [http frameworks page](https://deno.com/deploy/docs/resources-frameworks).

Thanks!

@ repository owners: please feel free to close this issue, as it isn't technically "feedback".

**Comment by wperron** [comment]
Hi, thanks for your interest, but as this is indeed not feedback on the platform, I'll close this issue. If you're looking for feedback on your project I think the [discord server](https://discord.gg/deno) is probably the best place to start.
