### ISSUE TITLE
[Bug]: ReferenceError: caches is not defined

### ISSUE THREAD

**Issue by inverted-capital** [denoland/deploy_feedback#652]
### Problem description

The beta features for web caches isn't working for me.  I know it's beta, but its so good - what do I need to do to access it ?

My isolate was in australia: gcp-australia-southeast1

### Steps to reproduce

Deploy any code that tries to access the `caches` global:

```js
const cache = await caches.open('bart')

Deno.serve((req: Request) => new Response("Hello World"));
```

### Expected behavior

[Docs](https://docs.deno.com/deploy/manual/edge-cache) say its there - plz be there

**Comment by inverted-capital** [comment]
Original issue seems here: https://github.com/denoland/deploy_feedback/issues/74

**Comment by danopia** [comment]
I'm also looking for this feature for my AWS API codegen (first [in a PR](https://github.com/cloudydeno/deno-aws_api/pull/47) and then in [a simple public playground](https://dash.deno.com/playground/light-shark-81)). This API would really speed up and *also* simplify my Deno Deploy setup (a good combination!), I would love to give it a spin. Currently I am using an S3 bucket for a cache which means that other continents have increased latency.

I suppose the docs landed before the feature itself..

**Comment by inverted-capital** [comment]
This available for me now.  Docs say it is in closed beta.  Hopefully we all get it real soon.

https://docs.deno.com/deploy/manual/edge-cache/
