### ISSUE TITLE
[Bug]: Deno Deploy brings commits from the grave (unsuccessfully)

### ISSUE THREAD

**Issue by sanngridhr** [denoland/deploy_feedback#658]
### Problem description

Deno Deploy tries to use commits that no longer are hosted on the GitHub repo I fed it.

### Steps to reproduce

1. Create a repo under a name, let's say, orest58008/yamadachibot and make it a home for a little telegram bot made with Rust
2. Witness the horrors of shuttle[dot]rs and switch to Deno Deploy. Because of this, move the repo to orest58008/yamadachibot-rs and create a new one under the name orest58008/yamadachibot
3. Deploy this repo using Deno Deploy GitHub integration
4. See as Deno Deploy continuously tries to deploy commit from another repo (and fails)
5. Try to delete the offending repo. This doesn't help

### Expected behavior

Deno Deploy not travelling between the worlds

### Environment

- Deno version: the one at dash.deno.com
- OS: Browser?

### Possible solution

Add an option to exclude commits

**Comment by sanngridhr** [comment]
The e-mails are now maxing out (I can't unsubscribe from them)

**Comment by magurotuna** [comment]
Hi @Orest58008, I reviewed our internal logs and found that we did receive a webhook from GitHub that specified the commit ID that doesn't exist in your repo. I'm not certain why GitHub sent us such "wrong" webhook requests, but my guess is it may have something to do with your repository rename you performed, which may have caused some data to mess up.
I'm unsure if this helps, but could you try reinstalling [Deno Deploy GitHub App](https://github.com/apps/deno-deploy) and create a new commit again? If this doesn't resolve the issue, another option that I could come up with is to recreate a new repository and link it to Deno Deploy again, if that's feasible for you.
Thanks!

**Comment by sanngridhr** [comment]
The issue wasn't with Deno Deploy
