### ISSUE TITLE
"Projects" and "Deployments" terms confusing

### ISSUE THREAD

**Issue by ebebbington** [denoland/deploy_feedback#66]
1. I go to https://dash.deno.com/projects/
2. I click "New Project", *assuming* it will be a single project, though i was somewhat unsure because in places like Digital Ocean, "Projects" refered to a collection of droplets
3. I'm greeted with "A project is a named collection of deployments.", so this led me to think "Oh.. ok so i'm just naming the group to put a bunch of deployments under, alright", which led me to naming it "my-deployments" (thinking i could deploy 2 separate websites within this group)
4. Only when I created it, did i realise I was just creating a single deployment
5. So now I have my-deployments.deno.dev which isn't what i intended. Of course I was doing this to test deploy, see what it was all about and i could easily delete the deployment (and wasted no time)

Maybe this is just me, but I find these terms and descriptions confusing and somewhat contradicting

**Comment by mathiasrw** [comment]
Call it a "namespace" or "slug"

**Comment by nhrones** [comment]
This a way to group GitHub updates for an individual git-repo.  You'll see each git-commit-deploy in this collection.
It is one 'app' with a history of automatic deploys of that app. Think 'app'-update....

**Comment by satyarohith** [comment]
We have docs on "Projects" and "Deployments". I hope they provide clarity. 

Projects: https://deno.com/deploy/docs/projects
Deployment: https://deno.com/deploy/docs/deployments

If you still find something confusing, please don't hesitate to open an issue.
