### ISSUE TITLE
Support DENO_FUTURE=1 on Deno Deploy

### ISSUE THREAD

**Issue by maxbrieiev** [denoland/deploy_feedback#666]
### What problem are you trying to solve?

I set `DENO_FUTURE=1` variable for compatibility with certain third-party libraries that check for the presence of the `window` object to determine if the code is running in a browser or on a server. The problem is that I can't set this environment variable in Deno Deploy, because it says `Invalid key: DENO_ is a reserved prefix`.

### Describe the solution you'd like

I would like Deno Deploy to support the DENO_FUTURE=1 environment variable.

**Comment by rbetts** [comment]
Thank you for the feedback. Our plans are not to support the `DENO_FUTURE` gated features until Deno 2.0 is shipped. I apologize for the difficulty this is causing in this case.
