### ISSUE TITLE
[KV Feedback]: Make the unit symbol of read and write unit consistent

### ISSUE THREAD

**Issue by ooker777** [denoland/deploy_feedback#669]
[Deno Deploy Pricing | Deno](https://deno.com/deploy/pricing "Deno Deploy Pricing | Deno") says that a read unit is equivalent to 4 **kb**. Assuming it's a lazy writing to **kB** ([kilobyte](https://en.wikipedia.org/wiki/Kilobyte "Kilobyte - Wikipedia") = 1000 bytes). While in the analytics graph it says 4 **KiB** (kibibyte = 1024 bytes).

**Comment by losfair** [comment]
The correct unit is KiB (1024 bytes). We'll get it fixed. Thanks for finding this!

**Comment by rbetts** [comment]
Website update merged.
