### ISSUE TITLE
cite-space-validation这个域名不小心删除了，怎么恢复，或者你们帮我直接清空，我自己新建！

### ISSUE THREAD

**Issue by stomatodaealhw7170** [denoland/deploy_feedback#684]
### What problem are you trying to solve?

cite-space-validation这个域名不小心删除了，怎么恢复，或者你们帮我直接清空，我自己新建！

### Describe the solution you'd like

cite-space-validation这个域名不小心删除了，怎么恢复，或者你们帮我直接清空，我自己新建！

### Describe alternatives you've considered

cite-space-validation这个域名不小心删除了，怎么恢复，或者你们帮我直接清空，我自己新建！

### Documentation, Adoption, Migration Strategy

cite-space-validation这个域名不小心删除了，怎么恢复，或者你们帮我直接清空，我自己新建！

**Comment by magurotuna** [comment]
Hi @stomatodaealhw7170, unfortunately, as the project deletion modal says, project delete operation is irreversible. Do you have the source code of the deleted project? If so, you can just create a new project with the same source code and you'll get the same functionality.

**Comment by stomatodaealhw7170** [comment]
我有源代码，但是域名：cite-space-validation，被占用了。

[cid:01df7e2d-970a-4dd2-84b7-261713921823]

***@***.***中的域名名称。

这样我就可以重新新建
________________________________

**Comment by stomatodaealhw7170** [comment]
I have source code, but the domain name: cite space validation is occupied.

[cid:03b28a32-7a71-45d1-b311-e4277c40881f]


Requesting official account deletion: ***@***.*** The domain name in.
So I can create a new one
________________________________

**Comment by magurotuna** [comment]
Closing this issue as we've received an email and we'll continue there.
