### ISSUE TITLE
[Bug]: Link to documentation from Deno Deploy account webpage is broken

### ISSUE THREAD

**Issue by matthewjnield** [denoland/deploy_feedback#685]
### Problem description

The Deno Deploy overview webpage (https://dash.deno.com/account/overview) includes a button in the top right corner with the text "Docs", which presumably links to the documentation for Deno Deploy or the Deno Runtime, but it leads to a page that says "Not Found".

![image](https://github.com/denoland/deploy_feedback/assets/64328730/b6ce21f7-ed9a-44c1-be5f-327d1ecf5f4a)

![image](https://github.com/denoland/deploy_feedback/assets/64328730/63907ef6-cd39-46e2-946c-8c014fffc890)

### Steps to reproduce

1. Log in to Deno Deploy, and navigate to the overview page at https://dash.deno.com/account/overview.
2. Click on the "Docs" button in top right corner of the screen.
3. The button will follow the address https://docs.deno.com/deploy/docs which loads a page that says "Not Found"

### Expected behavior

I expected that the button would lead to the documentation for Deno Deploy or the Deno Runtime, using a link such as https://docs.deno.com/deploy/manual/ or https://docs.deno.com/runtime/manual/

### Environment

Deno version: 1.44.4
OS: Windows 11
Browser: Firefox

### Possible solution

Change the address that the button follows from https://docs.deno.com/deploy/docs to a working address of the Deno Deploy documentation, such as https://docs.deno.com/deploy/manual/

As an alternative consideration, the "Docs" button may be redundant in the first place, as the overview page includes large buttons near the top of the page which are linked to the documentation for Deno Deploy ("Getting Started") and the Deno Runtime ("Runtime Documentation").

As these two buttons are present and very noticeable, it may be sufficient to remove the "Docs" button from the top right corner of the page. It may also be a good idea to change the names of the two buttons to clarify what they link to, perhaps with the names "Deno Deploy Documentation" and "Deno Runtime Documentation".

**Comment by magurotuna** [comment]
Thank you for catching this issue! We've also found several other links that are broken now, probably because of our rearchitecturing around the documentation (https://github.com/denoland/deno-docs/pull/519). The fixes for these errors will be shipping within the next couple days.

> As an alternative consideration, the "Docs" button may be redundant in the first place, as the overview page includes large buttons near the top of the page which are linked to the documentation for Deno Deploy ("Getting Started") and the Deno Runtime ("Runtime Documentation").
>
> As these two buttons are present and very noticeable, it may be sufficient to remove the "Docs" button from the top right corner of the page. It may also be a good idea to change the names of the two buttons to clarify what they link to, perhaps with the names "Deno Deploy Documentation" and "Deno Runtime Documentation".

Thanks for this valuable feedback too. I agree that we may need to reconsider what to put in the dashboard for better user experience. We'll bring it up and think about it in the team.
