### ISSUE TITLE
Analytics UI Duplicated

### ISSUE THREAD

**Issue by jfancher** [denoland/deploy_feedback#69]
This is an insignificant UI bug, but I've run into it a few times so I figured it was worth filing.

If you click on a date range in the Analytics view (e.g. "7 days"), then change it again before the data finishes loading, the UI doubles up like this (in Firefox, in case that ends up being relevant):

<img width="996" alt="image" src="https://user-images.githubusercontent.com/1724965/125700278-fa55cc6b-e070-42d9-9019-0366760c0713.png">

**Comment by wperron** [comment]
Thanks for the report, we're looking into it!

**Comment by kt3k** [comment]
@jfancher Now this is fixed. Thank you for reporting!
