### ISSUE TITLE
[Bug]: An internal server error occurred on deploy

### ISSUE THREAD

**Issue by morgothulhu** [denoland/deploy_feedback#697]
### Problem description

Getting a `An internal server error occurred on deploy` on deploy of a feature branch `feature/auth` on https://dash.deno.com/projects/trooper-sms - no idea why it is failing.

`deno bundle {entrypoint}` works locally.

### Steps to reproduce

Push to feature branch

### Expected behavior

deploys! or show logs so the root cause is known

**Comment by morgothulhu** [comment]
seems all deployments are broken. just did a branch of the last known good and still running into the same issue

**Comment by magurotuna** [comment]
Thanks for reporting and sorry for the trouble. I checked the relevant internal logs, but unfortunately it looks like the recorded logs are obscure so it's hard to figure out the root cause of this issue for now. We'll try to record more logs so we can investigate it further.

**Comment by morgothulhu** [comment]
@magurotuna thank you. Lmk when you want me to push again

**Comment by magurotuna** [comment]
@morgothulhu We've identified the reason why it happened. Briefly, it was because we updated the code related to building a deployment, and it now can't handle file names with whitespace. We're doing a quick fix for this issue. I'll get back to you once the patch is applied.

**Comment by magurotuna** [comment]
@morgothulhu thanks for your patience, the patch has landed and I have just confirmed that the minimal reproduction code can now successfully deploy. Can you try your deployment again?

**Comment by morgothulhu** [comment]
@magurotuna retried deployment and all is well. Thank you for the quick turn-around!
