### ISSUE TITLE
Documentation on regions/locations/POPs/infrastructure

### ISSUE THREAD

**Issue by potatopotaro** [denoland/deploy_feedback#7]
What and how many regions/locations are Deno Deploy projects distributed to? I'd love to have this info for comparing to cloudflare workers. Cheers :)

**Comment by ry** [comment]
Deploy currently runs in every GCP data center:
- Taiwan
- Hong Kong
- Tokyo
- Osaka
- Seoul
- Mumbai
- Singapore
- Jakarta
- Sydney
- Warsaw
- Finland
- Belgium
- London
- Frankfurt
- Netherlands
- Zurich
- Montréal
- São Paulo
- Iowa
- South Carolina
- North Virginia
- Oregon
- Los Angeles
- Utah
- Las Vegas

**Comment by lucacasonato** [comment]
This information is now in the deploy docs at https://deno.com/deploy/docs/regions
