### ISSUE TITLE
[Bug]: An internal server error occurred on deploy

### ISSUE THREAD

**Issue by morgothulhu** [denoland/deploy_feedback#707]
### Problem description

Trying to deploy last known good (which deployed previously successfully) - now no-luck.

`An internal server error occurred.`

https://dash.deno.com/projects/trooper-sms-dev/

### Steps to reproduce

redeploy last known good

### Expected behavior

LKG should re-deploy successfully

**Comment by magurotuna** [comment]
Hi @morgothulhu, sorry for the inconvenience. I looked through our internal logs to try to figure out what was happening while creating your new deployment, but it looks like we didn't get any useful logs.
I will modify our system so it will emit more logs that can help with investigations for future occurrences, but in order for us to troubleshoot your specific issue more quickly, would you mind sharing your project source code with us? If you can, we kindly ask you to either email us at deploy@deno.com or DM me at discord `yusuke_magurotuna`. Thank you!

**Comment by morgothulhu** [comment]
Update. The issue was related to `"experimentalDecorators": false` - seems broken in 1.46
