### ISSUE TITLE
[Bug]: Invalid Version Error

### ISSUE THREAD

**Issue by nekodendislike** [denoland/deploy_feedback#708]
### Problem description

I encountered the below error while using Deno deploy and Fresh.
![IMG_1719](https://github.com/user-attachments/assets/82cc45c6-7082-453f-8e5c-0139baa8793b)

### Steps to reproduce

1. Commit to github
2. Github Actions starts deploying
3. An error occurs in the Deploy section.

### Expected behavior

Deploys normally without any errors.

### Environment

- Deno Fresh 1.6.8
- Deno deploy(with Github actions)

**Comment by lucacasonato** [comment]
Did you accidentally link the `dev.ts` file instead of `main.ts`

**Comment by nekodendislike** [comment]
That's exactly it. Thank you.
