### ISSUE TITLE
The use of addEventListener

### ISSUE THREAD

**Issue by mpcref** [denoland/deploy_feedback#71]
The use of `addEventListener` to start listening for incoming requests suggests that:

1. Multiple listeners can be added
2. A listener can be removed with `removeEventListener`
3. A listener can be added, removed and then added again
4. Adding the same listener more then once has no effect

None of these cases are currently supported.
If compliance with the `EventTarget` interface is not planned for a future release then please consider using a different method to start listening for incoming requests.

**Comment by bnoordhuis** [comment]
Thanks for the feedback. We're in the process of phasing out `addEventListener("fetch", ...)` in favor of `Deno.listen() + Deno.serveHttp()`, to promote interop between Deploy and the Deno CLI.

**Comment by mpcref** [comment]
IMHO within the context of Deploy it would make sense if the default export of the module at the source URL would be the request handler function:
```
export default function (event) {
  event.respondWith(new Response("Hello world"));
}
```

**Comment by mpcref** [comment]
This has been resolved. Deno now uses `Deno.serve`.
