### ISSUE TITLE
Dark mode?

### ISSUE THREAD

**Issue by wdalhaj** [denoland/deploy_feedback#719]
### What problem are you trying to solve?

I have photophobia (light sensitivity), current theme is too bright for me, especially with too much empty spaces in ui.

### Describe the solution you'd like

enabledark mode option. 

### Describe alternatives you've considered

using dark mode browser plugins?

**Comment by marvinhagemeister** [comment]
Duplicate of https://github.com/denoland/deploy_feedback/issues/82
