### ISSUE TITLE
How to check if running in Deno Deploy?

### ISSUE THREAD

**Issue by HamishWHC** [denoland/deploy_feedback#73]
I've got an env.ts script that loads envvars from .env using [dotenv](https://deno.land/x/dotenv@v2.0.0). But this fails on deno deploy due to a lack of FS functions. I tried to detect being in Deno Deploy via `Deno.permissions.query` (would also work nicely if run locally without FS permissions) but this function isn't provided. What's the preferred/"official" method of determining whether or not my code is running on Deno Deploy?

I need it to be locally runnable as I have scripts that set up functionality for the hosted version. I could separate the dotenv code from the code being deployed but would like to avoid this if possible.

**Comment by kt3k** [comment]
A deployment in Deno Deploy always sets 'DENO_DEPLOYMENT_ID' environment variable. So you can use the following expression:

```ts
const isDenoDeploy = Deno.env.get("DENO_DEPLOYMENT_ID") !== undefined;
```

**Comment by HamishWHC** [comment]
Thanks!

**Comment by ignoramous** [comment]
Is `DENO_DEPLOYMENT_ID` part of public API? If it changes in the future, our deploys will end up in a pickle.

**Comment by zzz6519003** [comment]
@kt3k it could possibly run in a node env, where it don't have `Deno`

**Comment by DavidDTA** [comment]
It is mentioned in the docs here: https://docs.deno.com/deploy/manual/environment-variables/#default-environment-variables
