### ISSUE TITLE
[Bug]: Missing --global flag for installing deployctl

### ISSUE THREAD

**Issue by nounder** [denoland/deploy_feedback#730]
### Problem description

"Prefer the command line?" section on the website doesn't work on Deno 2.0.

> With the latest version of Deno installed, install the deployctl tool from [JSR](https://jsr.io/).
> deno install -Arf jsr:@deno/deployctl

### Steps to reproduce

1. Run `deno install -Arf jsr:@deno/deployctl`
2. See:
```
error: the following required arguments were not provided:
  --global

Note: Permission flags can only be used in a global setting
``` 

### Expected behavior

deployctl is installed w/o an error

### Environment

Deno 2.0

**Comment by arnauorriols** [comment]
Thanks!
