### ISSUE TITLE
[Bug]: Deno KV: txnproxy call timed out

### ISSUE THREAD

**Issue by ChristianSiegert** [denoland/deploy_feedback#738]
### Problem description

When a call to Deno KV is made, occasionally the call runs into a timeout (see error below). It used to work in the past without problem.

Example 1:
```
Error: txnproxy call timed out
    at async doAtomicWriteInPlace (ext:deno_kv/01_db.ts:629:10)
    at async AtomicOperation.commit (ext:deno_kv/01_db.ts:408:26)
    at async save (file:///src/src/models/redacted.ts:48:12)
    at async file:///src/src/models/redacted.ts:16:9
```

Example 2:
```
Error: txnproxy call timed out
    at async Kv.get (ext:deno_kv/01_db.ts:57:28)
    at async getFoo (file:///src/src/models/redacted.ts:57:10)
    at async Object.handler (file:///src/src/pages/redacted.ts:183:24)
    at async handler (https://…/redacted.ts:126:24)
    at async ext:deno_http/00_serve.ts:369:18
```

### Steps to reproduce

1. Interact with Deno KV, e.g. `await kv.atomic().sum(key, n).commit()` or `await kv.get(key)`.

### Expected behavior

No timeout occurs.

### Environment

Deno Deploy

### Additional context

The issue is not specific to a region. The error logs show these regions (more regions could be affected but the log is cut off):

- gcp-asia-south1
- gcp-asia-southeast1
- gcp-europe-west2
- gcp-europe-west3
- gcp-southamerica-east1
- gcp-us-east4
- gcp-us-south1
- gcp-us-west2

The most recent occurrences at the time of writing:
- Oct 26, 2024, 06:47:40 AM UTC (gcp-asia-south1)
- Oct 26, 2024, 06:47:36 AM UTC (gcp-europe-west2)
- Oct 26, 2024, 06:47:35 AM UTC (gcp-us-east4)
- Oct 26, 2024, 06:47:34 AM UTC (gcp-europe-west3)

**Comment by magurotuna** [comment]
Sorry for the late response. Do you still see this issue? We are aware that sometimes this timeout issue occurs, and we address it every time we detect.

**Comment by ChristianSiegert** [comment]
I don’t see this issue anymore.

**Comment by kewp** [comment]
I'm seeing this issue now. Strangely only in certain regions (like Spain)

<img width="784" alt="Image" src="https://github.com/user-attachments/assets/cdb4c4ff-7dc2-499f-be35-1bf45a77385b" />
