### ISSUE TITLE
[Bug]: Custom tlds are not supported

### ISSUE THREAD

**Issue by Markcial** [denoland/deploy_feedback#749]
### Problem description

Seems to be that there are some tlds that are not supported, trying to deploy here: https://hns.id/domain/soab.mfers/dns, but it can't be configured in the DNS zone

### Steps to reproduce

Go to dns configuration and introduce "soab.mfers" it won't allow

### Expected behavior

Be able to configure that domain with DNS

**Comment by lucacasonato** [comment]
Deno Deploy only supports TLDs registered with IANA that are resolvable through the DNS root servers (https://en.wikipedia.org/wiki/Top-level_domain). These kinds of crypto names are not resolvable through DNS, and thus can not be used with Deno Deploy.
