### ISSUE TITLE
Logs Page Unstable

### ISSUE THREAD

**Issue by kyeotic** [denoland/deploy_feedback#75]
The logs page often hangs (white screen) when refreshing. When this happens navigating back with the browser back button updates the URL to the project page, but this also hangs until refreshed again.

The logs page also fails to show most logs. It often tells me no logs exist after several API responses. It rarely contains logs from failures. Crash Reports is likewise empty, I have yet to see a single Crash Report from deploys with errors that block all responses.

**Comment by mpcref** [comment]
Another issue with the logs page is that after a while the ordering of the logs gets messed up.

**Comment by wperron** [comment]
Thanks for the report; We're aware of these issues with the logs page, fixes will be deployed soon for the failure logs not showing issue. We're also working on improving perf and usability on that section.

**Comment by mpcref** [comment]
What would probably help is if each log line would be prefixed with an edge location identifier. (and filter by edge location)
In general it would be nice to have an env var that identifies the edge location.

**Comment by kyeotic** [comment]
> What would probably help is if each log line would be prefixed with an edge location identifier. (and an option to filter by edge location)
> In general it would be nice to have an env var that identifies the edge location instance.

I agree. This probably deserves its own issue for tracking.

**Comment by bnoordhuis** [comment]
>  In general it would be nice to have an env var that identifies the edge location instance.

That exists: `Deno.env.get("DENO_REGION")`

> What would probably help is if each log line would be prefixed with an edge location identifier. (and an option to filter by edge location)

That's a good suggestion. We'll take it into consideration, thanks.
