### ISSUE TITLE
[Bug]:  dashboard isn't loaded on Edge browser

### ISSUE THREAD

**Issue by champ18ion** [denoland/deploy_feedback#757]
### Problem description

the deploy dashboard isn't loading, its blank screen
![image](https://github.com/user-attachments/assets/be550ea5-dea1-4531-9dfa-536054dacc6a)

### Steps to reproduce

 login to deno deploy

### Expected behavior

 should have all functionality

**Comment by magurotuna** [comment]
Are you still experiencing this issue? I wonder if this is a temporary error.

**Comment by champ18ion** [comment]
Yes! the Issue still persists

> Are you still experiencing this issue? I wonder if this is a temporary error.

**Comment by ChristianSiegert** [comment]
1. Do you see any errors in your browser’s console?
2. Do you see any failed requests in your browser’s network tab?
3. Try another browser, or disable your browser’s strict security mode, or disable all browser plugins and see if this resolves the problem. Then one by one enable plugins and refresh the site until the problem appears again.

**Comment by champ18ion** [comment]
I saw the browser console and network tab at that time the issue was basically related to some client authentication or I would share the screenshots as well.

I switched to **arc browser** and it was fine there.
I was facing the issue on edge

**Comment by magurotuna** [comment]
Do you have some extensions installed on the edge browser?

**Comment by champ18ion** [comment]
I disbaled all and checked its working now
