### ISSUE TITLE
 Is `window` meant to be defined on Deno Deploy environments?

### ISSUE THREAD

**Issue by horizoncarlo** [denoland/deploy_feedback#758]
### 🔍

- [x] Did you search for existing issues?

### Type of feedback

Bug report

### Description

Not sure if I'm misunderstanding something here, but on my local setup I had been using `globalThis.onClient = typeof window !== 'undefined';` to determine in a shared JS module if I'm in the browser or the server. This works as expected.

But when I put the same project on Deno Deploy the `window` property is available?!
![image](https://github.com/user-attachments/assets/6045f641-0900-4469-ac1e-682ffdb3f462)

Am I misunderstanding something?

### Steps to reproduce (if applicable)

1. Create a basic Deno project, and output whether `window` exists or not

### Expected behavior (if applicable)

Expect to see an undefined window on server, but available on client

Whereas I see both places have window for a Deno Deploy setup.

### Possible solution (if applicable)

For now using this as a slightly safer check:
`globalThis.onClient = typeof window !== 'undefined' && typeof Deno === 'undefined';`

### Additional context

Thought `window` was removed and reliable to check against via https://github.com/denoland/deno/issues/13367

Would prefer if not then the Deno Deploy docs are updated (...or I'm blind and missed it :100:)

**Comment by magurotuna** [comment]
`window` got removed since Deno 2.0 but Deno Deploy still runs v1-based runtime, although we are working on upgrading it to v2-based.
That said, our plan as of now is to keep `window` available after the upgrade on Deno Deploy. We'll discuss it internally a bit further if this is a right decision and get back to you.

**Comment by horizoncarlo** [comment]
I didn't realize at all that Deno Deploy is still on v1. That makes a lot more sense, thanks for clarifying. I'll make my "possible solution" approach permanent in my app and leave it at that.

**Comment by magurotuna** [comment]
Just FYI, we've decided to remove `window` after upgrading Deno Deploy runtime to Deno v2. Your permanent solution should keep working fine any way.
