### ISSUE TITLE
[Bug]: `deployctl deploy` doesn't update prod deployment

### ISSUE THREAD

**Issue by frankdeno** [denoland/deploy_feedback#759]
### Problem description

When I deploy to production, it doesn't update. 

development deployment and production deployment should be equal:
They are not equal.

### Steps to reproduce

Create some kind of index.html. 
Serve it via deployctl and jsr:@std/http/file-server 
Make a change. 
Deploy again, see if change is in deployment.

### Expected behavior

It should immeditaltyl deploy and work on production. 

### Environment

My folder structure:

```
.
├── CCM_All.glb
├── components
│   └── Card.js
├── computer.glb
├── data
│   └── cards.js
├── deno.json
├── favicon.ico
├── favicon.svg
├── icons
│   ├── favicon.svg
│   ├── icon-192x192.png
│   ├── icon-500x500.png
│   ├── icon-512x512.png
│   └── login.svg
├── index.html
├── main.ts
├── manifest.json
├── router.js
├── screenshots
│   ├── desktop.png
│   └── mobile.png
├── sw.js
├── utils
│   ├── pocketbase.es.mjs
│   ├── three
│   ├── three.module.js
│   └── XRButton.js
└── views
    ├── AnimationView.js
    ├── ChatView.js
    ├── LoginView.js
    ├── LogoutView.js
    ├── PreviewView.js
    ├── ProductView.js
    └── RegisterView.js

7 directories, 29 files
``` 

```
deno --version 
deno 2.1.1+5ca47ee (canary, release, x86_64-unknown-linux-gnu)
v8 13.0.245.12-rusty
typescript 5.6.2
```  

``` 
deployctl --version
deployctl 1.13.0
``` 

### Possible solution

It has something todo with the caching. 
I bet on it. :D 

### Additional context

```
zauber/apps/web on  main [!?] via 🦕 v2.1.1+5ca47ee via  
❯ deno task
Available tasks:
- serve
    deno run --allow-read --allow-net main.ts
- deploy
    deployctl deploy --prod --save-config --entrypoint=main.ts --project=zauber main.ts

zauber/apps/web on  main [!?] via 🦕 v2.1.1+5ca47ee via  
❯ deno task deploy
Task deploy deployctl deploy --prod --save-config --entrypoint=main.ts --project=zauber main.ts
i Using config file '/home/frank/zauber/apps/web/deno.json'
√ Deploying to project zauber.
√ Entrypoint: /home/frank/zauber/apps/web/main.ts
i Uploading all files from the current dir (/home/frank/zauber/apps/web)
√ Found 29 assets.
√ Uploaded 1 new asset.
√ Production deployment complete.
√ Updated config file '/home/frank/zauber/apps/web/deno.json'.

View at:
 - https://zauber-bewqttrw43q4.deno.dev
 - https://zauber.deno.dev
 ```  
 
 I tried to use a main.ts instead of jsr:@std/http/file-server
 Didn't changed something.
 
 ```typescript
 import { serveDir } from "jsr:@std/http/file-server";

Deno.serve((req) => {
  return serveDir(req, {
    fsRoot: ".",
    urlRoot: "",
    showDirListing: true,
    enableCors: true,
  });
}, { port: 3000 });
```

**Comment by magurotuna** [comment]
Does your `deno.json` have `deploy` property? If it does, would you mind sharing it with us?

**Comment by frankdeno** [comment]
### Hola 

It is fixed. Should be on my side.

Sure. [deno.json](https://gitlab.com/frankbevr/zauber/-/blob/main/apps/web/deno.json?ref_type=heads)

Sadly I don't remeber the how i fixed it. 

I think there were 2 main points
- delete everything, especially because its also pwa 
- change routing from / to has routing /#/ via webhashhistory in router.js

Lessons learned.
- Always check everything in your browser.
- Use Hashrouting if I want to copy paste url's 

Thanks for your response :v: 

### Cheers :beers: 

P.s. If you know how I can organize it in a monorepo, let me know. The current solution works but not optimal.
