### ISSUE TITLE
FaunaDB tutorial has a few issues

### ISSUE THREAD

**Issue by tomzij** [denoland/deploy_feedback#77]
Hi,
I followed the tutorial: https://deno.com/deploy/docs/tutorial-faunadb

1. When adding the POST request, the code line: `const { quote, author } = body;`
leads to: `Property 'quote' does not exist on type '{ [key: string]: unknown; } | undefined'.`

Perhaps it should be changed to something like this (there's probably a more elegant solution, but this works :) ):
```
const quote = body?.quote as string;
const author = body?.author as string;
```
2. When adding in the Fauna persistance, the tutorial says to remove the quotes array. That leads to this line not working (since quotes is now undefined: `return json({ quotes });`
Maybe it should be: `return json({ });`

Then instead of saying "You should see the quote in the response." you could say: "Notice how the quote was added to your collection in FaunaDB". Alternatively, removing the quotes array should be done in the next section where the getAllQuotes function is replacing this line

3. This line does not work:
``` 
const query = gql`
    query {
``` 
 it could be changed to: 

```
const query = `
    query {
```

4. The sift version could be updated to 0.3.5

5. I would consider changing the final step from:
> - Click on Deploy URL, paste the raw link and click on Deploy.
> - That's it.

to:
> - Click on Deploy URL, paste the raw link and click on Deploy.
> - Click on **Visit** to see your project live on Deno Deploy (remember to as /quotes to the url to see the content of your FaunaDB)
> - That's it.

**Comment by satyarohith** [comment]
Thanks, @tomzij! The tutorial is updated. :)
