### ISSUE TITLE
allow read my own cloned repo

### ISSUE THREAD

**Issue by elycheikhsmail** [denoland/deploy_feedback#80]
allow read my own repo contentent - for example - for generating html to serve to client using template engine like handelbar/dunjucks

**Comment by bnoordhuis** [comment]
I'm not sure what you're asking. Can you post a brief code snippet that outlines how you would like it to work?

**Comment by elycheikhsmail** [comment]
I use template engine (dunjucks/jinja2) for genrate html text, dunjucks needs read perimission to read templates contentent

**Comment by bnoordhuis** [comment]
I'm afraid it's still not clear to me. Post a code snippet?

**Comment by elycheikhsmail** [comment]
> I'm afraid it's still not clear to me. Post a code snippet?

i will do
but why afraid ? lol

**Comment by satyarohith** [comment]
> I use template engine (dunjucks/jinja2) for genrate html text, dunjucks needs read perimission to read templates contentment

 Are you looking for something similar to [`Deno.readFile()`](https://doc.deno.land/builtin/stable#Deno.readFile)?

> but why afraid ? lol

@elycheikhsmail It's a polite way to say that we don't understand your description. See https://www.macmillandictionary.com/dictionary/british/i-m-afraid

**Comment by elycheikhsmail** [comment]
> > I use template engine (dunjucks/jinja2) for genrate html text, dunjucks needs read perimission to read templates contentment
> 
> Are you looking for something similar to [`Deno.readFile()`](https://doc.deno.land/builtin/stable#Deno.readFile)?
> 
> > but why afraid ? lol
> 
> @elycheikhsmail It's a polite way to say that we don't understand your description. See https://www.macmillandictionary.com/dictionary/british/i-m-afraid

yes I'm looking for simething similar to Deno.readText but in limited scope, the read may be alias for fetch in deno deploy

**Comment by satyarohith** [comment]
.@elycheikhsmail, we now support `Deno.readFile()` on Deno Deploy: https://deno.com/deploy/docs/runtime-fs
