### ISSUE TITLE
"visit" vs. "view"

### ISSUE THREAD

**Issue by kjk** [denoland/deploy_feedback#81]
Nitpicking, I know, but:

* on https://dash.deno.com/projects, the button to go to deployed website is "Visit"
* on the page for a given project (like https://dash.deno.com/projects/essential-books-redirect), the button says "View"

The naming should be consistent

**Comment by bnoordhuis** [comment]
Nitpick appreciated! We'll fix this shortly.

**Comment by kt3k** [comment]
@kjk We now use `View` for both pages. Thank you for reporting this!
