### ISSUE TITLE
Header UI rendering issue in beta 2

### ISSUE THREAD

**Issue by khaled** [denoland/deploy_feedback#84]
Logs and Crash Reports buttons sit on top of Feedback, Docs, and user icon:

<img width="1196" alt="Screen Shot 2021-09-06 at 11 39 33 AM" src="https://user-images.githubusercontent.com/11412/132240250-14d1709b-ea6b-4167-80ca-e75ce8ddc469.png">

Using Firefox 91.0.2 on macOS 10.15.7.

**Comment by lucacasonato** [comment]
This should now be resolved. Thanks for the report!

**Comment by khaled** [comment]
thanks @lucacasonato!
