### ISSUE TITLE
`Deno.test` should be ignored

### ISSUE THREAD

**Issue by AnInternetTroll** [denoland/deploy_feedback#89]
`Deno.test` is a function used to write tests. Tests don't need to run on deno deploy, and in a normal deno enviorment they don't run at runtime either. As such I think `Deno.test` shouldn't throw an error, as seen here 
![image](https://user-images.githubusercontent.com/40470127/133483746-b897c5e6-9d04-42cc-abfe-783d7a089593.png)

**Comment by bartlomieju** [comment]
I believe it makes sense from usability perspective to define `Deno.test` in deploy - but it should be a noop so it doesn't error out like in the example above.

**Comment by bartlomieju** [comment]
`Deno.test()` calls will not error out anymore. This should be live within a couple days.
