### ISSUE TITLE
Allow Running Build Commands Before Deployment

### ISSUE THREAD

**Issue by shadowtime2000** [denoland/deploy_feedback#9]
Having a small CI to run build commands before something gets deployed would be pretty cool. It would allow us at alephjs to support deploying alephjs projects to deploy. It would just be great for frameworks like next and aleph and stuff that try to be deployment platform agnostic while still having stuff like serverless functions.

**Comment by ry** [comment]
I suppose you want this for generating static assets? Or why does aleph need a build step?

**Comment by lowlighter** [comment]
I'd like something similar too 👍 
It would be quite useful for running deno bundle and other static assets generation

**Comment by codehz** [comment]
Workaround:
Create a dedicated repo for deployment, and then use github action push generated code to it. (yes it is possible to use branch, but ALL branch will be deployed...

**Comment by satyarohith** [comment]
Hi. 

We introduced a GitHub Action for this use case: https://github.com/denoland/deployctl/tree/main/action

Related blog posts:
- https://deno.com/blog/hugo-blog-with-deno-deploy
- https://deno.com/blog/deploy-static-files

Thanks!
