### ISSUE TITLE
Stale values return

### ISSUE THREAD

**Issue by sylc** [denoland/deploy_feedback#94]
On the live Deno chat app example https://denochat.deno.dev/ or https://s-chat-test-fix.deno.dev/ which is the same but with `fresh` updated to latest due to https://github.com/denoland/deploy_feedback/issues/91 , the return values are the one from the previous submission.

Repro
- navigate to https://s-chat-test-fix.deno.dev/ 
- enter 1, click send. nothing appear on screen
- enter 2 click send, 1 appear.

This does NOT happen on a local environment:
```
deno run -A --unstable --watch https://raw.githubusercontent.com/sylc/deploy_chat/scau_fix/main.ts
```

so I'm thinking the issue might be with Deno deploy

$ deno --version
deno 1.14.0 (release, x86_64-pc-windows-msvc)
v8 9.4.146.15
typescript 4.4.2

**Comment by nhrones** [comment]
@sylc I have one working if you'd like to compare.
https://deploy-socket-chat.deno.dev/
https://github.com/nhrones/WS-Chat

**Comment by sylc** [comment]
@nhrones Thanks for sharing this. It is interesting. 

However one part of this issue is that the same code behave differently locally and on deno deploy, which is not clear to me why.

**Comment by nhrones** [comment]
I have the same experience, so I only test on Deploy!  Remember that Deploy BroadcastChannel only works across Deploy isolates!

**Comment by sylc** [comment]
This seems to have been fixed now.
