### ISSUE TITLE
Exceeds CPU time limit only on first few accesses

### ISSUE THREAD

**Issue by ayame113** [denoland/deploy_feedback#95]
After a new deployment, I get a "CPU time limit exceeded" error only on the first few accesses.
It may be related to the slow startup time (6 seconds) when running in the CLI.

Is it possible that this restriction will be relaxed?

![image](https://user-images.githubusercontent.com/40050810/133939662-7487f7d8-e8f5-42e1-b808-5f7a79ad2219.png)

---
By the way, it takes about 6 seconds for the `console.log` placed before the first import statement to be output, so I think it's taking time for something other than js execution.

```js
// temp.ts
console.log(performance.now());
import "https://raw.githubusercontent.com/ayame113/deploy_gitrepo/v0.0.2/mod.ts";
```

```shell
> deno run -A ./temp.ts
5653.2906 #This will be output after waiting about 6 seconds
```

**Comment by bnoordhuis** [comment]
Your script is loading big WASM blobs, https://deno.land/x/ammonia and https://deno.land/x/swc. That's likely the cause of those errors, they're taking too long to parse/compile. They're 7 or 8 MB combined.

I'll discuss internally if it makes sense to allow a grace period for starting scripts. Thanks for the report.

**Comment by bnoordhuis** [comment]
It's been fixed. Still in the process of being rolled out so give it 24-48 hours.

**Comment by ayame113** [comment]
Thank you!
