### ISSUE TITLE
Can't access Deno.version.deno

### ISSUE THREAD

**Issue by tatemz** [denoland/deploy_feedback#98]
I'm getting the following error when using Aleph.js

```
TypeError: Cannot read properties of undefined (reading 'deno')
```

[Source file](https://deno.land/x/aleph@v0.3.0-beta.17/server/helper.ts#L27)

**Comment by bnoordhuis** [comment]
That's something that needs to be fixed in aleph.js. There's no `Deno.version.deno` in Deploy.

I see more things in that file that won't work out of the box with Deploy - stuff like `Deno.exit()` and `Deno.remove()` - so there's probably a bigger refactor necessary to get it to run on Deploy.

**Comment by lucacasonato** [comment]
`Deno.version.deno` works in Deno Deploy now.
